//
//  TimeZone+IATA.swift
//  IBKit
//
//  Created by Sten Soosaar on 08.06.2026.
//

import Foundation


public extension TimeZone {
	
	static func from(iana:String)->TimeZone?{
		
		switch iana {
		case "Africa/Addis_Ababa":					self.init(identifier: "Africa/Nairobi")
		case "Africa/Asmara":	 					self.init(identifier: "Africa/Nairobi")
		case "Africa/Bamako":	 					self.init(identifier: "Africa/Abidjan")
		case "Africa/Bangui":	 					self.init(identifier: "Africa/Lagos")
		case "Africa/Banjul":	 					self.init(identifier: "Africa/Abidjan")
		case "Africa/Blantyre":	 					self.init(identifier: "Africa/Maputo")
		case "Africa/Brazzaville":					self.init(identifier: "Africa/Lagos")
		case "Africa/Bujumbura":					self.init(identifier: "Africa/Maputo")
		case "Africa/Conakry":	 					self.init(identifier: "Africa/Abidjan")
		case "Africa/Dakar": 						self.init(identifier: "Africa/Abidjan")
		case "Africa/Dar_es_Salaam": 				self.init(identifier: "Africa/Nairobi")
		case "Africa/Djibouti": 					self.init(identifier: "Africa/Nairobi")
		case "Africa/Douala": 						self.init(identifier: "Africa/Lagos")
		case "Africa/Freetown": 					self.init(identifier: "Africa/Abidjan")
		case "Africa/Gaborone": 					self.init(identifier: "Africa/Maputo")
		case "Africa/Harare":						self.init(identifier: "Africa/Maputo")
		case "Africa/Kampala":						self.init(identifier: "Africa/Nairobi")
		case "Africa/Kigali":						self.init(identifier: "Africa/Maputo")
		case "Africa/Kinshasa":						self.init(identifier: "Africa/Lagos")
		case "Africa/Libreville":					self.init(identifier: "Africa/Lagos")
		case "Africa/Lome":							self.init(identifier: "Africa/Abidjan")
		case "Africa/Luanda":						self.init(identifier: "Africa/Lagos")
		case "Africa/Lubumbashi":					self.init(identifier: "Africa/Maputo")
		case "Africa/Lusaka":						self.init(identifier: "Africa/Maputo")
		case "Africa/Malabo":						self.init(identifier: "Africa/Lagos")
		case "Africa/Maseru":						self.init(identifier: "Africa/Johannesburg")
		case "Africa/Mbabane":						self.init(identifier: "Africa/Johannesburg")
		case "Africa/Mogadishu":					self.init(identifier: "Africa/Nairobi")
		case "Africa/Niamey":						self.init(identifier: "Africa/Lagos")
		case "Africa/Nouakchott":					self.init(identifier: "Africa/Abidjan")
		case "Africa/Ouagadougou":					self.init(identifier: "Africa/Abidjan")
		case "Africa/Porto-Novo":					self.init(identifier: "Africa/Lagos")
		case "Africa/Timbuktu":						self.init(identifier: "Africa/Abidjan")
		case "America/Anguilla":					self.init(identifier: "America/Port_of_Spain")
		case "America/Antigua": 					self.init(identifier: "America/Port_of_Spain")
		case "America/Argentina/ComodRivadavia":   	self.init(identifier: "America/Argentina/Catamarca")
		case "America/Aruba":						self.init(identifier: "America/Curacao")
		case "America/Atka":						self.init(identifier: "America/Adak")
		case "America/Buenos_Aires":	 			self.init(identifier: "America/Argentina/Buenos_Aires")
		case "America/Catamarca":				 	self.init(identifier: "America/Argentina/Catamarca")
		case "America/Cayman":					 	self.init(identifier: "America/Panama")
		case "America/Coral_Harbour":				self.init(identifier: "America/Atikokan")
		case "America/Cordoba":				 		self.init(identifier: "America/Argentina/Cordoba")
		case "America/Dominica":					self.init(identifier: "America/Port_of_Spain")
		case "America/Ensenada":					self.init(identifier: "America/Tijuana")
		case "America/Fort_Wayne":					self.init(identifier: "America/Indiana/Indianapolis")
		case "America/Godthab":						self.init(identifier: "America/Nuuk")
		case "America/Grenada":						self.init(identifier: "America/Port_of_Spain")
		case "America/Guadeloupe":					self.init(identifier: "America/Port_of_Spain")
		case "America/Indianapolis":				self.init(identifier: "America/Indiana/Indianapolis")
		case "America/Jujuy":						self.init(identifier: "America/Argentina/Jujuy")
		case "America/Knox_IN":				 		self.init(identifier: "America/Indiana/Knox")
		case "America/Kralendijk":					self.init(identifier: "America/Curacao")
		case "America/Louisville":					self.init(identifier: "America/Kentucky/Louisville")
		case "America/Lower_Princes":			 	self.init(identifier: "America/Curacao")
		case "America/Marigot": 		 			self.init(identifier: "America/Port_of_Spain")
		case "America/Mendoza": 		 			self.init(identifier: "America/Argentina/Mendoza")
		case "America/Montreal":			 		self.init(identifier: "America/Toronto")
		case "America/Montserrat":			 		self.init(identifier: "America/Port_of_Spain")
		case "America/Porto_Acre":			 		self.init(identifier: "America/Rio_Branco")
		case "America/Punta_Arenas":				self.init(identifier: "Magallanes Region")
		case "America/Rosario":			 			self.init(identifier: "America/Argentina/Cordoba")
		case "America/Santa_Isabel":			 	self.init(identifier: "America/Tijuana")
		case "America/Shiprock":			 		self.init(identifier: "America/Denver")
		case "America/St_Barthelemy":			 	self.init(identifier: "America/Port_of_Spain")
		case "America/St_Kitts":				 	self.init(identifier: "America/Port_of_Spain")
		case "America/St_Lucia":			 		self.init(identifier: "America/Port_of_Spain")
		case "America/St_Thomas":			 		self.init(identifier: "America/Port_of_Spain")
		case "America/St_Vincent":			 		self.init(identifier: "America/Port_of_Spain")
		case "America/Tortola":			 			self.init(identifier: "America/Port_of_Spain")
		case "America/Virgin":			 			self.init(identifier: "America/Port_of_Spain")
		case "Antarctica/McMurdo":			 		self.init(identifier: "Pacific/Auckland")
		case "Antarctica/South_Pole": 		 		self.init(identifier: "Pacific/Auckland")
		case "Arctic/Longyearbyen":	 				self.init(identifier: "Europe/Oslo")
		case "Asia/Aden":				 			self.init(identifier: "Asia/Riyadh")
		case "Asia/Ashkhabad": 		 				self.init(identifier: "Asia/Ashgabat")
		case "Asia/Bahrain":			 			self.init(identifier: "Asia/Qatar")
		case "Asia/Calcutta":			 			self.init(identifier: "Asia/Kolkata")
		case "Asia/Chongqing":				 		self.init(identifier: "Asia/Shanghai")
		case "Asia/Chungking":			 			self.init(identifier: "Asia/Shanghai")
		case "Asia/Dacca":			 				self.init(identifier: "Asia/Dhaka")
		case "Asia/Harbin":			 				self.init(identifier: "Asia/Shanghai")
		case "Asia/Istanbul":			 			self.init(identifier: "Europe/Istanbul")
		case "Asia/Kashgar":			 			self.init(identifier: "Asia/Urumqi")
		case "Asia/Katmandu":			 			self.init(identifier: "Asia/Kathmandu")
		case "Asia/Kuwait":			 				self.init(identifier: "Asia/Riyadh")
		case "Asia/Macao":			 				self.init(identifier: "Asia/Macau")
		case "Asia/Muscat":			 				self.init(identifier: "Asia/Dubai")
		case "Asia/Phnom_Penh":			 			self.init(identifier: "Asia/Bangkok")
		case "Asia/Rangoon":			 			self.init(identifier: "Asia/Yangon")
		case "Asia/Saigon":			 				self.init(identifier: "Asia/Ho_Chi_Minh")
		case "Asia/Tel_Aviv":			 			self.init(identifier: "Asia/Jerusalem")
		case "Asia/Thimbu":			 				self.init(identifier: "Asia/Thimphu")
		case "Asia/Ujung_Pandang":					self.init(identifier: "Asia/Makassar")
		case "Asia/Ulan_Bator":			 			self.init(identifier: "Asia/Ulaanbaatar")
		case "Asia/Urumqi":			 				self.init(identifier: "Asia/Shanghai")
		case "Asia/Vientiane":			 			self.init(identifier: "Asia/Bangkok")
		case "Atlantic/Faeroe":			 			self.init(identifier: "Atlantic/Faroe")
		case "Atlantic/Jan_Mayen":			 		self.init(identifier: "Europe/Oslo")
		case "Atlantic/St_Helena":				 	self.init(identifier: "Africa/Abidjan")
		case "Australia/ACT":			 			self.init(identifier: "Australia/Sydney")
		case "Australia/Canberra":			 		self.init(identifier: "Australia/Sydney")
		case "Australia/Currie":			 		self.init(identifier: "Australia/Hobart")
		case "Australia/LHI":			 			self.init(identifier: "Australia/Lord_Howe")
		case "Australia/North":			 			self.init(identifier: "Australia/Darwin")
		case "Australia/NSW":			 			self.init(identifier: "Australia/Sydney")
		case "Australia/Queensland":				self.init(identifier: "Australia/Brisbane")
		case "Australia/South":			 			self.init(identifier: "Australia/Adelaide")
		case "Australia/Tasmania":			 		self.init(identifier: "Australia/Hobart")
		case "Australia/Victoria":			 		self.init(identifier: "Australia/Melbourne")
		case "Australia/West":			 			self.init(identifier: "Australia/Perth")
		case "Australia/Yancowinna":			 	self.init(identifier: "Australia/Broken_Hill")
		case "Brazil/Acre":			 				self.init(identifier: "America/Rio_Branco")
		case "Brazil/DeNoronha":			 		self.init(identifier: "America/Noronha")
		case "Brazil/East":			 				self.init(identifier: "America/Sao_Paulo")
		case "Brazil/West":			 				self.init(identifier: "America/Manaus")
		case "Canada/Atlantic":			 			self.init(identifier: "America/Halifax")
		case "Canada/Central":			 			self.init(identifier: "America/Winnipeg")
		case "Canada/Eastern":			 			self.init(identifier: "America/Toronto")
		case "Canada/Mountain":			 			self.init(identifier: "America/Edmonton")
		case "Canada/Newfoundland":			 		self.init(identifier: "America/St_Johns")
		case "Canada/Pacific":			 			self.init(identifier: "America/Vancouver")
		case "Canada/Saskatchewan":			 		self.init(identifier: "America/Regina")
		case "Canada/Yukon":			 			self.init(identifier: "America/Whitehorse")
		case "CET":			 						self.init(identifier: "Europe/Paris")
		case "Chile/Continental":				 	self.init(identifier: "America/Santiago")
		case "Chile/EasterIsland":					self.init(identifier: "Pacific/Easter")
		case "CST6CDT":								self.init(identifier: "America/Chicago")
		case "Cuba":			 					self.init(identifier: "America/Havana")
		case "EET":			 						self.init(identifier: "Europe/Sofia")
		case "Egypt":			 					self.init(identifier: "Africa/Cairo")
		case "Eire":			 					self.init(identifier: "Europe/Dublin")
		case "EST":			 						self.init(identifier: "America/Cancun")
		case "EST5EDT":								self.init(identifier: "America/New_York")
		case "Etc/GMT":								self.init(identifier: "GMT")
		case "Etc/GMT+0":							self.init(identifier: "GMT")
		case "Etc/GMT+1":							self.init(identifier: "GMT+1")
		case "Etc/GMT+10":							self.init(identifier: "GMT+10")
		case "Etc/GMT+11":							self.init(identifier: "GMT+11")
		case "Etc/GMT+12":							self.init(identifier: "GMT+12")
		case "Etc/GMT+2":							self.init(identifier: "GMT+2")
		case "Etc/GMT+3":							self.init(identifier: "GMT+3")
		case "Etc/GMT+4":							self.init(identifier: "GMT+4")
		case "Etc/GMT+5":							self.init(identifier: "GMT+5")
		case "Etc/GMT+6":							self.init(identifier: "GMT+6")
		case "Etc/GMT+7":							self.init(identifier: "GMT+7")
		case "Etc/GMT+8":							self.init(identifier: "GMT+8")
		case "Etc/GMT+9":							self.init(identifier: "GMT+9")
		case "Etc/GMT-0":							self.init(identifier: "GMT")
		case "Etc/GMT-1":							self.init(identifier: "GMT-1")
		case "Etc/GMT-10":							self.init(identifier: "GMT-10")
		case "Etc/GMT-11":							self.init(identifier: "GMT-11")
		case "Etc/GMT-12":							self.init(identifier: "GMT-12")
		case "Etc/GMT-13":							self.init(identifier: "GMT-13")
		case "Etc/GMT-14":							self.init(identifier: "GMT-14")
		case "Etc/GMT-2":							self.init(identifier: "GMT-2")
		case "Etc/GMT-3":							self.init(identifier: "GMT-3")
		case "Etc/GMT-4":							self.init(identifier: "GMT-4")
		case "Etc/GMT-5":							self.init(identifier: "GMT-5")
		case "Etc/GMT-6":							self.init(identifier: "GMT-6")
		case "Etc/GMT-7":							self.init(identifier: "GMT-7")
		case "Etc/GMT-8":							self.init(identifier: "GMT-8")
		case "Etc/GMT-9":							self.init(identifier: "GMT-9")
		case "Etc/GMT0":	 						self.init(identifier: "GMT")
		case "Etc/Greenwich":	 					self.init(identifier: "GMT")
		case "Etc/Universal":	 					self.init(identifier: "UTC")
		case "Etc/Zulu":	 						self.init(identifier: "UTC")
		case "Europe/Belfast":			 			self.init(identifier: "Europe/London")
		case "Europe/Bratislava":					self.init(identifier: "Europe/Prague")
		case "Europe/Busingen":			 			self.init(identifier: "Europe/Zurich")
		case "Europe/Guernsey":			 			self.init(identifier: "Europe/London")
		case "Europe/Isle_of_Man":					self.init(identifier: "Europe/London")
		case "Europe/Jersey":			 			self.init(identifier: "Europe/London")
		case "Europe/Ljubljana":		 			self.init(identifier: "Europe/Belgrade")
		case "Europe/Mariehamn":					self.init(identifier: "Europe/Helsinki")
		case "Europe/Nicosia":			 			self.init(identifier: "Asia/Nicosia")
		case "Europe/Podgorica":					self.init(identifier: "Europe/Belgrade")
		case "Europe/San_Marino":					self.init(identifier: "Europe/Rome")
		case "Europe/Sarajevo":			 			self.init(identifier: "Europe/Belgrade")
		case "Europe/Skopje":			 			self.init(identifier: "Europe/Belgrade")
		case "Europe/Tiraspol":			 			self.init(identifier: "Europe/Chisinau")
		case "Europe/Vaduz":			 			self.init(identifier: "Europe/Zurich")
		case "Europe/Vatican":			 			self.init(identifier: "Europe/Rome")
		case "Europe/Zagreb":			 			self.init(identifier: "Europe/Belgrade")
		case "GB":			 						self.init(identifier: "Europe/London")
		case "GB-Eire":			 					self.init(identifier: "Europe/London")
		case "GMT+0":			 					self.init(identifier: "GMT")
		case "GMT-0":			 					self.init(identifier: "GMT")
		case "GMT0":			 					self.init(identifier: "GMT")
		case "Greenwich":			 				self.init(identifier: "GMT")
		case "Hongkong":				 			self.init(identifier: "Asia/Hong_Kong")
		case "HST":			 						self.init(identifier: "Pacific/Honolulu")
		case "Iceland":			 					self.init(identifier: "Atlantic/Reykjavik")
		case "Indian/Antananarivo":					self.init(identifier: "Africa/Nairobi")
		case "Indian/Comoro":						self.init(identifier: "Africa/Nairobi")
		case "Indian/Mayotte":						self.init(identifier: "Africa/Nairobi")
		case "Iran":								self.init(identifier: "Asia/Tehran")
		case "Israel":								self.init(identifier: "Asia/Jerusalem")
		case "Jamaica":								self.init(identifier: "America/Jamaica")
		case "Japan":								self.init(identifier: "Asia/Tokyo")
		case "Kwajalein":			 				self.init(identifier: "Pacific/Kwajalein")
		case "Libya":			 					self.init(identifier: "Africa/Tripoli")
		case "MET":			 						self.init(identifier: "Europe/Paris")
		case "Mexico/BajaNorte":					self.init(identifier: "America/Tijuana")
		case "Mexico/BajaSur":			 			self.init(identifier: "America/Mazatlan")
		case "Mexico/General":			 			self.init(identifier: "America/Mexico_City")
		case "MST":			 						self.init(identifier: "America/Phoenix")
		case "MST7MDT":			 					self.init(identifier: "America/Denver")
		case "Navajo":			 					self.init(identifier: "America/Denver")
		case "NZ":			 						self.init(identifier: "Pacific/Auckland")
		case "NZ-CHAT":			 					self.init(identifier: "Pacific/Chatham")
		case "Pacific/Johnston":					self.init(identifier: "Pacific/Honolulu")
		case "Pacific/Midway":			 			self.init(identifier: "Pacific/Pago_Pago")
		case "Pacific/Ponape":			 			self.init(identifier: "Pacific/Pohnpei")
		case "Pacific/Saipan":			 			self.init(identifier: "Pacific/Guam")
		case "Pacific/Samoa":			 			self.init(identifier: "Pacific/Pago_Pago")
		case "Pacific/Truk": 		 				self.init(identifier: "Pacific/Chuuk")
		case "Pacific/Yap":			 				self.init(identifier: "Pacific/Chuuk")
		case "Poland":			 					self.init(identifier: "Europe/Warsaw")
		case "Portugal":			 				self.init(identifier: "Europe/Lisbon")
		case "PRC":			 						self.init(identifier: "Asia/Shanghai")
		case "PST8PDT":			 					self.init(identifier: "America/Los_Angeles")
		case "ROC":			 						self.init(identifier: "Asia/Taipei")
		case "ROK":			 						self.init(identifier: "Asia/Seoul")
		case "Singapore":			 				self.init(identifier: "Asia/Singapore")
		case "Turkey":			 					self.init(identifier: "Europe/Istanbul")
		case "UCT":			 						self.init(identifier: "UTC")
		case "Universal":			 				self.init(identifier: "UTC")
		case "US/Alaska":			 				self.init(identifier: "America/Anchorage")
		case "US/Aleutian":			 				self.init(identifier: "America/Adak")
		case "US/Arizona":			 				self.init(identifier: "America/Phoenix")
		case "US/Central":							self.init(identifier: "America/Chicago")
		case "US/East-Indiana":						self.init(identifier: "America/Indiana/Indianapolis")
		case "US/Eastern":			 				self.init(identifier: "America/New_York")
		case "US/Hawaii":			 				self.init(identifier: "Pacific/Honolulu")
		case "US/Indiana-Starke":					self.init(identifier: "America/Indiana/Knox")
		case "US/Michigan":			 				self.init(identifier: "America/Detroit")
		case "US/Mountain":			 				self.init(identifier: "America/Denver")
		case "US/Pacific":			 				self.init(identifier: "America/Los_Angeles")
		case "US/Samoa":			 				self.init(identifier: "Pacific/Pago_Pago")
		case "W-SU":			 					self.init(identifier: "Europe/Moscow")
		case "WET":			 						self.init(identifier: "Europe/Lisbon")
		case "Zulu":			 					self.init(identifier: "UTC")
		default: 									self.init(identifier: iana)
		}
		
		
	}
	
	var iana: String?{
		switch self.identifier{
			case "Africa/Nairobi": 					return "Africa/Addis_Ababa"
			case "Africa/Abidjan": 					return "Africa/Bamako"
			case "Africa/Lagos": 					return "Africa/Bangui"
			case "Africa/Maputo": 					return "Africa/Blantyre"
			case "Africa/Johannesburg": 			return "Africa/Maseru"
			case "America/Port_of_Spain": 			return "America/Anguilla"
			case "America/Argentina/Catamarca": 	return "America/Argentina/ComodRivadavia"
			case "America/Curacao": 				return "America/Aruba"
			case "America/Adak": 					return "America/Atka"
			case "America/Argentina/Buenos_Aires": 	return "America/Buenos_Aires"
			case "America/Panama": 					return "America/Cayman"
			case "America/Atikokan": 				return "America/Coral_Harbour"
			case "America/Argentina/Cordoba": 		return "America/Cordoba"
			case "America/Tijuana": 				return "America/Ensenada"
			case "America/Indiana/Indianapolis": 	return "America/Fort_Wayne"
			case "America/Nuuk": 					return "America/Godthab"
			case "America/Argentina/Jujuy": 		return "America/Jujuy"
			case "America/Indiana/Knox": 			return "America/Knox_IN"
			case "America/Kentucky/Louisville": 	return "America/Louisville"
			case "America/Argentina/Mendoza": 		return "America/Mendoza"
			case "America/Toronto": 				return "America/Montreal"
			case "America/Rio_Branco": 				return "America/Porto_Acre"
			case "Magallanes Region": 				return "America/Punta_Arenas"
			case "America/Denver": 					return "America/Shiprock"
			case "Pacific/Auckland": 				return "Antarctica/McMurdo"
			case "Europe/Oslo": 					return "Arctic/Longyearbyen"
			case "Asia/Riyadh": 					return "Asia/Aden"
			case "Asia/Ashgabat": 					return "Asia/Ashkhabad"
			case "Asia/Qatar": 						return "Asia/Bahrain"
			case "Asia/Kolkata": 					return "Asia/Calcutta"
			case "Asia/Shanghai": 					return "Asia/Chongqing"
			case "Asia/Dhaka": 						return "Asia/Dacca"
			case "Europe/Istanbul": 				return "Asia/Istanbul"
			case "Asia/Urumqi": 					return "Asia/Kashgar"
			case "Asia/Kathmandu": 					return "Asia/Katmandu"
			case "Asia/Macau": 						return "Asia/Macao"
			case "Asia/Dubai": 						return "Asia/Muscat"
			case "Asia/Bangkok": 					return "Asia/Phnom_Penh"
			case "Asia/Yangon": 					return "Asia/Rangoon"
			case "Asia/Ho_Chi_Minh": 				return "Asia/Saigon"
			case "Asia/Jerusalem": 					return "Asia/Tel_Aviv"
			case "Asia/Thimphu": 					return "Asia/Thimbu"
			case "Asia/Makassar": 					return "Asia/Ujung_Pandang"
			case "Asia/Ulaanbaatar": 				return "Asia/Ulan_Bator"
			case "Atlantic/Faroe": 					return "Atlantic/Faeroe"
			case "Australia/Sydney": 				return "Australia/ACT"
			case "Australia/Hobart": 				return "Australia/Currie"
			case "Australia/Lord_Howe": 			return "Australia/LHI"
			case "Australia/Darwin": 				return "Australia/North"
			case "Australia/Brisbane": 				return "Australia/Queensland"
			case "Australia/Adelaide": 				return "Australia/South"
			case "Australia/Melbourne": 			return "Australia/Victoria"
			case "Australia/Perth": 				return "Australia/West"
			case "Australia/Broken_Hill": 			return "Australia/Yancowinna"
			case "America/Noronha": 				return "Brazil/DeNoronha"
			case "America/Sao_Paulo": 				return "Brazil/East"
			case "America/Manaus": 					return "Brazil/West"
			case "America/Halifax": 				return "Canada/Atlantic"
			case "America/Winnipeg": 				return "Canada/Central"
			case "America/Edmonton": 				return "Canada/Mountain"
			case "America/St_Johns": 				return "Canada/Newfoundland"
			case "America/Vancouver": 				return "Canada/Pacific"
			case "America/Regina": 					return "Canada/Saskatchewan"
			case "America/Whitehorse": 				return "Canada/Yukon"
			case "Europe/Paris": 					return "CET"
			case "America/Santiago":	 			return "Chile/Continental"
			case "Pacific/Easter": 					return "Chile/EasterIsland"
			case "America/Chicago": 				return "CST6CDT"
			case "America/Havana": 					return "Cuba"
			case "Europe/Sofia": 					return "EET"
			case "Africa/Cairo": 					return "Egypt"
			case "Europe/Dublin": 					return "Eire"
			case "America/Cancun": 					return "EST"
			case "America/New_York":	 			return "EST5EDT"
			case "GMT": 							return "Etc/GMT"
			case "GMT+1": 							return "Etc/GMT+1"
			case "GMT+10": 							return "Etc/GMT+10"
			case "GMT+11": 							return "Etc/GMT+11"
			case "GMT+12": 							return "Etc/GMT+12"
			case "GMT+2": 							return "Etc/GMT+2"
			case "GMT+3": 							return "Etc/GMT+3"
			case "GMT+4": 							return "Etc/GMT+4"
			case "GMT+5": 							return "Etc/GMT+5"
			case "GMT+6": 							return "Etc/GMT+6"
			case "GMT+7": 							return "Etc/GMT+7"
			case "GMT+8": 							return "Etc/GMT+8"
			case "GMT+9": 							return "Etc/GMT+9"
			case "GMT-1": 							return "Etc/GMT-1"
			case "GMT-10": 							return "Etc/GMT-10"
			case "GMT-11": 							return "Etc/GMT-11"
			case "GMT-12": 							return "Etc/GMT-12"
			case "GMT-13": 							return "Etc/GMT-13"
			case "GMT-14": 							return "Etc/GMT-14"
			case "GMT-2": 							return "Etc/GMT-2"
			case "GMT-3": 							return "Etc/GMT-3"
			case "GMT-4": 							return "Etc/GMT-4"
			case "GMT-5": 							return "Etc/GMT-5"
			case "GMT-6": 							return "Etc/GMT-6"
			case "GMT-7": 							return "Etc/GMT-7"
			case "GMT-8": 							return "Etc/GMT-8"
			case "GMT-9": 							return "Etc/GMT-9"
			case "UTC": 							return "Etc/Universal"
			case "Europe/London": 					return "Europe/Belfast"
			case "Europe/Prague": 					return "Europe/Bratislava"
			case "Europe/Zurich": 					return "Europe/Busingen"
			case "Europe/Belgrade": 				return "Europe/Ljubljana"
			case "Europe/Helsinki": 				return "Europe/Mariehamn"
			case "Asia/Nicosia": 					return "Europe/Nicosia"
			case "Europe/Rome": 					return "Europe/San_Marino"
			case "Europe/Chisinau": 				return "Europe/Tiraspol"
			case "Asia/Hong_Kong": 					return "Hongkong"
			case "Pacific/Honolulu": 				return "HST"
			case "Atlantic/Reykjavik": 				return "Iceland"
			case "Asia/Tehran": 					return "Iran"
			case "America/Jamaica": 				return "Jamaica"
			case "Asia/Tokyo": 						return "Japan"
			case "Pacific/Kwajalein": 				return "Kwajalein"
			case "Africa/Tripoli": 					return "Libya"
			case "America/Mazatlan": 				return "Mexico/BajaSur"
			case "America/Mexico_City": 			return "Mexico/General"
			case "America/Phoenix": 				return "MST"
			case "Pacific/Chatham": 				return "NZ-CHAT"
			case "Pacific/Pago_Pago": 				return "Pacific/Midway"
			case "Pacific/Pohnpei": 				return "Pacific/Ponape"
			case "Pacific/Guam": 					return "Pacific/Saipan"
			case "Pacific/Chuuk": 					return "Pacific/Truk"
			case "Europe/Warsaw": 					return "Poland"
			case "Europe/Lisbon": 					return "Portugal"
			case "America/Los_Angeles": 			return "PST8PDT"
			case "Asia/Taipei": 					return "ROC"
			case "Asia/Seoul":						return "ROK"
			case "Asia/Singapore": 					return "Singapore"
			case "America/Anchorage": 				return "US/Alaska"
			case "America/Detroit": 				return "US/Michigan"
			case "Europe/Moscow": 					return "W-SU"
		default:									return "UTC"
		}
	}
}
