//
//  RequestType.swift
//  tws-api-swift
//
//  Created by Sten Soosaar on 05.02.2026.
//


public enum RequestType: Int32, Sendable{
	case REQ_MKT_DATA = 1
	case CANCEL_MKT_DATA = 2
	case PLACE_ORDER = 3
	case CANCEL_ORDER = 4
	case REQ_OPEN_ORDERS = 5
	case REQ_ACCT_DATA = 6
	case REQ_EXECUTIONS = 7
	case REQ_IDS = 8
	case REQ_CONTRACT_DATA = 9
	case REQ_MKT_DEPTH = 10
	case CANCEL_MKT_DEPTH = 11
	case REQ_NEWS_BULLETINS = 12
	case CANCEL_NEWS_BULLETINS = 13
	case SET_SERVER_LOGLEVEL = 14
	case REQ_AUTO_OPEN_ORDERS = 15
	case REQ_ALL_OPEN_ORDERS = 16
	case REQ_MANAGED_ACCTS = 17
	case REQ_FA = 18
	case REPLACE_FA = 19
	case REQ_HISTORICAL_DATA = 20
	case EXERCISE_OPTIONS = 21
	case REQ_SCANNER_SUBSCRIPTION = 22
	case CANCEL_SCANNER_SUBSCRIPTION = 23
	case REQ_SCANNER_PARAMETERS = 24
	case CANCEL_HISTORICAL_DATA = 25
	case REQ_CURRENT_TIME = 49
	case REQ_REAL_TIME_BARS = 50
	case CANCEL_REAL_TIME_BARS = 51
	case REQ_FUNDAMENTAL_DATA = 52
	case CANCEL_FUNDAMENTAL_DATA = 53
	case REQ_CALC_IMPLIED_VOLAT = 54
	case REQ_CALC_OPTION_PRICE = 55
	case CANCEL_CALC_IMPLIED_VOLAT = 56
	case CANCEL_CALC_OPTION_PRICE = 57
	case REQ_GLOBAL_CANCEL = 58
	case REQ_MARKET_DATA_TYPE = 59
	case REQ_POSITIONS = 61
	case REQ_ACCOUNT_SUMMARY = 62
	case CANCEL_ACCOUNT_SUMMARY = 63
	case CANCEL_POSITIONS = 64
	case VERIFY_REQUEST = 65
	case VERIFY_MESSAGE = 66
	case QUERY_DISPLAY_GROUPS = 67
	case SUBSCRIBE_TO_GROUP_EVENTS = 68
	case UPDATE_DISPLAY_GROUP = 69
	case UNSUBSCRIBE_FROM_GROUP_EVENTS = 70
	case START_API = 71
	case VERIFY_AND_AUTH_REQUEST = 72
	case VERIFY_AND_AUTH_MESSAGE = 73
	case REQ_POSITIONS_MULTI = 74
	case CANCEL_POSITIONS_MULTI = 75
	case REQ_ACCOUNT_UPDATES_MULTI = 76
	case CANCEL_ACCOUNT_UPDATES_MULTI = 77
	case REQ_SEC_DEF_OPT_PARAMS = 78
	case REQ_SOFT_DOLLAR_TIERS = 79
	case REQ_FAMILY_CODES = 80
	case REQ_MATCHING_SYMBOLS = 81
	case REQ_MKT_DEPTH_EXCHANGES = 82
	case REQ_SMART_COMPONENTS = 83
	case REQ_NEWS_ARTICLE = 84
	case REQ_NEWS_PROVIDERS = 85
	case REQ_HISTORICAL_NEWS = 86
	case REQ_HEAD_TIMESTAMP = 87
	case REQ_HISTOGRAM_DATA = 88
	case CANCEL_HISTOGRAM_DATA = 89
	case CANCEL_HEAD_TIMESTAMP = 90
	case REQ_MARKET_RULE = 91
	case REQ_PNL = 92
	case CANCEL_PNL = 93
	case REQ_PNL_SINGLE = 94
	case CANCEL_PNL_SINGLE = 95
	case REQ_HISTORICAL_TICKS = 96
	case REQ_TICK_BY_TICK_DATA = 97
	case CANCEL_TICK_BY_TICK_DATA = 98
	case REQ_COMPLETED_ORDERS = 99
	case REQ_WSH_META_DATA = 100
	case CANCEL_WSH_META_DATA = 101
	case REQ_WSH_EVENT_DATA = 102
	case CANCEL_WSH_EVENT_DATA = 103
	case REQ_USER_INFO = 104
	case REQ_CURRENT_TIME_IN_MILLIS = 105
	case CANCEL_CONTRACT_DATA = 106
	case CANCEL_HISTORICAL_TICKS = 107
	case REQ_CONFIG = 108
	case UPDATE_CONFIG = 109
}


public extension RequestType {
	
	var protoRawValue: Int32 {
		return self.rawValue + 200
	}
	
}
