//
//  ServerVersion.swift
//  tws-api-swift
//
//  Created by Sten Soosaar on 07.06.2026.
//


//
//  ServerVersion.swift
//  tws-api-swift
//
//  Created by Sten Soosaar on 05.02.2026.
//



public struct ServerVersion: Sendable, Codable{
	
	public let rawValue: Int
	
	init(rawValue: Int) { self.rawValue = rawValue }
	
	public static let realTimeBars 						= ServerVersion(rawValue: 34)
	public static let scaleOrders 						= ServerVersion(rawValue: 35)
	public static let snapshotMktData 					= ServerVersion(rawValue: 35)
	public static let sshortComboLegs 					= ServerVersion(rawValue: 35)
	public static let whatIfOrders 						= ServerVersion(rawValue: 36)
	public static let contractConid 					= ServerVersion(rawValue: 37)
	public static let ptaOrders 						= ServerVersion(rawValue: 39)
	public static let fundamentalData 					= ServerVersion(rawValue: 40)
	public static let deltaNeutral 						= ServerVersion(rawValue: 40)
	public static let contractDataChain 				= ServerVersion(rawValue: 40)
	public static let scaleOrders2 						= ServerVersion(rawValue: 40)
	public static let algoOrders 						= ServerVersion(rawValue: 41)
	public static let executionDataChain 				= ServerVersion(rawValue: 42)
	public static let notHeld 							= ServerVersion(rawValue: 44)
	public static let secIdType 						= ServerVersion(rawValue: 45)
	public static let placeOrderConid 					= ServerVersion(rawValue: 46)
	public static let reqMktDataConid 					= ServerVersion(rawValue: 47)
	public static let reqCalcImpliedVolat	 			= ServerVersion(rawValue: 49)
	public static let reqCalcOptionPrice 				= ServerVersion(rawValue: 50)
	public static let sshortxOld 						= ServerVersion(rawValue: 51)
	public static let sshortx 							= ServerVersion(rawValue: 52)
	public static let reqGlobalCancel 					= ServerVersion(rawValue: 53)
	public static let hedgeOrders 						= ServerVersion(rawValue: 54)
	public static let reqMarketDataType 				= ServerVersion(rawValue: 55)
	public static let optOutSmartRouting 				= ServerVersion(rawValue: 56)
	public static let smartComboRoutingParams 			= ServerVersion(rawValue: 57)
	public static let deltaNeutralConid 				= ServerVersion(rawValue: 58)
	public static let scaleOrders3 						= ServerVersion(rawValue: 60)
	public static let orderComboLegsPrice 				= ServerVersion(rawValue: 61)
	public static let trailingPercent 					= ServerVersion(rawValue: 62)
	public static let deltaNeutralOpenClose			 	= ServerVersion(rawValue: 66)
	public static let positions 						= ServerVersion(rawValue: 67)
	public static let accountSummary					= ServerVersion(rawValue: 67)
	public static let tradingClass 						= ServerVersion(rawValue: 68)
	public static let scaleTable 						= ServerVersion(rawValue: 69)
	public static let linking 							= ServerVersion(rawValue: 70)
	public static let algoId 							= ServerVersion(rawValue: 71)
	public static let optionalCapabilities 				= ServerVersion(rawValue: 72)
	public static let orderSolicited 					= ServerVersion(rawValue: 73)
	public static let linkingAuth 						= ServerVersion(rawValue: 74)
	public static let primaryExch 						= ServerVersion(rawValue: 75)
	public static let randomizeSizeAndPrice 			= ServerVersion(rawValue: 76)
	public static let fractionalPositions 				= ServerVersion(rawValue: 101)
	public static let peggedToBenchmark 				= ServerVersion(rawValue: 102)
	public static let modelsSupport 					= ServerVersion(rawValue: 103)
	public static let secDefOptParamsReq				= ServerVersion(rawValue: 104)
	public static let extOperator 						= ServerVersion(rawValue: 105)
	public static let softDollarTier 					= ServerVersion(rawValue: 106)
	public static let reqFamilyCodes 					= ServerVersion(rawValue: 107)
	public static let reqMatchingSymbols 				= ServerVersion(rawValue: 108)
	public static let pastLimit 						= ServerVersion(rawValue: 109)
	public static let mdSizeMultiplier 					= ServerVersion(rawValue: 110)
	public static let cashQty 							= ServerVersion(rawValue: 111)
	public static let reqMktDepthExchanges 				= ServerVersion(rawValue: 112)
	public static let tickNews 							= ServerVersion(rawValue: 113)
	public static let reqSmartComponents 				= ServerVersion(rawValue: 114)
	public static let reqNewsProviders 					= ServerVersion(rawValue: 115)
	public static let reqNewsArticle 					= ServerVersion(rawValue: 116)
	public static let reqHistoricalNews 				= ServerVersion(rawValue: 117)
	public static let reqHeadTimestamp 					= ServerVersion(rawValue: 118)
	public static let reqHistogram 						= ServerVersion(rawValue: 119)
	public static let serviceDataType 					= ServerVersion(rawValue: 120)
	public static let aggGroup	 						= ServerVersion(rawValue: 121)
	public static let underlyingInfo 					= ServerVersion(rawValue: 122)
	public static let cancelHeadtimestamp 				= ServerVersion(rawValue: 123)
	public static let syntRealtimeBars 					= ServerVersion(rawValue: 124)
	public static let cfdReroute 						= ServerVersion(rawValue: 125)
	public static let marketRules 						= ServerVersion(rawValue: 126)
	public static let accountPNL 						= ServerVersion(rawValue: 127)
	public static let newsQueryOrigins 					= ServerVersion(rawValue: 128)
	public static let unrealizedPnl 					= ServerVersion(rawValue: 129)
	public static let historicalTicks 					= ServerVersion(rawValue: 130)
	public static let marketCapPrice 					= ServerVersion(rawValue: 131)
	public static let preOpenBidAsk 					= ServerVersion(rawValue: 132)
	public static let realExpirationDate 				= ServerVersion(rawValue: 134)
	public static let realizedPnl 						= ServerVersion(rawValue: 135)
	public static let lastLiquidity 					= ServerVersion(rawValue: 136)
	public static let tickByTick 						= ServerVersion(rawValue: 137)
	public static let decisionMaker 					= ServerVersion(rawValue: 138)
	public static let mifidExecution 					= ServerVersion(rawValue: 139)
	public static let tickByTickIgnoreSize 				= ServerVersion(rawValue: 140)
	public static let autoPriceForHedge 				= ServerVersion(rawValue: 141)
	public static let whatIfExtFields 					= ServerVersion(rawValue: 142)
	public static let scannerGenericOpts 				= ServerVersion(rawValue: 143)
	public static let apiBindOrder 						= ServerVersion(rawValue: 144)
	public static let orderContainer 					= ServerVersion(rawValue: 145)
	public static let smartDepth 						= ServerVersion(rawValue: 146)
	public static let removeNullAllCasting 				= ServerVersion(rawValue: 147)
	public static let dPegOrders						= ServerVersion(rawValue: 148)
	public static let mktDepthPrimExchange 				= ServerVersion(rawValue: 149)
	public static let completedOrders 					= ServerVersion(rawValue: 150)
	public static let priceMgmtAlgo 					= ServerVersion(rawValue: 151)
	public static let stockType 						= ServerVersion(rawValue: 152)
	public static let encodeMsgAscii7 					= ServerVersion(rawValue: 153)
	public static let sendAllFamilyCodes 				= ServerVersion(rawValue: 154)
	public static let noDefaultOpenClose 				= ServerVersion(rawValue: 155)
	public static let priceBasedVolatility 				= ServerVersion(rawValue: 156)
	public static let replaceFAEnd 						= ServerVersion(rawValue: 157)
	public static let duration	 						= ServerVersion(rawValue: 158)
	public static let marketDataInShares				= ServerVersion(rawValue: 159)
	public static let postToAts 						= ServerVersion(rawValue: 160)
	public static let wshCalendar 						= ServerVersion(rawValue: 161)
	public static let autoCancelParent 					= ServerVersion(rawValue: 162)
	public static let fractionalSizeSupport 			= ServerVersion(rawValue: 163)
	public static let sizeRules 						= ServerVersion(rawValue: 164)
	public static let historicalSchedule				= ServerVersion(rawValue: 165)
	public static let advancedOrderReject 				= ServerVersion(rawValue: 166)
	public static let userInfo 							= ServerVersion(rawValue: 167)
	public static let cryptoAggregatedTrades			= ServerVersion(rawValue: 168)
	public static let manualOrderTime 					= ServerVersion(rawValue: 169)
	public static let pegbestPegmidOffsets 				= ServerVersion(rawValue: 170)
	public static let wshEventDataFilters 				= ServerVersion(rawValue: 171)
	public static let ipoPrices 						= ServerVersion(rawValue: 172)
	public static let wshEventDataFiltersDate 			= ServerVersion(rawValue: 173)
	public static let instrumentTimezone 				= ServerVersion(rawValue: 174)
	public static let hmdsMarketDataInShares 			= ServerVersion(rawValue: 175)
	public static let bondIssuerid 						= ServerVersion(rawValue: 176)
	public static let FAProfileDesupport 				= ServerVersion(rawValue: 177)
	public static let pendingPriceRevision 				= ServerVersion(rawValue: 178)
	public static let fundDataFields 					= ServerVersion(rawValue: 179)
	public static let manualOrderTimeExerciseOptions	= ServerVersion(rawValue: 180)
	public static let openOrderAdStrategy 				= ServerVersion(rawValue: 181)
	public static let lastTradeDate 					= ServerVersion(rawValue: 182)
	public static let customerAccount 					= ServerVersion(rawValue: 183)
	public static let professionalCustomer 				= ServerVersion(rawValue: 184)
	public static let bondAccruedInterest 				= ServerVersion(rawValue: 185)
	public static let ineligibilityReasons 				= ServerVersion(rawValue: 186)
	public static let rfqFields 						= ServerVersion(rawValue: 187)
	public static let bondTradingHours		 			= ServerVersion(rawValue: 188)
	public static let includeOvernight 					= ServerVersion(rawValue: 189)
	public static let undoRfqFields 					= ServerVersion(rawValue: 190)
	public static let permIdAsLong 						= ServerVersion(rawValue: 191)
	public static let cmeTaggingFields 					= ServerVersion(rawValue: 192)
	public static let cmeTaggingFieldsInOpenOrder 		= ServerVersion(rawValue: 193)
	public static let errorTime 						= ServerVersion(rawValue: 194)
	public static let fullOrderPreviewFields 			= ServerVersion(rawValue: 195)
	public static let historicalDataEnd 				= ServerVersion(rawValue: 196)
	public static let currenTimeInMilliseconds 			= ServerVersion(rawValue: 197)
	public static let submitter 						= ServerVersion(rawValue: 198)
	public static let imbalanceOnly 					= ServerVersion(rawValue: 199)
	public static let parametrizedDaysOfExecutions 		= ServerVersion(rawValue: 200)
	public static let protobuf 							= ServerVersion(rawValue: 201)
	public static let zeroStrike 						= ServerVersion(rawValue: 202)
	public static let protobufPlaceOrder 				= ServerVersion(rawValue: 203)
	public static let protobufCompletedOrders 			= ServerVersion(rawValue: 204)
	public static let protobufContractData 				= ServerVersion(rawValue: 205)
	public static let protobufMarketData 				= ServerVersion(rawValue: 206)
	public static let protobufAccountPositions 			= ServerVersion(rawValue: 207)
	public static let protobufHistoricalData 			= ServerVersion(rawValue: 208)
	public static let protobufNewsData 					= ServerVersion(rawValue: 209)
	public static let protobufScanData 					= ServerVersion(rawValue: 210)
	public static let protobufRestMessages1 			= ServerVersion(rawValue: 211)
	public static let protobufRestMessages2 			= ServerVersion(rawValue: 212)
	public static let protobufRestMessages3				= ServerVersion(rawValue: 213)
	public static let addZSuffixToUTCDateTime 			= ServerVersion(rawValue: 214)
	public static let cancelContractData 				= ServerVersion(rawValue: 215)
	public static let additionalOrderParamters1 		= ServerVersion(rawValue: 216)
	public static let additionalOrderParamters2 		= ServerVersion(rawValue: 217)
	public static let attachedOrders 					= ServerVersion(rawValue: 218)
	public static let config 							= ServerVersion(rawValue: 219)
	public static let marketDataVolumeAsShares 			= ServerVersion(rawValue: 220)
	public static let updateConfig 						= ServerVersion(rawValue: 221)
	public static let fractionalLastSize 				= ServerVersion(rawValue: 222)
	public static let hedgeMaxSize 						= ServerVersion(rawValue: 223)
	public static let usePrecisionFromSecDef			= ServerVersion(rawValue: 224)
	public static let OddLotBidAskQuotes 				= ServerVersion(rawValue: 225)
}


extension ServerVersion: Comparable, Equatable {
	
	public static func < (lhs: ServerVersion, rhs: ServerVersion) -> Bool {
		return lhs.rawValue < rhs.rawValue
	}
	
	public static func == (lhs: ServerVersion, rhs: ServerVersion) -> Bool {
		return lhs.rawValue == rhs.rawValue
	}

}

