// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ApiPrecautionsConfig.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBApiPrecautionsConfig: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var bypassOrderPrecautions: Bool {
    get {_bypassOrderPrecautions ?? false}
    set {_bypassOrderPrecautions = newValue}
  }
  /// Returns true if `bypassOrderPrecautions` has been explicitly set.
  public var hasBypassOrderPrecautions: Bool {self._bypassOrderPrecautions != nil}
  /// Clears the value of `bypassOrderPrecautions`. Subsequent reads from it will return its default value.
  public mutating func clearBypassOrderPrecautions() {self._bypassOrderPrecautions = nil}

  public var bypassBondWarning: Bool {
    get {_bypassBondWarning ?? false}
    set {_bypassBondWarning = newValue}
  }
  /// Returns true if `bypassBondWarning` has been explicitly set.
  public var hasBypassBondWarning: Bool {self._bypassBondWarning != nil}
  /// Clears the value of `bypassBondWarning`. Subsequent reads from it will return its default value.
  public mutating func clearBypassBondWarning() {self._bypassBondWarning = nil}

  public var bypassNegativeYieldConfirmation: Bool {
    get {_bypassNegativeYieldConfirmation ?? false}
    set {_bypassNegativeYieldConfirmation = newValue}
  }
  /// Returns true if `bypassNegativeYieldConfirmation` has been explicitly set.
  public var hasBypassNegativeYieldConfirmation: Bool {self._bypassNegativeYieldConfirmation != nil}
  /// Clears the value of `bypassNegativeYieldConfirmation`. Subsequent reads from it will return its default value.
  public mutating func clearBypassNegativeYieldConfirmation() {self._bypassNegativeYieldConfirmation = nil}

  public var bypassCalledBondWarning: Bool {
    get {_bypassCalledBondWarning ?? false}
    set {_bypassCalledBondWarning = newValue}
  }
  /// Returns true if `bypassCalledBondWarning` has been explicitly set.
  public var hasBypassCalledBondWarning: Bool {self._bypassCalledBondWarning != nil}
  /// Clears the value of `bypassCalledBondWarning`. Subsequent reads from it will return its default value.
  public mutating func clearBypassCalledBondWarning() {self._bypassCalledBondWarning = nil}

  public var bypassSameActionPairTradeWarning: Bool {
    get {_bypassSameActionPairTradeWarning ?? false}
    set {_bypassSameActionPairTradeWarning = newValue}
  }
  /// Returns true if `bypassSameActionPairTradeWarning` has been explicitly set.
  public var hasBypassSameActionPairTradeWarning: Bool {self._bypassSameActionPairTradeWarning != nil}
  /// Clears the value of `bypassSameActionPairTradeWarning`. Subsequent reads from it will return its default value.
  public mutating func clearBypassSameActionPairTradeWarning() {self._bypassSameActionPairTradeWarning = nil}

  public var bypassFlaggedAccountsWarning: Bool {
    get {_bypassFlaggedAccountsWarning ?? false}
    set {_bypassFlaggedAccountsWarning = newValue}
  }
  /// Returns true if `bypassFlaggedAccountsWarning` has been explicitly set.
  public var hasBypassFlaggedAccountsWarning: Bool {self._bypassFlaggedAccountsWarning != nil}
  /// Clears the value of `bypassFlaggedAccountsWarning`. Subsequent reads from it will return its default value.
  public mutating func clearBypassFlaggedAccountsWarning() {self._bypassFlaggedAccountsWarning = nil}

  public var bypassPriceBasedVolatilityWarning: Bool {
    get {_bypassPriceBasedVolatilityWarning ?? false}
    set {_bypassPriceBasedVolatilityWarning = newValue}
  }
  /// Returns true if `bypassPriceBasedVolatilityWarning` has been explicitly set.
  public var hasBypassPriceBasedVolatilityWarning: Bool {self._bypassPriceBasedVolatilityWarning != nil}
  /// Clears the value of `bypassPriceBasedVolatilityWarning`. Subsequent reads from it will return its default value.
  public mutating func clearBypassPriceBasedVolatilityWarning() {self._bypassPriceBasedVolatilityWarning = nil}

  public var bypassRedirectOrderWarning: Bool {
    get {_bypassRedirectOrderWarning ?? false}
    set {_bypassRedirectOrderWarning = newValue}
  }
  /// Returns true if `bypassRedirectOrderWarning` has been explicitly set.
  public var hasBypassRedirectOrderWarning: Bool {self._bypassRedirectOrderWarning != nil}
  /// Clears the value of `bypassRedirectOrderWarning`. Subsequent reads from it will return its default value.
  public mutating func clearBypassRedirectOrderWarning() {self._bypassRedirectOrderWarning = nil}

  public var bypassNoOverfillProtection: Bool {
    get {_bypassNoOverfillProtection ?? false}
    set {_bypassNoOverfillProtection = newValue}
  }
  /// Returns true if `bypassNoOverfillProtection` has been explicitly set.
  public var hasBypassNoOverfillProtection: Bool {self._bypassNoOverfillProtection != nil}
  /// Clears the value of `bypassNoOverfillProtection`. Subsequent reads from it will return its default value.
  public mutating func clearBypassNoOverfillProtection() {self._bypassNoOverfillProtection = nil}

  public var bypassRouteMarketableToBbo: Bool {
    get {_bypassRouteMarketableToBbo ?? false}
    set {_bypassRouteMarketableToBbo = newValue}
  }
  /// Returns true if `bypassRouteMarketableToBbo` has been explicitly set.
  public var hasBypassRouteMarketableToBbo: Bool {self._bypassRouteMarketableToBbo != nil}
  /// Clears the value of `bypassRouteMarketableToBbo`. Subsequent reads from it will return its default value.
  public mutating func clearBypassRouteMarketableToBbo() {self._bypassRouteMarketableToBbo = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _bypassOrderPrecautions: Bool? = nil
  fileprivate var _bypassBondWarning: Bool? = nil
  fileprivate var _bypassNegativeYieldConfirmation: Bool? = nil
  fileprivate var _bypassCalledBondWarning: Bool? = nil
  fileprivate var _bypassSameActionPairTradeWarning: Bool? = nil
  fileprivate var _bypassFlaggedAccountsWarning: Bool? = nil
  fileprivate var _bypassPriceBasedVolatilityWarning: Bool? = nil
  fileprivate var _bypassRedirectOrderWarning: Bool? = nil
  fileprivate var _bypassNoOverfillProtection: Bool? = nil
  fileprivate var _bypassRouteMarketableToBbo: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBApiPrecautionsConfig: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ApiPrecautionsConfig"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}bypassOrderPrecautions\0\u{1}bypassBondWarning\0\u{1}bypassNegativeYieldConfirmation\0\u{1}bypassCalledBondWarning\0\u{1}bypassSameActionPairTradeWarning\0\u{1}bypassFlaggedAccountsWarning\0\u{1}bypassPriceBasedVolatilityWarning\0\u{1}bypassRedirectOrderWarning\0\u{1}bypassNoOverfillProtection\0\u{1}bypassRouteMarketableToBBO\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._bypassOrderPrecautions) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._bypassBondWarning) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._bypassNegativeYieldConfirmation) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._bypassCalledBondWarning) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._bypassSameActionPairTradeWarning) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._bypassFlaggedAccountsWarning) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._bypassPriceBasedVolatilityWarning) }()
      case 8: try { try decoder.decodeSingularBoolField(value: &self._bypassRedirectOrderWarning) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._bypassNoOverfillProtection) }()
      case 10: try { try decoder.decodeSingularBoolField(value: &self._bypassRouteMarketableToBbo) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._bypassOrderPrecautions {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._bypassBondWarning {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._bypassNegativeYieldConfirmation {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._bypassCalledBondWarning {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._bypassSameActionPairTradeWarning {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._bypassFlaggedAccountsWarning {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._bypassPriceBasedVolatilityWarning {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._bypassRedirectOrderWarning {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._bypassNoOverfillProtection {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._bypassRouteMarketableToBbo {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBApiPrecautionsConfig, rhs: IBPBApiPrecautionsConfig) -> Bool {
    if lhs._bypassOrderPrecautions != rhs._bypassOrderPrecautions {return false}
    if lhs._bypassBondWarning != rhs._bypassBondWarning {return false}
    if lhs._bypassNegativeYieldConfirmation != rhs._bypassNegativeYieldConfirmation {return false}
    if lhs._bypassCalledBondWarning != rhs._bypassCalledBondWarning {return false}
    if lhs._bypassSameActionPairTradeWarning != rhs._bypassSameActionPairTradeWarning {return false}
    if lhs._bypassFlaggedAccountsWarning != rhs._bypassFlaggedAccountsWarning {return false}
    if lhs._bypassPriceBasedVolatilityWarning != rhs._bypassPriceBasedVolatilityWarning {return false}
    if lhs._bypassRedirectOrderWarning != rhs._bypassRedirectOrderWarning {return false}
    if lhs._bypassNoOverfillProtection != rhs._bypassNoOverfillProtection {return false}
    if lhs._bypassRouteMarketableToBbo != rhs._bypassRouteMarketableToBbo {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
