// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ComboLeg.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBComboLeg: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var conID: Int32 {
    get {_conID ?? 0}
    set {_conID = newValue}
  }
  /// Returns true if `conID` has been explicitly set.
  public var hasConID: Bool {self._conID != nil}
  /// Clears the value of `conID`. Subsequent reads from it will return its default value.
  public mutating func clearConID() {self._conID = nil}

  public var ratio: Int32 {
    get {_ratio ?? 0}
    set {_ratio = newValue}
  }
  /// Returns true if `ratio` has been explicitly set.
  public var hasRatio: Bool {self._ratio != nil}
  /// Clears the value of `ratio`. Subsequent reads from it will return its default value.
  public mutating func clearRatio() {self._ratio = nil}

  public var action: String {
    get {_action ?? String()}
    set {_action = newValue}
  }
  /// Returns true if `action` has been explicitly set.
  public var hasAction: Bool {self._action != nil}
  /// Clears the value of `action`. Subsequent reads from it will return its default value.
  public mutating func clearAction() {self._action = nil}

  public var exchange: String {
    get {_exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  public var openClose: Int32 {
    get {_openClose ?? 0}
    set {_openClose = newValue}
  }
  /// Returns true if `openClose` has been explicitly set.
  public var hasOpenClose: Bool {self._openClose != nil}
  /// Clears the value of `openClose`. Subsequent reads from it will return its default value.
  public mutating func clearOpenClose() {self._openClose = nil}

  public var shortSalesSlot: Int32 {
    get {_shortSalesSlot ?? 0}
    set {_shortSalesSlot = newValue}
  }
  /// Returns true if `shortSalesSlot` has been explicitly set.
  public var hasShortSalesSlot: Bool {self._shortSalesSlot != nil}
  /// Clears the value of `shortSalesSlot`. Subsequent reads from it will return its default value.
  public mutating func clearShortSalesSlot() {self._shortSalesSlot = nil}

  public var designatedLocation: String {
    get {_designatedLocation ?? String()}
    set {_designatedLocation = newValue}
  }
  /// Returns true if `designatedLocation` has been explicitly set.
  public var hasDesignatedLocation: Bool {self._designatedLocation != nil}
  /// Clears the value of `designatedLocation`. Subsequent reads from it will return its default value.
  public mutating func clearDesignatedLocation() {self._designatedLocation = nil}

  public var exemptCode: Int32 {
    get {_exemptCode ?? 0}
    set {_exemptCode = newValue}
  }
  /// Returns true if `exemptCode` has been explicitly set.
  public var hasExemptCode: Bool {self._exemptCode != nil}
  /// Clears the value of `exemptCode`. Subsequent reads from it will return its default value.
  public mutating func clearExemptCode() {self._exemptCode = nil}

  public var perLegPrice: Double {
    get {_perLegPrice ?? 0}
    set {_perLegPrice = newValue}
  }
  /// Returns true if `perLegPrice` has been explicitly set.
  public var hasPerLegPrice: Bool {self._perLegPrice != nil}
  /// Clears the value of `perLegPrice`. Subsequent reads from it will return its default value.
  public mutating func clearPerLegPrice() {self._perLegPrice = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _conID: Int32? = nil
  fileprivate var _ratio: Int32? = nil
  fileprivate var _action: String? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _openClose: Int32? = nil
  fileprivate var _shortSalesSlot: Int32? = nil
  fileprivate var _designatedLocation: String? = nil
  fileprivate var _exemptCode: Int32? = nil
  fileprivate var _perLegPrice: Double? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBComboLeg: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ComboLeg"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}conId\0\u{1}ratio\0\u{1}action\0\u{1}exchange\0\u{1}openClose\0\u{1}shortSalesSlot\0\u{1}designatedLocation\0\u{1}exemptCode\0\u{1}perLegPrice\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._conID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._ratio) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._action) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._exchange) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._openClose) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self._shortSalesSlot) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._designatedLocation) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._exemptCode) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self._perLegPrice) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._conID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._ratio {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._action {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._openClose {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._shortSalesSlot {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._designatedLocation {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._exemptCode {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._perLegPrice {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBComboLeg, rhs: IBPBComboLeg) -> Bool {
    if lhs._conID != rhs._conID {return false}
    if lhs._ratio != rhs._ratio {return false}
    if lhs._action != rhs._action {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._openClose != rhs._openClose {return false}
    if lhs._shortSalesSlot != rhs._shortSalesSlot {return false}
    if lhs._designatedLocation != rhs._designatedLocation {return false}
    if lhs._exemptCode != rhs._exemptCode {return false}
    if lhs._perLegPrice != rhs._perLegPrice {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
