// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: CommissionAndFeesReport.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBCommissionAndFeesReport: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var execID: String {
    get {_execID ?? String()}
    set {_execID = newValue}
  }
  /// Returns true if `execID` has been explicitly set.
  public var hasExecID: Bool {self._execID != nil}
  /// Clears the value of `execID`. Subsequent reads from it will return its default value.
  public mutating func clearExecID() {self._execID = nil}

  public var commissionAndFees: Double {
    get {_commissionAndFees ?? 0}
    set {_commissionAndFees = newValue}
  }
  /// Returns true if `commissionAndFees` has been explicitly set.
  public var hasCommissionAndFees: Bool {self._commissionAndFees != nil}
  /// Clears the value of `commissionAndFees`. Subsequent reads from it will return its default value.
  public mutating func clearCommissionAndFees() {self._commissionAndFees = nil}

  public var currency: String {
    get {_currency ?? String()}
    set {_currency = newValue}
  }
  /// Returns true if `currency` has been explicitly set.
  public var hasCurrency: Bool {self._currency != nil}
  /// Clears the value of `currency`. Subsequent reads from it will return its default value.
  public mutating func clearCurrency() {self._currency = nil}

  public var realizedPnl: Double {
    get {_realizedPnl ?? 0}
    set {_realizedPnl = newValue}
  }
  /// Returns true if `realizedPnl` has been explicitly set.
  public var hasRealizedPnl: Bool {self._realizedPnl != nil}
  /// Clears the value of `realizedPnl`. Subsequent reads from it will return its default value.
  public mutating func clearRealizedPnl() {self._realizedPnl = nil}

  public var bondYield: Double {
    get {_bondYield ?? 0}
    set {_bondYield = newValue}
  }
  /// Returns true if `bondYield` has been explicitly set.
  public var hasBondYield: Bool {self._bondYield != nil}
  /// Clears the value of `bondYield`. Subsequent reads from it will return its default value.
  public mutating func clearBondYield() {self._bondYield = nil}

  public var yieldRedemptionDate: String {
    get {_yieldRedemptionDate ?? String()}
    set {_yieldRedemptionDate = newValue}
  }
  /// Returns true if `yieldRedemptionDate` has been explicitly set.
  public var hasYieldRedemptionDate: Bool {self._yieldRedemptionDate != nil}
  /// Clears the value of `yieldRedemptionDate`. Subsequent reads from it will return its default value.
  public mutating func clearYieldRedemptionDate() {self._yieldRedemptionDate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _execID: String? = nil
  fileprivate var _commissionAndFees: Double? = nil
  fileprivate var _currency: String? = nil
  fileprivate var _realizedPnl: Double? = nil
  fileprivate var _bondYield: Double? = nil
  fileprivate var _yieldRedemptionDate: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBCommissionAndFeesReport: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".CommissionAndFeesReport"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}execId\0\u{1}commissionAndFees\0\u{1}currency\0\u{1}realizedPNL\0\u{1}bondYield\0\u{1}yieldRedemptionDate\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._execID) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self._commissionAndFees) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._currency) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._realizedPnl) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self._bondYield) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._yieldRedemptionDate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._execID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._commissionAndFees {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._currency {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._realizedPnl {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._bondYield {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._yieldRedemptionDate {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBCommissionAndFeesReport, rhs: IBPBCommissionAndFeesReport) -> Bool {
    if lhs._execID != rhs._execID {return false}
    if lhs._commissionAndFees != rhs._commissionAndFees {return false}
    if lhs._currency != rhs._currency {return false}
    if lhs._realizedPnl != rhs._realizedPnl {return false}
    if lhs._bondYield != rhs._bondYield {return false}
    if lhs._yieldRedemptionDate != rhs._yieldRedemptionDate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
