// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Contract.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBContract: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var conID: Int32 {
    get {_storage._conID ?? 0}
    set {_uniqueStorage()._conID = newValue}
  }
  /// Returns true if `conID` has been explicitly set.
  public var hasConID: Bool {_storage._conID != nil}
  /// Clears the value of `conID`. Subsequent reads from it will return its default value.
  public mutating func clearConID() {_uniqueStorage()._conID = nil}

  public var symbol: String {
    get {_storage._symbol ?? String()}
    set {_uniqueStorage()._symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {_storage._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {_uniqueStorage()._symbol = nil}

  public var secType: String {
    get {_storage._secType ?? String()}
    set {_uniqueStorage()._secType = newValue}
  }
  /// Returns true if `secType` has been explicitly set.
  public var hasSecType: Bool {_storage._secType != nil}
  /// Clears the value of `secType`. Subsequent reads from it will return its default value.
  public mutating func clearSecType() {_uniqueStorage()._secType = nil}

  public var lastTradeDateOrContractMonth: String {
    get {_storage._lastTradeDateOrContractMonth ?? String()}
    set {_uniqueStorage()._lastTradeDateOrContractMonth = newValue}
  }
  /// Returns true if `lastTradeDateOrContractMonth` has been explicitly set.
  public var hasLastTradeDateOrContractMonth: Bool {_storage._lastTradeDateOrContractMonth != nil}
  /// Clears the value of `lastTradeDateOrContractMonth`. Subsequent reads from it will return its default value.
  public mutating func clearLastTradeDateOrContractMonth() {_uniqueStorage()._lastTradeDateOrContractMonth = nil}

  public var strike: Double {
    get {_storage._strike ?? 0}
    set {_uniqueStorage()._strike = newValue}
  }
  /// Returns true if `strike` has been explicitly set.
  public var hasStrike: Bool {_storage._strike != nil}
  /// Clears the value of `strike`. Subsequent reads from it will return its default value.
  public mutating func clearStrike() {_uniqueStorage()._strike = nil}

  public var right: String {
    get {_storage._right ?? String()}
    set {_uniqueStorage()._right = newValue}
  }
  /// Returns true if `right` has been explicitly set.
  public var hasRight: Bool {_storage._right != nil}
  /// Clears the value of `right`. Subsequent reads from it will return its default value.
  public mutating func clearRight() {_uniqueStorage()._right = nil}

  public var multiplier: Double {
    get {_storage._multiplier ?? 0}
    set {_uniqueStorage()._multiplier = newValue}
  }
  /// Returns true if `multiplier` has been explicitly set.
  public var hasMultiplier: Bool {_storage._multiplier != nil}
  /// Clears the value of `multiplier`. Subsequent reads from it will return its default value.
  public mutating func clearMultiplier() {_uniqueStorage()._multiplier = nil}

  public var exchange: String {
    get {_storage._exchange ?? String()}
    set {_uniqueStorage()._exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {_storage._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {_uniqueStorage()._exchange = nil}

  public var primaryExch: String {
    get {_storage._primaryExch ?? String()}
    set {_uniqueStorage()._primaryExch = newValue}
  }
  /// Returns true if `primaryExch` has been explicitly set.
  public var hasPrimaryExch: Bool {_storage._primaryExch != nil}
  /// Clears the value of `primaryExch`. Subsequent reads from it will return its default value.
  public mutating func clearPrimaryExch() {_uniqueStorage()._primaryExch = nil}

  public var currency: String {
    get {_storage._currency ?? String()}
    set {_uniqueStorage()._currency = newValue}
  }
  /// Returns true if `currency` has been explicitly set.
  public var hasCurrency: Bool {_storage._currency != nil}
  /// Clears the value of `currency`. Subsequent reads from it will return its default value.
  public mutating func clearCurrency() {_uniqueStorage()._currency = nil}

  public var localSymbol: String {
    get {_storage._localSymbol ?? String()}
    set {_uniqueStorage()._localSymbol = newValue}
  }
  /// Returns true if `localSymbol` has been explicitly set.
  public var hasLocalSymbol: Bool {_storage._localSymbol != nil}
  /// Clears the value of `localSymbol`. Subsequent reads from it will return its default value.
  public mutating func clearLocalSymbol() {_uniqueStorage()._localSymbol = nil}

  public var tradingClass: String {
    get {_storage._tradingClass ?? String()}
    set {_uniqueStorage()._tradingClass = newValue}
  }
  /// Returns true if `tradingClass` has been explicitly set.
  public var hasTradingClass: Bool {_storage._tradingClass != nil}
  /// Clears the value of `tradingClass`. Subsequent reads from it will return its default value.
  public mutating func clearTradingClass() {_uniqueStorage()._tradingClass = nil}

  public var secIDType: String {
    get {_storage._secIDType ?? String()}
    set {_uniqueStorage()._secIDType = newValue}
  }
  /// Returns true if `secIDType` has been explicitly set.
  public var hasSecIDType: Bool {_storage._secIDType != nil}
  /// Clears the value of `secIDType`. Subsequent reads from it will return its default value.
  public mutating func clearSecIDType() {_uniqueStorage()._secIDType = nil}

  public var secID: String {
    get {_storage._secID ?? String()}
    set {_uniqueStorage()._secID = newValue}
  }
  /// Returns true if `secID` has been explicitly set.
  public var hasSecID: Bool {_storage._secID != nil}
  /// Clears the value of `secID`. Subsequent reads from it will return its default value.
  public mutating func clearSecID() {_uniqueStorage()._secID = nil}

  public var description_p: String {
    get {_storage._description_p ?? String()}
    set {_uniqueStorage()._description_p = newValue}
  }
  /// Returns true if `description_p` has been explicitly set.
  public var hasDescription_p: Bool {_storage._description_p != nil}
  /// Clears the value of `description_p`. Subsequent reads from it will return its default value.
  public mutating func clearDescription_p() {_uniqueStorage()._description_p = nil}

  public var issuerID: String {
    get {_storage._issuerID ?? String()}
    set {_uniqueStorage()._issuerID = newValue}
  }
  /// Returns true if `issuerID` has been explicitly set.
  public var hasIssuerID: Bool {_storage._issuerID != nil}
  /// Clears the value of `issuerID`. Subsequent reads from it will return its default value.
  public mutating func clearIssuerID() {_uniqueStorage()._issuerID = nil}

  public var deltaNeutralContract: IBPBDeltaNeutralContract {
    get {_storage._deltaNeutralContract ?? IBPBDeltaNeutralContract()}
    set {_uniqueStorage()._deltaNeutralContract = newValue}
  }
  /// Returns true if `deltaNeutralContract` has been explicitly set.
  public var hasDeltaNeutralContract: Bool {_storage._deltaNeutralContract != nil}
  /// Clears the value of `deltaNeutralContract`. Subsequent reads from it will return its default value.
  public mutating func clearDeltaNeutralContract() {_uniqueStorage()._deltaNeutralContract = nil}

  public var includeExpired: Bool {
    get {_storage._includeExpired ?? false}
    set {_uniqueStorage()._includeExpired = newValue}
  }
  /// Returns true if `includeExpired` has been explicitly set.
  public var hasIncludeExpired: Bool {_storage._includeExpired != nil}
  /// Clears the value of `includeExpired`. Subsequent reads from it will return its default value.
  public mutating func clearIncludeExpired() {_uniqueStorage()._includeExpired = nil}

  public var comboLegsDescrip: String {
    get {_storage._comboLegsDescrip ?? String()}
    set {_uniqueStorage()._comboLegsDescrip = newValue}
  }
  /// Returns true if `comboLegsDescrip` has been explicitly set.
  public var hasComboLegsDescrip: Bool {_storage._comboLegsDescrip != nil}
  /// Clears the value of `comboLegsDescrip`. Subsequent reads from it will return its default value.
  public mutating func clearComboLegsDescrip() {_uniqueStorage()._comboLegsDescrip = nil}

  public var comboLegs: [IBPBComboLeg] {
    get {_storage._comboLegs}
    set {_uniqueStorage()._comboLegs = newValue}
  }

  public var lastTradeDate: String {
    get {_storage._lastTradeDate ?? String()}
    set {_uniqueStorage()._lastTradeDate = newValue}
  }
  /// Returns true if `lastTradeDate` has been explicitly set.
  public var hasLastTradeDate: Bool {_storage._lastTradeDate != nil}
  /// Clears the value of `lastTradeDate`. Subsequent reads from it will return its default value.
  public mutating func clearLastTradeDate() {_uniqueStorage()._lastTradeDate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBContract: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Contract"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}conId\0\u{1}symbol\0\u{1}secType\0\u{1}lastTradeDateOrContractMonth\0\u{1}strike\0\u{1}right\0\u{1}multiplier\0\u{1}exchange\0\u{1}primaryExch\0\u{1}currency\0\u{1}localSymbol\0\u{1}tradingClass\0\u{1}secIdType\0\u{1}secId\0\u{1}description\0\u{1}issuerId\0\u{1}deltaNeutralContract\0\u{1}includeExpired\0\u{1}comboLegsDescrip\0\u{1}comboLegs\0\u{1}lastTradeDate\0")

  fileprivate class _StorageClass {
    var _conID: Int32? = nil
    var _symbol: String? = nil
    var _secType: String? = nil
    var _lastTradeDateOrContractMonth: String? = nil
    var _strike: Double? = nil
    var _right: String? = nil
    var _multiplier: Double? = nil
    var _exchange: String? = nil
    var _primaryExch: String? = nil
    var _currency: String? = nil
    var _localSymbol: String? = nil
    var _tradingClass: String? = nil
    var _secIDType: String? = nil
    var _secID: String? = nil
    var _description_p: String? = nil
    var _issuerID: String? = nil
    var _deltaNeutralContract: IBPBDeltaNeutralContract? = nil
    var _includeExpired: Bool? = nil
    var _comboLegsDescrip: String? = nil
    var _comboLegs: [IBPBComboLeg] = []
    var _lastTradeDate: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _conID = source._conID
      _symbol = source._symbol
      _secType = source._secType
      _lastTradeDateOrContractMonth = source._lastTradeDateOrContractMonth
      _strike = source._strike
      _right = source._right
      _multiplier = source._multiplier
      _exchange = source._exchange
      _primaryExch = source._primaryExch
      _currency = source._currency
      _localSymbol = source._localSymbol
      _tradingClass = source._tradingClass
      _secIDType = source._secIDType
      _secID = source._secID
      _description_p = source._description_p
      _issuerID = source._issuerID
      _deltaNeutralContract = source._deltaNeutralContract
      _includeExpired = source._includeExpired
      _comboLegsDescrip = source._comboLegsDescrip
      _comboLegs = source._comboLegs
      _lastTradeDate = source._lastTradeDate
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._conID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._symbol) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._secType) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._lastTradeDateOrContractMonth) }()
        case 5: try { try decoder.decodeSingularDoubleField(value: &_storage._strike) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._right) }()
        case 7: try { try decoder.decodeSingularDoubleField(value: &_storage._multiplier) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._exchange) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._primaryExch) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._currency) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._localSymbol) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._tradingClass) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._secIDType) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._secID) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._description_p) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._issuerID) }()
        case 17: try { try decoder.decodeSingularMessageField(value: &_storage._deltaNeutralContract) }()
        case 18: try { try decoder.decodeSingularBoolField(value: &_storage._includeExpired) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._comboLegsDescrip) }()
        case 20: try { try decoder.decodeRepeatedMessageField(value: &_storage._comboLegs) }()
        case 21: try { try decoder.decodeSingularStringField(value: &_storage._lastTradeDate) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._conID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._symbol {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._secType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._lastTradeDateOrContractMonth {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._strike {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._right {
        try visitor.visitSingularStringField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._multiplier {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._exchange {
        try visitor.visitSingularStringField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._primaryExch {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._currency {
        try visitor.visitSingularStringField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._localSymbol {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._tradingClass {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._secIDType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._secID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._description_p {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._issuerID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 16)
      } }()
      try { if let v = _storage._deltaNeutralContract {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
      } }()
      try { if let v = _storage._includeExpired {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 18)
      } }()
      try { if let v = _storage._comboLegsDescrip {
        try visitor.visitSingularStringField(value: v, fieldNumber: 19)
      } }()
      if !_storage._comboLegs.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._comboLegs, fieldNumber: 20)
      }
      try { if let v = _storage._lastTradeDate {
        try visitor.visitSingularStringField(value: v, fieldNumber: 21)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBContract, rhs: IBPBContract) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._conID != rhs_storage._conID {return false}
        if _storage._symbol != rhs_storage._symbol {return false}
        if _storage._secType != rhs_storage._secType {return false}
        if _storage._lastTradeDateOrContractMonth != rhs_storage._lastTradeDateOrContractMonth {return false}
        if _storage._strike != rhs_storage._strike {return false}
        if _storage._right != rhs_storage._right {return false}
        if _storage._multiplier != rhs_storage._multiplier {return false}
        if _storage._exchange != rhs_storage._exchange {return false}
        if _storage._primaryExch != rhs_storage._primaryExch {return false}
        if _storage._currency != rhs_storage._currency {return false}
        if _storage._localSymbol != rhs_storage._localSymbol {return false}
        if _storage._tradingClass != rhs_storage._tradingClass {return false}
        if _storage._secIDType != rhs_storage._secIDType {return false}
        if _storage._secID != rhs_storage._secID {return false}
        if _storage._description_p != rhs_storage._description_p {return false}
        if _storage._issuerID != rhs_storage._issuerID {return false}
        if _storage._deltaNeutralContract != rhs_storage._deltaNeutralContract {return false}
        if _storage._includeExpired != rhs_storage._includeExpired {return false}
        if _storage._comboLegsDescrip != rhs_storage._comboLegsDescrip {return false}
        if _storage._comboLegs != rhs_storage._comboLegs {return false}
        if _storage._lastTradeDate != rhs_storage._lastTradeDate {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
