// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ContractDetails.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBContractDetails: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var marketName: String {
    get {_storage._marketName ?? String()}
    set {_uniqueStorage()._marketName = newValue}
  }
  /// Returns true if `marketName` has been explicitly set.
  public var hasMarketName: Bool {_storage._marketName != nil}
  /// Clears the value of `marketName`. Subsequent reads from it will return its default value.
  public mutating func clearMarketName() {_uniqueStorage()._marketName = nil}

  public var minTick: String {
    get {_storage._minTick ?? String()}
    set {_uniqueStorage()._minTick = newValue}
  }
  /// Returns true if `minTick` has been explicitly set.
  public var hasMinTick: Bool {_storage._minTick != nil}
  /// Clears the value of `minTick`. Subsequent reads from it will return its default value.
  public mutating func clearMinTick() {_uniqueStorage()._minTick = nil}

  public var orderTypes: String {
    get {_storage._orderTypes ?? String()}
    set {_uniqueStorage()._orderTypes = newValue}
  }
  /// Returns true if `orderTypes` has been explicitly set.
  public var hasOrderTypes: Bool {_storage._orderTypes != nil}
  /// Clears the value of `orderTypes`. Subsequent reads from it will return its default value.
  public mutating func clearOrderTypes() {_uniqueStorage()._orderTypes = nil}

  public var validExchanges: String {
    get {_storage._validExchanges ?? String()}
    set {_uniqueStorage()._validExchanges = newValue}
  }
  /// Returns true if `validExchanges` has been explicitly set.
  public var hasValidExchanges: Bool {_storage._validExchanges != nil}
  /// Clears the value of `validExchanges`. Subsequent reads from it will return its default value.
  public mutating func clearValidExchanges() {_uniqueStorage()._validExchanges = nil}

  public var priceMagnifier: Int32 {
    get {_storage._priceMagnifier ?? 0}
    set {_uniqueStorage()._priceMagnifier = newValue}
  }
  /// Returns true if `priceMagnifier` has been explicitly set.
  public var hasPriceMagnifier: Bool {_storage._priceMagnifier != nil}
  /// Clears the value of `priceMagnifier`. Subsequent reads from it will return its default value.
  public mutating func clearPriceMagnifier() {_uniqueStorage()._priceMagnifier = nil}

  public var underConID: Int32 {
    get {_storage._underConID ?? 0}
    set {_uniqueStorage()._underConID = newValue}
  }
  /// Returns true if `underConID` has been explicitly set.
  public var hasUnderConID: Bool {_storage._underConID != nil}
  /// Clears the value of `underConID`. Subsequent reads from it will return its default value.
  public mutating func clearUnderConID() {_uniqueStorage()._underConID = nil}

  public var longName: String {
    get {_storage._longName ?? String()}
    set {_uniqueStorage()._longName = newValue}
  }
  /// Returns true if `longName` has been explicitly set.
  public var hasLongName: Bool {_storage._longName != nil}
  /// Clears the value of `longName`. Subsequent reads from it will return its default value.
  public mutating func clearLongName() {_uniqueStorage()._longName = nil}

  public var contractMonth: String {
    get {_storage._contractMonth ?? String()}
    set {_uniqueStorage()._contractMonth = newValue}
  }
  /// Returns true if `contractMonth` has been explicitly set.
  public var hasContractMonth: Bool {_storage._contractMonth != nil}
  /// Clears the value of `contractMonth`. Subsequent reads from it will return its default value.
  public mutating func clearContractMonth() {_uniqueStorage()._contractMonth = nil}

  public var industry: String {
    get {_storage._industry ?? String()}
    set {_uniqueStorage()._industry = newValue}
  }
  /// Returns true if `industry` has been explicitly set.
  public var hasIndustry: Bool {_storage._industry != nil}
  /// Clears the value of `industry`. Subsequent reads from it will return its default value.
  public mutating func clearIndustry() {_uniqueStorage()._industry = nil}

  public var category: String {
    get {_storage._category ?? String()}
    set {_uniqueStorage()._category = newValue}
  }
  /// Returns true if `category` has been explicitly set.
  public var hasCategory: Bool {_storage._category != nil}
  /// Clears the value of `category`. Subsequent reads from it will return its default value.
  public mutating func clearCategory() {_uniqueStorage()._category = nil}

  public var subcategory: String {
    get {_storage._subcategory ?? String()}
    set {_uniqueStorage()._subcategory = newValue}
  }
  /// Returns true if `subcategory` has been explicitly set.
  public var hasSubcategory: Bool {_storage._subcategory != nil}
  /// Clears the value of `subcategory`. Subsequent reads from it will return its default value.
  public mutating func clearSubcategory() {_uniqueStorage()._subcategory = nil}

  public var timeZoneID: String {
    get {_storage._timeZoneID ?? String()}
    set {_uniqueStorage()._timeZoneID = newValue}
  }
  /// Returns true if `timeZoneID` has been explicitly set.
  public var hasTimeZoneID: Bool {_storage._timeZoneID != nil}
  /// Clears the value of `timeZoneID`. Subsequent reads from it will return its default value.
  public mutating func clearTimeZoneID() {_uniqueStorage()._timeZoneID = nil}

  public var tradingHours: String {
    get {_storage._tradingHours ?? String()}
    set {_uniqueStorage()._tradingHours = newValue}
  }
  /// Returns true if `tradingHours` has been explicitly set.
  public var hasTradingHours: Bool {_storage._tradingHours != nil}
  /// Clears the value of `tradingHours`. Subsequent reads from it will return its default value.
  public mutating func clearTradingHours() {_uniqueStorage()._tradingHours = nil}

  public var liquidHours: String {
    get {_storage._liquidHours ?? String()}
    set {_uniqueStorage()._liquidHours = newValue}
  }
  /// Returns true if `liquidHours` has been explicitly set.
  public var hasLiquidHours: Bool {_storage._liquidHours != nil}
  /// Clears the value of `liquidHours`. Subsequent reads from it will return its default value.
  public mutating func clearLiquidHours() {_uniqueStorage()._liquidHours = nil}

  public var evRule: String {
    get {_storage._evRule ?? String()}
    set {_uniqueStorage()._evRule = newValue}
  }
  /// Returns true if `evRule` has been explicitly set.
  public var hasEvRule: Bool {_storage._evRule != nil}
  /// Clears the value of `evRule`. Subsequent reads from it will return its default value.
  public mutating func clearEvRule() {_uniqueStorage()._evRule = nil}

  public var evMultiplier: Double {
    get {_storage._evMultiplier ?? 0}
    set {_uniqueStorage()._evMultiplier = newValue}
  }
  /// Returns true if `evMultiplier` has been explicitly set.
  public var hasEvMultiplier: Bool {_storage._evMultiplier != nil}
  /// Clears the value of `evMultiplier`. Subsequent reads from it will return its default value.
  public mutating func clearEvMultiplier() {_uniqueStorage()._evMultiplier = nil}

  public var secIDList: Dictionary<String,String> {
    get {_storage._secIDList}
    set {_uniqueStorage()._secIDList = newValue}
  }

  public var aggGroup: Int32 {
    get {_storage._aggGroup ?? 0}
    set {_uniqueStorage()._aggGroup = newValue}
  }
  /// Returns true if `aggGroup` has been explicitly set.
  public var hasAggGroup: Bool {_storage._aggGroup != nil}
  /// Clears the value of `aggGroup`. Subsequent reads from it will return its default value.
  public mutating func clearAggGroup() {_uniqueStorage()._aggGroup = nil}

  public var underSymbol: String {
    get {_storage._underSymbol ?? String()}
    set {_uniqueStorage()._underSymbol = newValue}
  }
  /// Returns true if `underSymbol` has been explicitly set.
  public var hasUnderSymbol: Bool {_storage._underSymbol != nil}
  /// Clears the value of `underSymbol`. Subsequent reads from it will return its default value.
  public mutating func clearUnderSymbol() {_uniqueStorage()._underSymbol = nil}

  public var underSecType: String {
    get {_storage._underSecType ?? String()}
    set {_uniqueStorage()._underSecType = newValue}
  }
  /// Returns true if `underSecType` has been explicitly set.
  public var hasUnderSecType: Bool {_storage._underSecType != nil}
  /// Clears the value of `underSecType`. Subsequent reads from it will return its default value.
  public mutating func clearUnderSecType() {_uniqueStorage()._underSecType = nil}

  public var marketRuleIds: String {
    get {_storage._marketRuleIds ?? String()}
    set {_uniqueStorage()._marketRuleIds = newValue}
  }
  /// Returns true if `marketRuleIds` has been explicitly set.
  public var hasMarketRuleIds: Bool {_storage._marketRuleIds != nil}
  /// Clears the value of `marketRuleIds`. Subsequent reads from it will return its default value.
  public mutating func clearMarketRuleIds() {_uniqueStorage()._marketRuleIds = nil}

  public var realExpirationDate: String {
    get {_storage._realExpirationDate ?? String()}
    set {_uniqueStorage()._realExpirationDate = newValue}
  }
  /// Returns true if `realExpirationDate` has been explicitly set.
  public var hasRealExpirationDate: Bool {_storage._realExpirationDate != nil}
  /// Clears the value of `realExpirationDate`. Subsequent reads from it will return its default value.
  public mutating func clearRealExpirationDate() {_uniqueStorage()._realExpirationDate = nil}

  public var stockType: String {
    get {_storage._stockType ?? String()}
    set {_uniqueStorage()._stockType = newValue}
  }
  /// Returns true if `stockType` has been explicitly set.
  public var hasStockType: Bool {_storage._stockType != nil}
  /// Clears the value of `stockType`. Subsequent reads from it will return its default value.
  public mutating func clearStockType() {_uniqueStorage()._stockType = nil}

  public var minSize: String {
    get {_storage._minSize ?? String()}
    set {_uniqueStorage()._minSize = newValue}
  }
  /// Returns true if `minSize` has been explicitly set.
  public var hasMinSize: Bool {_storage._minSize != nil}
  /// Clears the value of `minSize`. Subsequent reads from it will return its default value.
  public mutating func clearMinSize() {_uniqueStorage()._minSize = nil}

  public var sizeIncrement: String {
    get {_storage._sizeIncrement ?? String()}
    set {_uniqueStorage()._sizeIncrement = newValue}
  }
  /// Returns true if `sizeIncrement` has been explicitly set.
  public var hasSizeIncrement: Bool {_storage._sizeIncrement != nil}
  /// Clears the value of `sizeIncrement`. Subsequent reads from it will return its default value.
  public mutating func clearSizeIncrement() {_uniqueStorage()._sizeIncrement = nil}

  public var suggestedSizeIncrement: String {
    get {_storage._suggestedSizeIncrement ?? String()}
    set {_uniqueStorage()._suggestedSizeIncrement = newValue}
  }
  /// Returns true if `suggestedSizeIncrement` has been explicitly set.
  public var hasSuggestedSizeIncrement: Bool {_storage._suggestedSizeIncrement != nil}
  /// Clears the value of `suggestedSizeIncrement`. Subsequent reads from it will return its default value.
  public mutating func clearSuggestedSizeIncrement() {_uniqueStorage()._suggestedSizeIncrement = nil}

  /// fund	fields
  public var fundName: String {
    get {_storage._fundName ?? String()}
    set {_uniqueStorage()._fundName = newValue}
  }
  /// Returns true if `fundName` has been explicitly set.
  public var hasFundName: Bool {_storage._fundName != nil}
  /// Clears the value of `fundName`. Subsequent reads from it will return its default value.
  public mutating func clearFundName() {_uniqueStorage()._fundName = nil}

  public var fundFamily: String {
    get {_storage._fundFamily ?? String()}
    set {_uniqueStorage()._fundFamily = newValue}
  }
  /// Returns true if `fundFamily` has been explicitly set.
  public var hasFundFamily: Bool {_storage._fundFamily != nil}
  /// Clears the value of `fundFamily`. Subsequent reads from it will return its default value.
  public mutating func clearFundFamily() {_uniqueStorage()._fundFamily = nil}

  public var fundType: String {
    get {_storage._fundType ?? String()}
    set {_uniqueStorage()._fundType = newValue}
  }
  /// Returns true if `fundType` has been explicitly set.
  public var hasFundType: Bool {_storage._fundType != nil}
  /// Clears the value of `fundType`. Subsequent reads from it will return its default value.
  public mutating func clearFundType() {_uniqueStorage()._fundType = nil}

  public var fundFrontLoad: String {
    get {_storage._fundFrontLoad ?? String()}
    set {_uniqueStorage()._fundFrontLoad = newValue}
  }
  /// Returns true if `fundFrontLoad` has been explicitly set.
  public var hasFundFrontLoad: Bool {_storage._fundFrontLoad != nil}
  /// Clears the value of `fundFrontLoad`. Subsequent reads from it will return its default value.
  public mutating func clearFundFrontLoad() {_uniqueStorage()._fundFrontLoad = nil}

  public var fundBackLoad: String {
    get {_storage._fundBackLoad ?? String()}
    set {_uniqueStorage()._fundBackLoad = newValue}
  }
  /// Returns true if `fundBackLoad` has been explicitly set.
  public var hasFundBackLoad: Bool {_storage._fundBackLoad != nil}
  /// Clears the value of `fundBackLoad`. Subsequent reads from it will return its default value.
  public mutating func clearFundBackLoad() {_uniqueStorage()._fundBackLoad = nil}

  public var fundBackLoadTimeInterval: String {
    get {_storage._fundBackLoadTimeInterval ?? String()}
    set {_uniqueStorage()._fundBackLoadTimeInterval = newValue}
  }
  /// Returns true if `fundBackLoadTimeInterval` has been explicitly set.
  public var hasFundBackLoadTimeInterval: Bool {_storage._fundBackLoadTimeInterval != nil}
  /// Clears the value of `fundBackLoadTimeInterval`. Subsequent reads from it will return its default value.
  public mutating func clearFundBackLoadTimeInterval() {_uniqueStorage()._fundBackLoadTimeInterval = nil}

  public var fundManagementFee: String {
    get {_storage._fundManagementFee ?? String()}
    set {_uniqueStorage()._fundManagementFee = newValue}
  }
  /// Returns true if `fundManagementFee` has been explicitly set.
  public var hasFundManagementFee: Bool {_storage._fundManagementFee != nil}
  /// Clears the value of `fundManagementFee`. Subsequent reads from it will return its default value.
  public mutating func clearFundManagementFee() {_uniqueStorage()._fundManagementFee = nil}

  public var fundClosed: Bool {
    get {_storage._fundClosed ?? false}
    set {_uniqueStorage()._fundClosed = newValue}
  }
  /// Returns true if `fundClosed` has been explicitly set.
  public var hasFundClosed: Bool {_storage._fundClosed != nil}
  /// Clears the value of `fundClosed`. Subsequent reads from it will return its default value.
  public mutating func clearFundClosed() {_uniqueStorage()._fundClosed = nil}

  public var fundClosedForNewInvestors: Bool {
    get {_storage._fundClosedForNewInvestors ?? false}
    set {_uniqueStorage()._fundClosedForNewInvestors = newValue}
  }
  /// Returns true if `fundClosedForNewInvestors` has been explicitly set.
  public var hasFundClosedForNewInvestors: Bool {_storage._fundClosedForNewInvestors != nil}
  /// Clears the value of `fundClosedForNewInvestors`. Subsequent reads from it will return its default value.
  public mutating func clearFundClosedForNewInvestors() {_uniqueStorage()._fundClosedForNewInvestors = nil}

  public var fundClosedForNewMoney: Bool {
    get {_storage._fundClosedForNewMoney ?? false}
    set {_uniqueStorage()._fundClosedForNewMoney = newValue}
  }
  /// Returns true if `fundClosedForNewMoney` has been explicitly set.
  public var hasFundClosedForNewMoney: Bool {_storage._fundClosedForNewMoney != nil}
  /// Clears the value of `fundClosedForNewMoney`. Subsequent reads from it will return its default value.
  public mutating func clearFundClosedForNewMoney() {_uniqueStorage()._fundClosedForNewMoney = nil}

  public var fundNotifyAmount: String {
    get {_storage._fundNotifyAmount ?? String()}
    set {_uniqueStorage()._fundNotifyAmount = newValue}
  }
  /// Returns true if `fundNotifyAmount` has been explicitly set.
  public var hasFundNotifyAmount: Bool {_storage._fundNotifyAmount != nil}
  /// Clears the value of `fundNotifyAmount`. Subsequent reads from it will return its default value.
  public mutating func clearFundNotifyAmount() {_uniqueStorage()._fundNotifyAmount = nil}

  public var fundMinimumInitialPurchase: String {
    get {_storage._fundMinimumInitialPurchase ?? String()}
    set {_uniqueStorage()._fundMinimumInitialPurchase = newValue}
  }
  /// Returns true if `fundMinimumInitialPurchase` has been explicitly set.
  public var hasFundMinimumInitialPurchase: Bool {_storage._fundMinimumInitialPurchase != nil}
  /// Clears the value of `fundMinimumInitialPurchase`. Subsequent reads from it will return its default value.
  public mutating func clearFundMinimumInitialPurchase() {_uniqueStorage()._fundMinimumInitialPurchase = nil}

  public var fundMinimumSubsequentPurchase: String {
    get {_storage._fundMinimumSubsequentPurchase ?? String()}
    set {_uniqueStorage()._fundMinimumSubsequentPurchase = newValue}
  }
  /// Returns true if `fundMinimumSubsequentPurchase` has been explicitly set.
  public var hasFundMinimumSubsequentPurchase: Bool {_storage._fundMinimumSubsequentPurchase != nil}
  /// Clears the value of `fundMinimumSubsequentPurchase`. Subsequent reads from it will return its default value.
  public mutating func clearFundMinimumSubsequentPurchase() {_uniqueStorage()._fundMinimumSubsequentPurchase = nil}

  public var fundBlueSkyStates: String {
    get {_storage._fundBlueSkyStates ?? String()}
    set {_uniqueStorage()._fundBlueSkyStates = newValue}
  }
  /// Returns true if `fundBlueSkyStates` has been explicitly set.
  public var hasFundBlueSkyStates: Bool {_storage._fundBlueSkyStates != nil}
  /// Clears the value of `fundBlueSkyStates`. Subsequent reads from it will return its default value.
  public mutating func clearFundBlueSkyStates() {_uniqueStorage()._fundBlueSkyStates = nil}

  public var fundBlueSkyTerritories: String {
    get {_storage._fundBlueSkyTerritories ?? String()}
    set {_uniqueStorage()._fundBlueSkyTerritories = newValue}
  }
  /// Returns true if `fundBlueSkyTerritories` has been explicitly set.
  public var hasFundBlueSkyTerritories: Bool {_storage._fundBlueSkyTerritories != nil}
  /// Clears the value of `fundBlueSkyTerritories`. Subsequent reads from it will return its default value.
  public mutating func clearFundBlueSkyTerritories() {_uniqueStorage()._fundBlueSkyTerritories = nil}

  public var fundDistributionPolicyIndicator: String {
    get {_storage._fundDistributionPolicyIndicator ?? String()}
    set {_uniqueStorage()._fundDistributionPolicyIndicator = newValue}
  }
  /// Returns true if `fundDistributionPolicyIndicator` has been explicitly set.
  public var hasFundDistributionPolicyIndicator: Bool {_storage._fundDistributionPolicyIndicator != nil}
  /// Clears the value of `fundDistributionPolicyIndicator`. Subsequent reads from it will return its default value.
  public mutating func clearFundDistributionPolicyIndicator() {_uniqueStorage()._fundDistributionPolicyIndicator = nil}

  public var fundAssetType: String {
    get {_storage._fundAssetType ?? String()}
    set {_uniqueStorage()._fundAssetType = newValue}
  }
  /// Returns true if `fundAssetType` has been explicitly set.
  public var hasFundAssetType: Bool {_storage._fundAssetType != nil}
  /// Clears the value of `fundAssetType`. Subsequent reads from it will return its default value.
  public mutating func clearFundAssetType() {_uniqueStorage()._fundAssetType = nil}

  /// bond fields
  public var cusip: String {
    get {_storage._cusip ?? String()}
    set {_uniqueStorage()._cusip = newValue}
  }
  /// Returns true if `cusip` has been explicitly set.
  public var hasCusip: Bool {_storage._cusip != nil}
  /// Clears the value of `cusip`. Subsequent reads from it will return its default value.
  public mutating func clearCusip() {_uniqueStorage()._cusip = nil}

  public var issueDate: String {
    get {_storage._issueDate ?? String()}
    set {_uniqueStorage()._issueDate = newValue}
  }
  /// Returns true if `issueDate` has been explicitly set.
  public var hasIssueDate: Bool {_storage._issueDate != nil}
  /// Clears the value of `issueDate`. Subsequent reads from it will return its default value.
  public mutating func clearIssueDate() {_uniqueStorage()._issueDate = nil}

  public var ratings: String {
    get {_storage._ratings ?? String()}
    set {_uniqueStorage()._ratings = newValue}
  }
  /// Returns true if `ratings` has been explicitly set.
  public var hasRatings: Bool {_storage._ratings != nil}
  /// Clears the value of `ratings`. Subsequent reads from it will return its default value.
  public mutating func clearRatings() {_uniqueStorage()._ratings = nil}

  public var bondType: String {
    get {_storage._bondType ?? String()}
    set {_uniqueStorage()._bondType = newValue}
  }
  /// Returns true if `bondType` has been explicitly set.
  public var hasBondType: Bool {_storage._bondType != nil}
  /// Clears the value of `bondType`. Subsequent reads from it will return its default value.
  public mutating func clearBondType() {_uniqueStorage()._bondType = nil}

  public var coupon: Double {
    get {_storage._coupon ?? 0}
    set {_uniqueStorage()._coupon = newValue}
  }
  /// Returns true if `coupon` has been explicitly set.
  public var hasCoupon: Bool {_storage._coupon != nil}
  /// Clears the value of `coupon`. Subsequent reads from it will return its default value.
  public mutating func clearCoupon() {_uniqueStorage()._coupon = nil}

  public var couponType: String {
    get {_storage._couponType ?? String()}
    set {_uniqueStorage()._couponType = newValue}
  }
  /// Returns true if `couponType` has been explicitly set.
  public var hasCouponType: Bool {_storage._couponType != nil}
  /// Clears the value of `couponType`. Subsequent reads from it will return its default value.
  public mutating func clearCouponType() {_uniqueStorage()._couponType = nil}

  public var convertible: Bool {
    get {_storage._convertible ?? false}
    set {_uniqueStorage()._convertible = newValue}
  }
  /// Returns true if `convertible` has been explicitly set.
  public var hasConvertible: Bool {_storage._convertible != nil}
  /// Clears the value of `convertible`. Subsequent reads from it will return its default value.
  public mutating func clearConvertible() {_uniqueStorage()._convertible = nil}

  public var callable: Bool {
    get {_storage._callable ?? false}
    set {_uniqueStorage()._callable = newValue}
  }
  /// Returns true if `callable` has been explicitly set.
  public var hasCallable: Bool {_storage._callable != nil}
  /// Clears the value of `callable`. Subsequent reads from it will return its default value.
  public mutating func clearCallable() {_uniqueStorage()._callable = nil}

  public var puttable: Bool {
    get {_storage._puttable ?? false}
    set {_uniqueStorage()._puttable = newValue}
  }
  /// Returns true if `puttable` has been explicitly set.
  public var hasPuttable: Bool {_storage._puttable != nil}
  /// Clears the value of `puttable`. Subsequent reads from it will return its default value.
  public mutating func clearPuttable() {_uniqueStorage()._puttable = nil}

  public var descAppend: String {
    get {_storage._descAppend ?? String()}
    set {_uniqueStorage()._descAppend = newValue}
  }
  /// Returns true if `descAppend` has been explicitly set.
  public var hasDescAppend: Bool {_storage._descAppend != nil}
  /// Clears the value of `descAppend`. Subsequent reads from it will return its default value.
  public mutating func clearDescAppend() {_uniqueStorage()._descAppend = nil}

  public var nextOptionDate: String {
    get {_storage._nextOptionDate ?? String()}
    set {_uniqueStorage()._nextOptionDate = newValue}
  }
  /// Returns true if `nextOptionDate` has been explicitly set.
  public var hasNextOptionDate: Bool {_storage._nextOptionDate != nil}
  /// Clears the value of `nextOptionDate`. Subsequent reads from it will return its default value.
  public mutating func clearNextOptionDate() {_uniqueStorage()._nextOptionDate = nil}

  public var nextOptionType: String {
    get {_storage._nextOptionType ?? String()}
    set {_uniqueStorage()._nextOptionType = newValue}
  }
  /// Returns true if `nextOptionType` has been explicitly set.
  public var hasNextOptionType: Bool {_storage._nextOptionType != nil}
  /// Clears the value of `nextOptionType`. Subsequent reads from it will return its default value.
  public mutating func clearNextOptionType() {_uniqueStorage()._nextOptionType = nil}

  public var nextOptionPartial: Bool {
    get {_storage._nextOptionPartial ?? false}
    set {_uniqueStorage()._nextOptionPartial = newValue}
  }
  /// Returns true if `nextOptionPartial` has been explicitly set.
  public var hasNextOptionPartial: Bool {_storage._nextOptionPartial != nil}
  /// Clears the value of `nextOptionPartial`. Subsequent reads from it will return its default value.
  public mutating func clearNextOptionPartial() {_uniqueStorage()._nextOptionPartial = nil}

  public var bondNotes: String {
    get {_storage._bondNotes ?? String()}
    set {_uniqueStorage()._bondNotes = newValue}
  }
  /// Returns true if `bondNotes` has been explicitly set.
  public var hasBondNotes: Bool {_storage._bondNotes != nil}
  /// Clears the value of `bondNotes`. Subsequent reads from it will return its default value.
  public mutating func clearBondNotes() {_uniqueStorage()._bondNotes = nil}

  public var ineligibilityReasonList: [IBPBIneligibilityReason] {
    get {_storage._ineligibilityReasonList}
    set {_uniqueStorage()._ineligibilityReasonList = newValue}
  }

  /// event contract fields
  public var eventContract1: String {
    get {_storage._eventContract1 ?? String()}
    set {_uniqueStorage()._eventContract1 = newValue}
  }
  /// Returns true if `eventContract1` has been explicitly set.
  public var hasEventContract1: Bool {_storage._eventContract1 != nil}
  /// Clears the value of `eventContract1`. Subsequent reads from it will return its default value.
  public mutating func clearEventContract1() {_uniqueStorage()._eventContract1 = nil}

  public var eventContractDescription1: String {
    get {_storage._eventContractDescription1 ?? String()}
    set {_uniqueStorage()._eventContractDescription1 = newValue}
  }
  /// Returns true if `eventContractDescription1` has been explicitly set.
  public var hasEventContractDescription1: Bool {_storage._eventContractDescription1 != nil}
  /// Clears the value of `eventContractDescription1`. Subsequent reads from it will return its default value.
  public mutating func clearEventContractDescription1() {_uniqueStorage()._eventContractDescription1 = nil}

  public var eventContractDescription2: String {
    get {_storage._eventContractDescription2 ?? String()}
    set {_uniqueStorage()._eventContractDescription2 = newValue}
  }
  /// Returns true if `eventContractDescription2` has been explicitly set.
  public var hasEventContractDescription2: Bool {_storage._eventContractDescription2 != nil}
  /// Clears the value of `eventContractDescription2`. Subsequent reads from it will return its default value.
  public mutating func clearEventContractDescription2() {_uniqueStorage()._eventContractDescription2 = nil}

  public var minAlgoSize: String {
    get {_storage._minAlgoSize ?? String()}
    set {_uniqueStorage()._minAlgoSize = newValue}
  }
  /// Returns true if `minAlgoSize` has been explicitly set.
  public var hasMinAlgoSize: Bool {_storage._minAlgoSize != nil}
  /// Clears the value of `minAlgoSize`. Subsequent reads from it will return its default value.
  public mutating func clearMinAlgoSize() {_uniqueStorage()._minAlgoSize = nil}

  public var lastPricePrecision: String {
    get {_storage._lastPricePrecision ?? String()}
    set {_uniqueStorage()._lastPricePrecision = newValue}
  }
  /// Returns true if `lastPricePrecision` has been explicitly set.
  public var hasLastPricePrecision: Bool {_storage._lastPricePrecision != nil}
  /// Clears the value of `lastPricePrecision`. Subsequent reads from it will return its default value.
  public mutating func clearLastPricePrecision() {_uniqueStorage()._lastPricePrecision = nil}

  public var lastSizePrecision: String {
    get {_storage._lastSizePrecision ?? String()}
    set {_uniqueStorage()._lastSizePrecision = newValue}
  }
  /// Returns true if `lastSizePrecision` has been explicitly set.
  public var hasLastSizePrecision: Bool {_storage._lastSizePrecision != nil}
  /// Clears the value of `lastSizePrecision`. Subsequent reads from it will return its default value.
  public mutating func clearLastSizePrecision() {_uniqueStorage()._lastSizePrecision = nil}

  public var settlementMethod: String {
    get {_storage._settlementMethod ?? String()}
    set {_uniqueStorage()._settlementMethod = newValue}
  }
  /// Returns true if `settlementMethod` has been explicitly set.
  public var hasSettlementMethod: Bool {_storage._settlementMethod != nil}
  /// Clears the value of `settlementMethod`. Subsequent reads from it will return its default value.
  public mutating func clearSettlementMethod() {_uniqueStorage()._settlementMethod = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBContractDetails: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ContractDetails"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}marketName\0\u{1}minTick\0\u{1}orderTypes\0\u{1}validExchanges\0\u{1}priceMagnifier\0\u{1}underConId\0\u{1}longName\0\u{1}contractMonth\0\u{1}industry\0\u{1}category\0\u{1}subcategory\0\u{1}timeZoneId\0\u{1}tradingHours\0\u{1}liquidHours\0\u{1}evRule\0\u{1}evMultiplier\0\u{1}secIdList\0\u{1}aggGroup\0\u{1}underSymbol\0\u{1}underSecType\0\u{1}marketRuleIds\0\u{1}realExpirationDate\0\u{1}stockType\0\u{1}minSize\0\u{1}sizeIncrement\0\u{1}suggestedSizeIncrement\0\u{1}fundName\0\u{1}fundFamily\0\u{1}fundType\0\u{1}fundFrontLoad\0\u{1}fundBackLoad\0\u{1}fundBackLoadTimeInterval\0\u{1}fundManagementFee\0\u{1}fundClosed\0\u{1}fundClosedForNewInvestors\0\u{1}fundClosedForNewMoney\0\u{1}fundNotifyAmount\0\u{1}fundMinimumInitialPurchase\0\u{1}fundMinimumSubsequentPurchase\0\u{1}fundBlueSkyStates\0\u{1}fundBlueSkyTerritories\0\u{1}fundDistributionPolicyIndicator\0\u{1}fundAssetType\0\u{1}cusip\0\u{1}issueDate\0\u{1}ratings\0\u{1}bondType\0\u{1}coupon\0\u{1}couponType\0\u{1}convertible\0\u{1}callable\0\u{1}puttable\0\u{1}descAppend\0\u{1}nextOptionDate\0\u{1}nextOptionType\0\u{1}nextOptionPartial\0\u{1}bondNotes\0\u{1}ineligibilityReasonList\0\u{1}eventContract1\0\u{1}eventContractDescription1\0\u{1}eventContractDescription2\0\u{1}minAlgoSize\0\u{1}lastPricePrecision\0\u{1}lastSizePrecision\0\u{1}settlementMethod\0")

  fileprivate class _StorageClass {
    var _marketName: String? = nil
    var _minTick: String? = nil
    var _orderTypes: String? = nil
    var _validExchanges: String? = nil
    var _priceMagnifier: Int32? = nil
    var _underConID: Int32? = nil
    var _longName: String? = nil
    var _contractMonth: String? = nil
    var _industry: String? = nil
    var _category: String? = nil
    var _subcategory: String? = nil
    var _timeZoneID: String? = nil
    var _tradingHours: String? = nil
    var _liquidHours: String? = nil
    var _evRule: String? = nil
    var _evMultiplier: Double? = nil
    var _secIDList: Dictionary<String,String> = [:]
    var _aggGroup: Int32? = nil
    var _underSymbol: String? = nil
    var _underSecType: String? = nil
    var _marketRuleIds: String? = nil
    var _realExpirationDate: String? = nil
    var _stockType: String? = nil
    var _minSize: String? = nil
    var _sizeIncrement: String? = nil
    var _suggestedSizeIncrement: String? = nil
    var _fundName: String? = nil
    var _fundFamily: String? = nil
    var _fundType: String? = nil
    var _fundFrontLoad: String? = nil
    var _fundBackLoad: String? = nil
    var _fundBackLoadTimeInterval: String? = nil
    var _fundManagementFee: String? = nil
    var _fundClosed: Bool? = nil
    var _fundClosedForNewInvestors: Bool? = nil
    var _fundClosedForNewMoney: Bool? = nil
    var _fundNotifyAmount: String? = nil
    var _fundMinimumInitialPurchase: String? = nil
    var _fundMinimumSubsequentPurchase: String? = nil
    var _fundBlueSkyStates: String? = nil
    var _fundBlueSkyTerritories: String? = nil
    var _fundDistributionPolicyIndicator: String? = nil
    var _fundAssetType: String? = nil
    var _cusip: String? = nil
    var _issueDate: String? = nil
    var _ratings: String? = nil
    var _bondType: String? = nil
    var _coupon: Double? = nil
    var _couponType: String? = nil
    var _convertible: Bool? = nil
    var _callable: Bool? = nil
    var _puttable: Bool? = nil
    var _descAppend: String? = nil
    var _nextOptionDate: String? = nil
    var _nextOptionType: String? = nil
    var _nextOptionPartial: Bool? = nil
    var _bondNotes: String? = nil
    var _ineligibilityReasonList: [IBPBIneligibilityReason] = []
    var _eventContract1: String? = nil
    var _eventContractDescription1: String? = nil
    var _eventContractDescription2: String? = nil
    var _minAlgoSize: String? = nil
    var _lastPricePrecision: String? = nil
    var _lastSizePrecision: String? = nil
    var _settlementMethod: String? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _marketName = source._marketName
      _minTick = source._minTick
      _orderTypes = source._orderTypes
      _validExchanges = source._validExchanges
      _priceMagnifier = source._priceMagnifier
      _underConID = source._underConID
      _longName = source._longName
      _contractMonth = source._contractMonth
      _industry = source._industry
      _category = source._category
      _subcategory = source._subcategory
      _timeZoneID = source._timeZoneID
      _tradingHours = source._tradingHours
      _liquidHours = source._liquidHours
      _evRule = source._evRule
      _evMultiplier = source._evMultiplier
      _secIDList = source._secIDList
      _aggGroup = source._aggGroup
      _underSymbol = source._underSymbol
      _underSecType = source._underSecType
      _marketRuleIds = source._marketRuleIds
      _realExpirationDate = source._realExpirationDate
      _stockType = source._stockType
      _minSize = source._minSize
      _sizeIncrement = source._sizeIncrement
      _suggestedSizeIncrement = source._suggestedSizeIncrement
      _fundName = source._fundName
      _fundFamily = source._fundFamily
      _fundType = source._fundType
      _fundFrontLoad = source._fundFrontLoad
      _fundBackLoad = source._fundBackLoad
      _fundBackLoadTimeInterval = source._fundBackLoadTimeInterval
      _fundManagementFee = source._fundManagementFee
      _fundClosed = source._fundClosed
      _fundClosedForNewInvestors = source._fundClosedForNewInvestors
      _fundClosedForNewMoney = source._fundClosedForNewMoney
      _fundNotifyAmount = source._fundNotifyAmount
      _fundMinimumInitialPurchase = source._fundMinimumInitialPurchase
      _fundMinimumSubsequentPurchase = source._fundMinimumSubsequentPurchase
      _fundBlueSkyStates = source._fundBlueSkyStates
      _fundBlueSkyTerritories = source._fundBlueSkyTerritories
      _fundDistributionPolicyIndicator = source._fundDistributionPolicyIndicator
      _fundAssetType = source._fundAssetType
      _cusip = source._cusip
      _issueDate = source._issueDate
      _ratings = source._ratings
      _bondType = source._bondType
      _coupon = source._coupon
      _couponType = source._couponType
      _convertible = source._convertible
      _callable = source._callable
      _puttable = source._puttable
      _descAppend = source._descAppend
      _nextOptionDate = source._nextOptionDate
      _nextOptionType = source._nextOptionType
      _nextOptionPartial = source._nextOptionPartial
      _bondNotes = source._bondNotes
      _ineligibilityReasonList = source._ineligibilityReasonList
      _eventContract1 = source._eventContract1
      _eventContractDescription1 = source._eventContractDescription1
      _eventContractDescription2 = source._eventContractDescription2
      _minAlgoSize = source._minAlgoSize
      _lastPricePrecision = source._lastPricePrecision
      _lastSizePrecision = source._lastSizePrecision
      _settlementMethod = source._settlementMethod
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._marketName) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._minTick) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._orderTypes) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._validExchanges) }()
        case 5: try { try decoder.decodeSingularInt32Field(value: &_storage._priceMagnifier) }()
        case 6: try { try decoder.decodeSingularInt32Field(value: &_storage._underConID) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._longName) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._contractMonth) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._industry) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._category) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._subcategory) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._timeZoneID) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._tradingHours) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._liquidHours) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._evRule) }()
        case 16: try { try decoder.decodeSingularDoubleField(value: &_storage._evMultiplier) }()
        case 17: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._secIDList) }()
        case 18: try { try decoder.decodeSingularInt32Field(value: &_storage._aggGroup) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._underSymbol) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._underSecType) }()
        case 21: try { try decoder.decodeSingularStringField(value: &_storage._marketRuleIds) }()
        case 22: try { try decoder.decodeSingularStringField(value: &_storage._realExpirationDate) }()
        case 23: try { try decoder.decodeSingularStringField(value: &_storage._stockType) }()
        case 24: try { try decoder.decodeSingularStringField(value: &_storage._minSize) }()
        case 25: try { try decoder.decodeSingularStringField(value: &_storage._sizeIncrement) }()
        case 26: try { try decoder.decodeSingularStringField(value: &_storage._suggestedSizeIncrement) }()
        case 27: try { try decoder.decodeSingularStringField(value: &_storage._fundName) }()
        case 28: try { try decoder.decodeSingularStringField(value: &_storage._fundFamily) }()
        case 29: try { try decoder.decodeSingularStringField(value: &_storage._fundType) }()
        case 30: try { try decoder.decodeSingularStringField(value: &_storage._fundFrontLoad) }()
        case 31: try { try decoder.decodeSingularStringField(value: &_storage._fundBackLoad) }()
        case 32: try { try decoder.decodeSingularStringField(value: &_storage._fundBackLoadTimeInterval) }()
        case 33: try { try decoder.decodeSingularStringField(value: &_storage._fundManagementFee) }()
        case 34: try { try decoder.decodeSingularBoolField(value: &_storage._fundClosed) }()
        case 35: try { try decoder.decodeSingularBoolField(value: &_storage._fundClosedForNewInvestors) }()
        case 36: try { try decoder.decodeSingularBoolField(value: &_storage._fundClosedForNewMoney) }()
        case 37: try { try decoder.decodeSingularStringField(value: &_storage._fundNotifyAmount) }()
        case 38: try { try decoder.decodeSingularStringField(value: &_storage._fundMinimumInitialPurchase) }()
        case 39: try { try decoder.decodeSingularStringField(value: &_storage._fundMinimumSubsequentPurchase) }()
        case 40: try { try decoder.decodeSingularStringField(value: &_storage._fundBlueSkyStates) }()
        case 41: try { try decoder.decodeSingularStringField(value: &_storage._fundBlueSkyTerritories) }()
        case 42: try { try decoder.decodeSingularStringField(value: &_storage._fundDistributionPolicyIndicator) }()
        case 43: try { try decoder.decodeSingularStringField(value: &_storage._fundAssetType) }()
        case 44: try { try decoder.decodeSingularStringField(value: &_storage._cusip) }()
        case 45: try { try decoder.decodeSingularStringField(value: &_storage._issueDate) }()
        case 46: try { try decoder.decodeSingularStringField(value: &_storage._ratings) }()
        case 47: try { try decoder.decodeSingularStringField(value: &_storage._bondType) }()
        case 48: try { try decoder.decodeSingularDoubleField(value: &_storage._coupon) }()
        case 49: try { try decoder.decodeSingularStringField(value: &_storage._couponType) }()
        case 50: try { try decoder.decodeSingularBoolField(value: &_storage._convertible) }()
        case 51: try { try decoder.decodeSingularBoolField(value: &_storage._callable) }()
        case 52: try { try decoder.decodeSingularBoolField(value: &_storage._puttable) }()
        case 53: try { try decoder.decodeSingularStringField(value: &_storage._descAppend) }()
        case 54: try { try decoder.decodeSingularStringField(value: &_storage._nextOptionDate) }()
        case 55: try { try decoder.decodeSingularStringField(value: &_storage._nextOptionType) }()
        case 56: try { try decoder.decodeSingularBoolField(value: &_storage._nextOptionPartial) }()
        case 57: try { try decoder.decodeSingularStringField(value: &_storage._bondNotes) }()
        case 58: try { try decoder.decodeRepeatedMessageField(value: &_storage._ineligibilityReasonList) }()
        case 59: try { try decoder.decodeSingularStringField(value: &_storage._eventContract1) }()
        case 60: try { try decoder.decodeSingularStringField(value: &_storage._eventContractDescription1) }()
        case 61: try { try decoder.decodeSingularStringField(value: &_storage._eventContractDescription2) }()
        case 62: try { try decoder.decodeSingularStringField(value: &_storage._minAlgoSize) }()
        case 63: try { try decoder.decodeSingularStringField(value: &_storage._lastPricePrecision) }()
        case 64: try { try decoder.decodeSingularStringField(value: &_storage._lastSizePrecision) }()
        case 65: try { try decoder.decodeSingularStringField(value: &_storage._settlementMethod) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._marketName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._minTick {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._orderTypes {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._validExchanges {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._priceMagnifier {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._underConID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._longName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._contractMonth {
        try visitor.visitSingularStringField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._industry {
        try visitor.visitSingularStringField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._category {
        try visitor.visitSingularStringField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._subcategory {
        try visitor.visitSingularStringField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._timeZoneID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._tradingHours {
        try visitor.visitSingularStringField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._liquidHours {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._evRule {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._evMultiplier {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 16)
      } }()
      if !_storage._secIDList.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._secIDList, fieldNumber: 17)
      }
      try { if let v = _storage._aggGroup {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 18)
      } }()
      try { if let v = _storage._underSymbol {
        try visitor.visitSingularStringField(value: v, fieldNumber: 19)
      } }()
      try { if let v = _storage._underSecType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 20)
      } }()
      try { if let v = _storage._marketRuleIds {
        try visitor.visitSingularStringField(value: v, fieldNumber: 21)
      } }()
      try { if let v = _storage._realExpirationDate {
        try visitor.visitSingularStringField(value: v, fieldNumber: 22)
      } }()
      try { if let v = _storage._stockType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 23)
      } }()
      try { if let v = _storage._minSize {
        try visitor.visitSingularStringField(value: v, fieldNumber: 24)
      } }()
      try { if let v = _storage._sizeIncrement {
        try visitor.visitSingularStringField(value: v, fieldNumber: 25)
      } }()
      try { if let v = _storage._suggestedSizeIncrement {
        try visitor.visitSingularStringField(value: v, fieldNumber: 26)
      } }()
      try { if let v = _storage._fundName {
        try visitor.visitSingularStringField(value: v, fieldNumber: 27)
      } }()
      try { if let v = _storage._fundFamily {
        try visitor.visitSingularStringField(value: v, fieldNumber: 28)
      } }()
      try { if let v = _storage._fundType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 29)
      } }()
      try { if let v = _storage._fundFrontLoad {
        try visitor.visitSingularStringField(value: v, fieldNumber: 30)
      } }()
      try { if let v = _storage._fundBackLoad {
        try visitor.visitSingularStringField(value: v, fieldNumber: 31)
      } }()
      try { if let v = _storage._fundBackLoadTimeInterval {
        try visitor.visitSingularStringField(value: v, fieldNumber: 32)
      } }()
      try { if let v = _storage._fundManagementFee {
        try visitor.visitSingularStringField(value: v, fieldNumber: 33)
      } }()
      try { if let v = _storage._fundClosed {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 34)
      } }()
      try { if let v = _storage._fundClosedForNewInvestors {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 35)
      } }()
      try { if let v = _storage._fundClosedForNewMoney {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 36)
      } }()
      try { if let v = _storage._fundNotifyAmount {
        try visitor.visitSingularStringField(value: v, fieldNumber: 37)
      } }()
      try { if let v = _storage._fundMinimumInitialPurchase {
        try visitor.visitSingularStringField(value: v, fieldNumber: 38)
      } }()
      try { if let v = _storage._fundMinimumSubsequentPurchase {
        try visitor.visitSingularStringField(value: v, fieldNumber: 39)
      } }()
      try { if let v = _storage._fundBlueSkyStates {
        try visitor.visitSingularStringField(value: v, fieldNumber: 40)
      } }()
      try { if let v = _storage._fundBlueSkyTerritories {
        try visitor.visitSingularStringField(value: v, fieldNumber: 41)
      } }()
      try { if let v = _storage._fundDistributionPolicyIndicator {
        try visitor.visitSingularStringField(value: v, fieldNumber: 42)
      } }()
      try { if let v = _storage._fundAssetType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 43)
      } }()
      try { if let v = _storage._cusip {
        try visitor.visitSingularStringField(value: v, fieldNumber: 44)
      } }()
      try { if let v = _storage._issueDate {
        try visitor.visitSingularStringField(value: v, fieldNumber: 45)
      } }()
      try { if let v = _storage._ratings {
        try visitor.visitSingularStringField(value: v, fieldNumber: 46)
      } }()
      try { if let v = _storage._bondType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 47)
      } }()
      try { if let v = _storage._coupon {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 48)
      } }()
      try { if let v = _storage._couponType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 49)
      } }()
      try { if let v = _storage._convertible {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 50)
      } }()
      try { if let v = _storage._callable {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 51)
      } }()
      try { if let v = _storage._puttable {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 52)
      } }()
      try { if let v = _storage._descAppend {
        try visitor.visitSingularStringField(value: v, fieldNumber: 53)
      } }()
      try { if let v = _storage._nextOptionDate {
        try visitor.visitSingularStringField(value: v, fieldNumber: 54)
      } }()
      try { if let v = _storage._nextOptionType {
        try visitor.visitSingularStringField(value: v, fieldNumber: 55)
      } }()
      try { if let v = _storage._nextOptionPartial {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 56)
      } }()
      try { if let v = _storage._bondNotes {
        try visitor.visitSingularStringField(value: v, fieldNumber: 57)
      } }()
      if !_storage._ineligibilityReasonList.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._ineligibilityReasonList, fieldNumber: 58)
      }
      try { if let v = _storage._eventContract1 {
        try visitor.visitSingularStringField(value: v, fieldNumber: 59)
      } }()
      try { if let v = _storage._eventContractDescription1 {
        try visitor.visitSingularStringField(value: v, fieldNumber: 60)
      } }()
      try { if let v = _storage._eventContractDescription2 {
        try visitor.visitSingularStringField(value: v, fieldNumber: 61)
      } }()
      try { if let v = _storage._minAlgoSize {
        try visitor.visitSingularStringField(value: v, fieldNumber: 62)
      } }()
      try { if let v = _storage._lastPricePrecision {
        try visitor.visitSingularStringField(value: v, fieldNumber: 63)
      } }()
      try { if let v = _storage._lastSizePrecision {
        try visitor.visitSingularStringField(value: v, fieldNumber: 64)
      } }()
      try { if let v = _storage._settlementMethod {
        try visitor.visitSingularStringField(value: v, fieldNumber: 65)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBContractDetails, rhs: IBPBContractDetails) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._marketName != rhs_storage._marketName {return false}
        if _storage._minTick != rhs_storage._minTick {return false}
        if _storage._orderTypes != rhs_storage._orderTypes {return false}
        if _storage._validExchanges != rhs_storage._validExchanges {return false}
        if _storage._priceMagnifier != rhs_storage._priceMagnifier {return false}
        if _storage._underConID != rhs_storage._underConID {return false}
        if _storage._longName != rhs_storage._longName {return false}
        if _storage._contractMonth != rhs_storage._contractMonth {return false}
        if _storage._industry != rhs_storage._industry {return false}
        if _storage._category != rhs_storage._category {return false}
        if _storage._subcategory != rhs_storage._subcategory {return false}
        if _storage._timeZoneID != rhs_storage._timeZoneID {return false}
        if _storage._tradingHours != rhs_storage._tradingHours {return false}
        if _storage._liquidHours != rhs_storage._liquidHours {return false}
        if _storage._evRule != rhs_storage._evRule {return false}
        if _storage._evMultiplier != rhs_storage._evMultiplier {return false}
        if _storage._secIDList != rhs_storage._secIDList {return false}
        if _storage._aggGroup != rhs_storage._aggGroup {return false}
        if _storage._underSymbol != rhs_storage._underSymbol {return false}
        if _storage._underSecType != rhs_storage._underSecType {return false}
        if _storage._marketRuleIds != rhs_storage._marketRuleIds {return false}
        if _storage._realExpirationDate != rhs_storage._realExpirationDate {return false}
        if _storage._stockType != rhs_storage._stockType {return false}
        if _storage._minSize != rhs_storage._minSize {return false}
        if _storage._sizeIncrement != rhs_storage._sizeIncrement {return false}
        if _storage._suggestedSizeIncrement != rhs_storage._suggestedSizeIncrement {return false}
        if _storage._fundName != rhs_storage._fundName {return false}
        if _storage._fundFamily != rhs_storage._fundFamily {return false}
        if _storage._fundType != rhs_storage._fundType {return false}
        if _storage._fundFrontLoad != rhs_storage._fundFrontLoad {return false}
        if _storage._fundBackLoad != rhs_storage._fundBackLoad {return false}
        if _storage._fundBackLoadTimeInterval != rhs_storage._fundBackLoadTimeInterval {return false}
        if _storage._fundManagementFee != rhs_storage._fundManagementFee {return false}
        if _storage._fundClosed != rhs_storage._fundClosed {return false}
        if _storage._fundClosedForNewInvestors != rhs_storage._fundClosedForNewInvestors {return false}
        if _storage._fundClosedForNewMoney != rhs_storage._fundClosedForNewMoney {return false}
        if _storage._fundNotifyAmount != rhs_storage._fundNotifyAmount {return false}
        if _storage._fundMinimumInitialPurchase != rhs_storage._fundMinimumInitialPurchase {return false}
        if _storage._fundMinimumSubsequentPurchase != rhs_storage._fundMinimumSubsequentPurchase {return false}
        if _storage._fundBlueSkyStates != rhs_storage._fundBlueSkyStates {return false}
        if _storage._fundBlueSkyTerritories != rhs_storage._fundBlueSkyTerritories {return false}
        if _storage._fundDistributionPolicyIndicator != rhs_storage._fundDistributionPolicyIndicator {return false}
        if _storage._fundAssetType != rhs_storage._fundAssetType {return false}
        if _storage._cusip != rhs_storage._cusip {return false}
        if _storage._issueDate != rhs_storage._issueDate {return false}
        if _storage._ratings != rhs_storage._ratings {return false}
        if _storage._bondType != rhs_storage._bondType {return false}
        if _storage._coupon != rhs_storage._coupon {return false}
        if _storage._couponType != rhs_storage._couponType {return false}
        if _storage._convertible != rhs_storage._convertible {return false}
        if _storage._callable != rhs_storage._callable {return false}
        if _storage._puttable != rhs_storage._puttable {return false}
        if _storage._descAppend != rhs_storage._descAppend {return false}
        if _storage._nextOptionDate != rhs_storage._nextOptionDate {return false}
        if _storage._nextOptionType != rhs_storage._nextOptionType {return false}
        if _storage._nextOptionPartial != rhs_storage._nextOptionPartial {return false}
        if _storage._bondNotes != rhs_storage._bondNotes {return false}
        if _storage._ineligibilityReasonList != rhs_storage._ineligibilityReasonList {return false}
        if _storage._eventContract1 != rhs_storage._eventContract1 {return false}
        if _storage._eventContractDescription1 != rhs_storage._eventContractDescription1 {return false}
        if _storage._eventContractDescription2 != rhs_storage._eventContractDescription2 {return false}
        if _storage._minAlgoSize != rhs_storage._minAlgoSize {return false}
        if _storage._lastPricePrecision != rhs_storage._lastPricePrecision {return false}
        if _storage._lastSizePrecision != rhs_storage._lastSizePrecision {return false}
        if _storage._settlementMethod != rhs_storage._settlementMethod {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
