// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: DepthMarketDataDescription.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBDepthMarketDataDescription: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var exchange: String {
    get {_exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  public var secType: String {
    get {_secType ?? String()}
    set {_secType = newValue}
  }
  /// Returns true if `secType` has been explicitly set.
  public var hasSecType: Bool {self._secType != nil}
  /// Clears the value of `secType`. Subsequent reads from it will return its default value.
  public mutating func clearSecType() {self._secType = nil}

  public var listingExch: String {
    get {_listingExch ?? String()}
    set {_listingExch = newValue}
  }
  /// Returns true if `listingExch` has been explicitly set.
  public var hasListingExch: Bool {self._listingExch != nil}
  /// Clears the value of `listingExch`. Subsequent reads from it will return its default value.
  public mutating func clearListingExch() {self._listingExch = nil}

  public var serviceDataType: String {
    get {_serviceDataType ?? String()}
    set {_serviceDataType = newValue}
  }
  /// Returns true if `serviceDataType` has been explicitly set.
  public var hasServiceDataType: Bool {self._serviceDataType != nil}
  /// Clears the value of `serviceDataType`. Subsequent reads from it will return its default value.
  public mutating func clearServiceDataType() {self._serviceDataType = nil}

  public var aggGroup: Int32 {
    get {_aggGroup ?? 0}
    set {_aggGroup = newValue}
  }
  /// Returns true if `aggGroup` has been explicitly set.
  public var hasAggGroup: Bool {self._aggGroup != nil}
  /// Clears the value of `aggGroup`. Subsequent reads from it will return its default value.
  public mutating func clearAggGroup() {self._aggGroup = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _exchange: String? = nil
  fileprivate var _secType: String? = nil
  fileprivate var _listingExch: String? = nil
  fileprivate var _serviceDataType: String? = nil
  fileprivate var _aggGroup: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBDepthMarketDataDescription: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DepthMarketDataDescription"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}exchange\0\u{1}secType\0\u{1}listingExch\0\u{1}serviceDataType\0\u{1}aggGroup\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._exchange) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._secType) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._listingExch) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._serviceDataType) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._aggGroup) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._secType {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._listingExch {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._serviceDataType {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._aggGroup {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBDepthMarketDataDescription, rhs: IBPBDepthMarketDataDescription) -> Bool {
    if lhs._exchange != rhs._exchange {return false}
    if lhs._secType != rhs._secType {return false}
    if lhs._listingExch != rhs._listingExch {return false}
    if lhs._serviceDataType != rhs._serviceDataType {return false}
    if lhs._aggGroup != rhs._aggGroup {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
