// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ErrorMessage.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBErrorMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Int32 {
    get {_id ?? 0}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {self._id = nil}

  public var errorTime: Int64 {
    get {_errorTime ?? 0}
    set {_errorTime = newValue}
  }
  /// Returns true if `errorTime` has been explicitly set.
  public var hasErrorTime: Bool {self._errorTime != nil}
  /// Clears the value of `errorTime`. Subsequent reads from it will return its default value.
  public mutating func clearErrorTime() {self._errorTime = nil}

  public var errorCode: Int32 {
    get {_errorCode ?? 0}
    set {_errorCode = newValue}
  }
  /// Returns true if `errorCode` has been explicitly set.
  public var hasErrorCode: Bool {self._errorCode != nil}
  /// Clears the value of `errorCode`. Subsequent reads from it will return its default value.
  public mutating func clearErrorCode() {self._errorCode = nil}

  public var errorMsg: String {
    get {_errorMsg ?? String()}
    set {_errorMsg = newValue}
  }
  /// Returns true if `errorMsg` has been explicitly set.
  public var hasErrorMsg: Bool {self._errorMsg != nil}
  /// Clears the value of `errorMsg`. Subsequent reads from it will return its default value.
  public mutating func clearErrorMsg() {self._errorMsg = nil}

  public var advancedOrderRejectJson: String {
    get {_advancedOrderRejectJson ?? String()}
    set {_advancedOrderRejectJson = newValue}
  }
  /// Returns true if `advancedOrderRejectJson` has been explicitly set.
  public var hasAdvancedOrderRejectJson: Bool {self._advancedOrderRejectJson != nil}
  /// Clears the value of `advancedOrderRejectJson`. Subsequent reads from it will return its default value.
  public mutating func clearAdvancedOrderRejectJson() {self._advancedOrderRejectJson = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _id: Int32? = nil
  fileprivate var _errorTime: Int64? = nil
  fileprivate var _errorCode: Int32? = nil
  fileprivate var _errorMsg: String? = nil
  fileprivate var _advancedOrderRejectJson: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBErrorMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ErrorMessage"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}errorTime\0\u{1}errorCode\0\u{1}errorMsg\0\u{1}advancedOrderRejectJson\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._id) }()
      case 2: try { try decoder.decodeSingularInt64Field(value: &self._errorTime) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._errorCode) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._errorMsg) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._advancedOrderRejectJson) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._errorTime {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._errorCode {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._errorMsg {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._advancedOrderRejectJson {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBErrorMessage, rhs: IBPBErrorMessage) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._errorTime != rhs._errorTime {return false}
    if lhs._errorCode != rhs._errorCode {return false}
    if lhs._errorMsg != rhs._errorMsg {return false}
    if lhs._advancedOrderRejectJson != rhs._advancedOrderRejectJson {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
