// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ExecutionFilter.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBExecutionFilter: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var clientID: Int32 {
    get {_clientID ?? 0}
    set {_clientID = newValue}
  }
  /// Returns true if `clientID` has been explicitly set.
  public var hasClientID: Bool {self._clientID != nil}
  /// Clears the value of `clientID`. Subsequent reads from it will return its default value.
  public mutating func clearClientID() {self._clientID = nil}

  public var acctCode: String {
    get {_acctCode ?? String()}
    set {_acctCode = newValue}
  }
  /// Returns true if `acctCode` has been explicitly set.
  public var hasAcctCode: Bool {self._acctCode != nil}
  /// Clears the value of `acctCode`. Subsequent reads from it will return its default value.
  public mutating func clearAcctCode() {self._acctCode = nil}

  public var time: String {
    get {_time ?? String()}
    set {_time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  public var hasTime: Bool {self._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  public mutating func clearTime() {self._time = nil}

  public var symbol: String {
    get {_symbol ?? String()}
    set {_symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {self._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {self._symbol = nil}

  public var secType: String {
    get {_secType ?? String()}
    set {_secType = newValue}
  }
  /// Returns true if `secType` has been explicitly set.
  public var hasSecType: Bool {self._secType != nil}
  /// Clears the value of `secType`. Subsequent reads from it will return its default value.
  public mutating func clearSecType() {self._secType = nil}

  public var exchange: String {
    get {_exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  public var side: String {
    get {_side ?? String()}
    set {_side = newValue}
  }
  /// Returns true if `side` has been explicitly set.
  public var hasSide: Bool {self._side != nil}
  /// Clears the value of `side`. Subsequent reads from it will return its default value.
  public mutating func clearSide() {self._side = nil}

  public var lastNdays: Int32 {
    get {_lastNdays ?? 0}
    set {_lastNdays = newValue}
  }
  /// Returns true if `lastNdays` has been explicitly set.
  public var hasLastNdays: Bool {self._lastNdays != nil}
  /// Clears the value of `lastNdays`. Subsequent reads from it will return its default value.
  public mutating func clearLastNdays() {self._lastNdays = nil}

  public var specificDates: [Int32] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _clientID: Int32? = nil
  fileprivate var _acctCode: String? = nil
  fileprivate var _time: String? = nil
  fileprivate var _symbol: String? = nil
  fileprivate var _secType: String? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _side: String? = nil
  fileprivate var _lastNdays: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBExecutionFilter: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ExecutionFilter"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}clientId\0\u{1}acctCode\0\u{1}time\0\u{1}symbol\0\u{1}secType\0\u{1}exchange\0\u{1}side\0\u{1}lastNDays\0\u{1}specificDates\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._clientID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._acctCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._time) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._symbol) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._secType) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._exchange) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._side) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._lastNdays) }()
      case 9: try { try decoder.decodeRepeatedInt32Field(value: &self.specificDates) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._clientID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._acctCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._time {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._symbol {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._secType {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._side {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._lastNdays {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    if !self.specificDates.isEmpty {
      try visitor.visitPackedInt32Field(value: self.specificDates, fieldNumber: 9)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBExecutionFilter, rhs: IBPBExecutionFilter) -> Bool {
    if lhs._clientID != rhs._clientID {return false}
    if lhs._acctCode != rhs._acctCode {return false}
    if lhs._time != rhs._time {return false}
    if lhs._symbol != rhs._symbol {return false}
    if lhs._secType != rhs._secType {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._side != rhs._side {return false}
    if lhs._lastNdays != rhs._lastNdays {return false}
    if lhs.specificDates != rhs.specificDates {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
