// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: Execution.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBExecution: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var orderID: Int32 {
    get {_storage._orderID ?? 0}
    set {_uniqueStorage()._orderID = newValue}
  }
  /// Returns true if `orderID` has been explicitly set.
  public var hasOrderID: Bool {_storage._orderID != nil}
  /// Clears the value of `orderID`. Subsequent reads from it will return its default value.
  public mutating func clearOrderID() {_uniqueStorage()._orderID = nil}

  public var execID: String {
    get {_storage._execID ?? String()}
    set {_uniqueStorage()._execID = newValue}
  }
  /// Returns true if `execID` has been explicitly set.
  public var hasExecID: Bool {_storage._execID != nil}
  /// Clears the value of `execID`. Subsequent reads from it will return its default value.
  public mutating func clearExecID() {_uniqueStorage()._execID = nil}

  public var time: String {
    get {_storage._time ?? String()}
    set {_uniqueStorage()._time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  public var hasTime: Bool {_storage._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  public mutating func clearTime() {_uniqueStorage()._time = nil}

  public var acctNumber: String {
    get {_storage._acctNumber ?? String()}
    set {_uniqueStorage()._acctNumber = newValue}
  }
  /// Returns true if `acctNumber` has been explicitly set.
  public var hasAcctNumber: Bool {_storage._acctNumber != nil}
  /// Clears the value of `acctNumber`. Subsequent reads from it will return its default value.
  public mutating func clearAcctNumber() {_uniqueStorage()._acctNumber = nil}

  public var exchange: String {
    get {_storage._exchange ?? String()}
    set {_uniqueStorage()._exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {_storage._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {_uniqueStorage()._exchange = nil}

  public var side: String {
    get {_storage._side ?? String()}
    set {_uniqueStorage()._side = newValue}
  }
  /// Returns true if `side` has been explicitly set.
  public var hasSide: Bool {_storage._side != nil}
  /// Clears the value of `side`. Subsequent reads from it will return its default value.
  public mutating func clearSide() {_uniqueStorage()._side = nil}

  public var shares: String {
    get {_storage._shares ?? String()}
    set {_uniqueStorage()._shares = newValue}
  }
  /// Returns true if `shares` has been explicitly set.
  public var hasShares: Bool {_storage._shares != nil}
  /// Clears the value of `shares`. Subsequent reads from it will return its default value.
  public mutating func clearShares() {_uniqueStorage()._shares = nil}

  public var price: Double {
    get {_storage._price ?? 0}
    set {_uniqueStorage()._price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {_storage._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {_uniqueStorage()._price = nil}

  public var permID: Int64 {
    get {_storage._permID ?? 0}
    set {_uniqueStorage()._permID = newValue}
  }
  /// Returns true if `permID` has been explicitly set.
  public var hasPermID: Bool {_storage._permID != nil}
  /// Clears the value of `permID`. Subsequent reads from it will return its default value.
  public mutating func clearPermID() {_uniqueStorage()._permID = nil}

  public var clientID: Int32 {
    get {_storage._clientID ?? 0}
    set {_uniqueStorage()._clientID = newValue}
  }
  /// Returns true if `clientID` has been explicitly set.
  public var hasClientID: Bool {_storage._clientID != nil}
  /// Clears the value of `clientID`. Subsequent reads from it will return its default value.
  public mutating func clearClientID() {_uniqueStorage()._clientID = nil}

  public var isLiquidation: Bool {
    get {_storage._isLiquidation ?? false}
    set {_uniqueStorage()._isLiquidation = newValue}
  }
  /// Returns true if `isLiquidation` has been explicitly set.
  public var hasIsLiquidation: Bool {_storage._isLiquidation != nil}
  /// Clears the value of `isLiquidation`. Subsequent reads from it will return its default value.
  public mutating func clearIsLiquidation() {_uniqueStorage()._isLiquidation = nil}

  public var cumQty: String {
    get {_storage._cumQty ?? String()}
    set {_uniqueStorage()._cumQty = newValue}
  }
  /// Returns true if `cumQty` has been explicitly set.
  public var hasCumQty: Bool {_storage._cumQty != nil}
  /// Clears the value of `cumQty`. Subsequent reads from it will return its default value.
  public mutating func clearCumQty() {_uniqueStorage()._cumQty = nil}

  public var avgPrice: Double {
    get {_storage._avgPrice ?? 0}
    set {_uniqueStorage()._avgPrice = newValue}
  }
  /// Returns true if `avgPrice` has been explicitly set.
  public var hasAvgPrice: Bool {_storage._avgPrice != nil}
  /// Clears the value of `avgPrice`. Subsequent reads from it will return its default value.
  public mutating func clearAvgPrice() {_uniqueStorage()._avgPrice = nil}

  public var orderRef: String {
    get {_storage._orderRef ?? String()}
    set {_uniqueStorage()._orderRef = newValue}
  }
  /// Returns true if `orderRef` has been explicitly set.
  public var hasOrderRef: Bool {_storage._orderRef != nil}
  /// Clears the value of `orderRef`. Subsequent reads from it will return its default value.
  public mutating func clearOrderRef() {_uniqueStorage()._orderRef = nil}

  public var evRule: String {
    get {_storage._evRule ?? String()}
    set {_uniqueStorage()._evRule = newValue}
  }
  /// Returns true if `evRule` has been explicitly set.
  public var hasEvRule: Bool {_storage._evRule != nil}
  /// Clears the value of `evRule`. Subsequent reads from it will return its default value.
  public mutating func clearEvRule() {_uniqueStorage()._evRule = nil}

  public var evMultiplier: Double {
    get {_storage._evMultiplier ?? 0}
    set {_uniqueStorage()._evMultiplier = newValue}
  }
  /// Returns true if `evMultiplier` has been explicitly set.
  public var hasEvMultiplier: Bool {_storage._evMultiplier != nil}
  /// Clears the value of `evMultiplier`. Subsequent reads from it will return its default value.
  public mutating func clearEvMultiplier() {_uniqueStorage()._evMultiplier = nil}

  public var modelCode: String {
    get {_storage._modelCode ?? String()}
    set {_uniqueStorage()._modelCode = newValue}
  }
  /// Returns true if `modelCode` has been explicitly set.
  public var hasModelCode: Bool {_storage._modelCode != nil}
  /// Clears the value of `modelCode`. Subsequent reads from it will return its default value.
  public mutating func clearModelCode() {_uniqueStorage()._modelCode = nil}

  public var lastLiquidity: Int32 {
    get {_storage._lastLiquidity ?? 0}
    set {_uniqueStorage()._lastLiquidity = newValue}
  }
  /// Returns true if `lastLiquidity` has been explicitly set.
  public var hasLastLiquidity: Bool {_storage._lastLiquidity != nil}
  /// Clears the value of `lastLiquidity`. Subsequent reads from it will return its default value.
  public mutating func clearLastLiquidity() {_uniqueStorage()._lastLiquidity = nil}

  public var isPriceRevisionPending: Bool {
    get {_storage._isPriceRevisionPending ?? false}
    set {_uniqueStorage()._isPriceRevisionPending = newValue}
  }
  /// Returns true if `isPriceRevisionPending` has been explicitly set.
  public var hasIsPriceRevisionPending: Bool {_storage._isPriceRevisionPending != nil}
  /// Clears the value of `isPriceRevisionPending`. Subsequent reads from it will return its default value.
  public mutating func clearIsPriceRevisionPending() {_uniqueStorage()._isPriceRevisionPending = nil}

  public var submitter: String {
    get {_storage._submitter ?? String()}
    set {_uniqueStorage()._submitter = newValue}
  }
  /// Returns true if `submitter` has been explicitly set.
  public var hasSubmitter: Bool {_storage._submitter != nil}
  /// Clears the value of `submitter`. Subsequent reads from it will return its default value.
  public mutating func clearSubmitter() {_uniqueStorage()._submitter = nil}

  public var optExerciseOrLapseType: Int32 {
    get {_storage._optExerciseOrLapseType ?? 0}
    set {_uniqueStorage()._optExerciseOrLapseType = newValue}
  }
  /// Returns true if `optExerciseOrLapseType` has been explicitly set.
  public var hasOptExerciseOrLapseType: Bool {_storage._optExerciseOrLapseType != nil}
  /// Clears the value of `optExerciseOrLapseType`. Subsequent reads from it will return its default value.
  public mutating func clearOptExerciseOrLapseType() {_uniqueStorage()._optExerciseOrLapseType = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBExecution: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".Execution"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}orderId\0\u{1}execId\0\u{1}time\0\u{1}acctNumber\0\u{1}exchange\0\u{1}side\0\u{1}shares\0\u{1}price\0\u{1}permId\0\u{1}clientId\0\u{1}isLiquidation\0\u{1}cumQty\0\u{1}avgPrice\0\u{1}orderRef\0\u{1}evRule\0\u{1}evMultiplier\0\u{1}modelCode\0\u{1}lastLiquidity\0\u{1}isPriceRevisionPending\0\u{1}submitter\0\u{1}optExerciseOrLapseType\0")

  fileprivate class _StorageClass {
    var _orderID: Int32? = nil
    var _execID: String? = nil
    var _time: String? = nil
    var _acctNumber: String? = nil
    var _exchange: String? = nil
    var _side: String? = nil
    var _shares: String? = nil
    var _price: Double? = nil
    var _permID: Int64? = nil
    var _clientID: Int32? = nil
    var _isLiquidation: Bool? = nil
    var _cumQty: String? = nil
    var _avgPrice: Double? = nil
    var _orderRef: String? = nil
    var _evRule: String? = nil
    var _evMultiplier: Double? = nil
    var _modelCode: String? = nil
    var _lastLiquidity: Int32? = nil
    var _isPriceRevisionPending: Bool? = nil
    var _submitter: String? = nil
    var _optExerciseOrLapseType: Int32? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _orderID = source._orderID
      _execID = source._execID
      _time = source._time
      _acctNumber = source._acctNumber
      _exchange = source._exchange
      _side = source._side
      _shares = source._shares
      _price = source._price
      _permID = source._permID
      _clientID = source._clientID
      _isLiquidation = source._isLiquidation
      _cumQty = source._cumQty
      _avgPrice = source._avgPrice
      _orderRef = source._orderRef
      _evRule = source._evRule
      _evMultiplier = source._evMultiplier
      _modelCode = source._modelCode
      _lastLiquidity = source._lastLiquidity
      _isPriceRevisionPending = source._isPriceRevisionPending
      _submitter = source._submitter
      _optExerciseOrLapseType = source._optExerciseOrLapseType
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._orderID) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._execID) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._time) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._acctNumber) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._exchange) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._side) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._shares) }()
        case 8: try { try decoder.decodeSingularDoubleField(value: &_storage._price) }()
        case 9: try { try decoder.decodeSingularInt64Field(value: &_storage._permID) }()
        case 10: try { try decoder.decodeSingularInt32Field(value: &_storage._clientID) }()
        case 11: try { try decoder.decodeSingularBoolField(value: &_storage._isLiquidation) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._cumQty) }()
        case 13: try { try decoder.decodeSingularDoubleField(value: &_storage._avgPrice) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._orderRef) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._evRule) }()
        case 16: try { try decoder.decodeSingularDoubleField(value: &_storage._evMultiplier) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._modelCode) }()
        case 18: try { try decoder.decodeSingularInt32Field(value: &_storage._lastLiquidity) }()
        case 19: try { try decoder.decodeSingularBoolField(value: &_storage._isPriceRevisionPending) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._submitter) }()
        case 21: try { try decoder.decodeSingularInt32Field(value: &_storage._optExerciseOrLapseType) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._orderID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._execID {
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._time {
        try visitor.visitSingularStringField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._acctNumber {
        try visitor.visitSingularStringField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._exchange {
        try visitor.visitSingularStringField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._side {
        try visitor.visitSingularStringField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._shares {
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._price {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._permID {
        try visitor.visitSingularInt64Field(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._clientID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._isLiquidation {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._cumQty {
        try visitor.visitSingularStringField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._avgPrice {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._orderRef {
        try visitor.visitSingularStringField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._evRule {
        try visitor.visitSingularStringField(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._evMultiplier {
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 16)
      } }()
      try { if let v = _storage._modelCode {
        try visitor.visitSingularStringField(value: v, fieldNumber: 17)
      } }()
      try { if let v = _storage._lastLiquidity {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 18)
      } }()
      try { if let v = _storage._isPriceRevisionPending {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 19)
      } }()
      try { if let v = _storage._submitter {
        try visitor.visitSingularStringField(value: v, fieldNumber: 20)
      } }()
      try { if let v = _storage._optExerciseOrLapseType {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 21)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBExecution, rhs: IBPBExecution) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._orderID != rhs_storage._orderID {return false}
        if _storage._execID != rhs_storage._execID {return false}
        if _storage._time != rhs_storage._time {return false}
        if _storage._acctNumber != rhs_storage._acctNumber {return false}
        if _storage._exchange != rhs_storage._exchange {return false}
        if _storage._side != rhs_storage._side {return false}
        if _storage._shares != rhs_storage._shares {return false}
        if _storage._price != rhs_storage._price {return false}
        if _storage._permID != rhs_storage._permID {return false}
        if _storage._clientID != rhs_storage._clientID {return false}
        if _storage._isLiquidation != rhs_storage._isLiquidation {return false}
        if _storage._cumQty != rhs_storage._cumQty {return false}
        if _storage._avgPrice != rhs_storage._avgPrice {return false}
        if _storage._orderRef != rhs_storage._orderRef {return false}
        if _storage._evRule != rhs_storage._evRule {return false}
        if _storage._evMultiplier != rhs_storage._evMultiplier {return false}
        if _storage._modelCode != rhs_storage._modelCode {return false}
        if _storage._lastLiquidity != rhs_storage._lastLiquidity {return false}
        if _storage._isPriceRevisionPending != rhs_storage._isPriceRevisionPending {return false}
        if _storage._submitter != rhs_storage._submitter {return false}
        if _storage._optExerciseOrLapseType != rhs_storage._optExerciseOrLapseType {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
