// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ExerciseOptionsRequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBExerciseOptionsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var orderID: Int32 {
    get {_orderID ?? 0}
    set {_orderID = newValue}
  }
  /// Returns true if `orderID` has been explicitly set.
  public var hasOrderID: Bool {self._orderID != nil}
  /// Clears the value of `orderID`. Subsequent reads from it will return its default value.
  public mutating func clearOrderID() {self._orderID = nil}

  public var contract: IBPBContract {
    get {_contract ?? IBPBContract()}
    set {_contract = newValue}
  }
  /// Returns true if `contract` has been explicitly set.
  public var hasContract: Bool {self._contract != nil}
  /// Clears the value of `contract`. Subsequent reads from it will return its default value.
  public mutating func clearContract() {self._contract = nil}

  public var exerciseAction: Int32 {
    get {_exerciseAction ?? 0}
    set {_exerciseAction = newValue}
  }
  /// Returns true if `exerciseAction` has been explicitly set.
  public var hasExerciseAction: Bool {self._exerciseAction != nil}
  /// Clears the value of `exerciseAction`. Subsequent reads from it will return its default value.
  public mutating func clearExerciseAction() {self._exerciseAction = nil}

  public var exerciseQuantity: Int32 {
    get {_exerciseQuantity ?? 0}
    set {_exerciseQuantity = newValue}
  }
  /// Returns true if `exerciseQuantity` has been explicitly set.
  public var hasExerciseQuantity: Bool {self._exerciseQuantity != nil}
  /// Clears the value of `exerciseQuantity`. Subsequent reads from it will return its default value.
  public mutating func clearExerciseQuantity() {self._exerciseQuantity = nil}

  public var account: String {
    get {_account ?? String()}
    set {_account = newValue}
  }
  /// Returns true if `account` has been explicitly set.
  public var hasAccount: Bool {self._account != nil}
  /// Clears the value of `account`. Subsequent reads from it will return its default value.
  public mutating func clearAccount() {self._account = nil}

  public var override: Bool {
    get {_override ?? false}
    set {_override = newValue}
  }
  /// Returns true if `override` has been explicitly set.
  public var hasOverride: Bool {self._override != nil}
  /// Clears the value of `override`. Subsequent reads from it will return its default value.
  public mutating func clearOverride() {self._override = nil}

  public var manualOrderTime: String {
    get {_manualOrderTime ?? String()}
    set {_manualOrderTime = newValue}
  }
  /// Returns true if `manualOrderTime` has been explicitly set.
  public var hasManualOrderTime: Bool {self._manualOrderTime != nil}
  /// Clears the value of `manualOrderTime`. Subsequent reads from it will return its default value.
  public mutating func clearManualOrderTime() {self._manualOrderTime = nil}

  public var customerAccount: String {
    get {_customerAccount ?? String()}
    set {_customerAccount = newValue}
  }
  /// Returns true if `customerAccount` has been explicitly set.
  public var hasCustomerAccount: Bool {self._customerAccount != nil}
  /// Clears the value of `customerAccount`. Subsequent reads from it will return its default value.
  public mutating func clearCustomerAccount() {self._customerAccount = nil}

  public var professionalCustomer: Bool {
    get {_professionalCustomer ?? false}
    set {_professionalCustomer = newValue}
  }
  /// Returns true if `professionalCustomer` has been explicitly set.
  public var hasProfessionalCustomer: Bool {self._professionalCustomer != nil}
  /// Clears the value of `professionalCustomer`. Subsequent reads from it will return its default value.
  public mutating func clearProfessionalCustomer() {self._professionalCustomer = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _orderID: Int32? = nil
  fileprivate var _contract: IBPBContract? = nil
  fileprivate var _exerciseAction: Int32? = nil
  fileprivate var _exerciseQuantity: Int32? = nil
  fileprivate var _account: String? = nil
  fileprivate var _override: Bool? = nil
  fileprivate var _manualOrderTime: String? = nil
  fileprivate var _customerAccount: String? = nil
  fileprivate var _professionalCustomer: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBExerciseOptionsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ExerciseOptionsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}orderId\0\u{1}contract\0\u{1}exerciseAction\0\u{1}exerciseQuantity\0\u{1}account\0\u{1}override\0\u{1}manualOrderTime\0\u{1}customerAccount\0\u{1}professionalCustomer\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._orderID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._contract) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._exerciseAction) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._exerciseQuantity) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._account) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._override) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._manualOrderTime) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._customerAccount) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._professionalCustomer) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._orderID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._contract {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._exerciseAction {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._exerciseQuantity {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._account {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._override {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._manualOrderTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._customerAccount {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._professionalCustomer {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBExerciseOptionsRequest, rhs: IBPBExerciseOptionsRequest) -> Bool {
    if lhs._orderID != rhs._orderID {return false}
    if lhs._contract != rhs._contract {return false}
    if lhs._exerciseAction != rhs._exerciseAction {return false}
    if lhs._exerciseQuantity != rhs._exerciseQuantity {return false}
    if lhs._account != rhs._account {return false}
    if lhs._override != rhs._override {return false}
    if lhs._manualOrderTime != rhs._manualOrderTime {return false}
    if lhs._customerAccount != rhs._customerAccount {return false}
    if lhs._professionalCustomer != rhs._professionalCustomer {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
