// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: HistoricalTickLast.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBHistoricalTickLast: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var time: Int64 {
    get {_time ?? 0}
    set {_time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  public var hasTime: Bool {self._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  public mutating func clearTime() {self._time = nil}

  public var tickAttribLast: IBPBTickAttribLast {
    get {_tickAttribLast ?? IBPBTickAttribLast()}
    set {_tickAttribLast = newValue}
  }
  /// Returns true if `tickAttribLast` has been explicitly set.
  public var hasTickAttribLast: Bool {self._tickAttribLast != nil}
  /// Clears the value of `tickAttribLast`. Subsequent reads from it will return its default value.
  public mutating func clearTickAttribLast() {self._tickAttribLast = nil}

  public var price: Double {
    get {_price ?? 0}
    set {_price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {self._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {self._price = nil}

  public var size: String {
    get {_size ?? String()}
    set {_size = newValue}
  }
  /// Returns true if `size` has been explicitly set.
  public var hasSize: Bool {self._size != nil}
  /// Clears the value of `size`. Subsequent reads from it will return its default value.
  public mutating func clearSize() {self._size = nil}

  public var exchange: String {
    get {_exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  public var specialConditions: String {
    get {_specialConditions ?? String()}
    set {_specialConditions = newValue}
  }
  /// Returns true if `specialConditions` has been explicitly set.
  public var hasSpecialConditions: Bool {self._specialConditions != nil}
  /// Clears the value of `specialConditions`. Subsequent reads from it will return its default value.
  public mutating func clearSpecialConditions() {self._specialConditions = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _time: Int64? = nil
  fileprivate var _tickAttribLast: IBPBTickAttribLast? = nil
  fileprivate var _price: Double? = nil
  fileprivate var _size: String? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _specialConditions: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBHistoricalTickLast: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HistoricalTickLast"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}time\0\u{1}tickAttribLast\0\u{1}price\0\u{1}size\0\u{1}exchange\0\u{1}specialConditions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt64Field(value: &self._time) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._tickAttribLast) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self._price) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._size) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._exchange) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._specialConditions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._time {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._tickAttribLast {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._price {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._size {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._specialConditions {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBHistoricalTickLast, rhs: IBPBHistoricalTickLast) -> Bool {
    if lhs._time != rhs._time {return false}
    if lhs._tickAttribLast != rhs._tickAttribLast {return false}
    if lhs._price != rhs._price {return false}
    if lhs._size != rhs._size {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._specialConditions != rhs._specialConditions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
