// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: HistoricalDataRequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBHistoricalDataRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var contract: IBPBContract {
    get {_contract ?? IBPBContract()}
    set {_contract = newValue}
  }
  /// Returns true if `contract` has been explicitly set.
  public var hasContract: Bool {self._contract != nil}
  /// Clears the value of `contract`. Subsequent reads from it will return its default value.
  public mutating func clearContract() {self._contract = nil}

  public var endDateTime: String {
    get {_endDateTime ?? String()}
    set {_endDateTime = newValue}
  }
  /// Returns true if `endDateTime` has been explicitly set.
  public var hasEndDateTime: Bool {self._endDateTime != nil}
  /// Clears the value of `endDateTime`. Subsequent reads from it will return its default value.
  public mutating func clearEndDateTime() {self._endDateTime = nil}

  public var barSizeSetting: String {
    get {_barSizeSetting ?? String()}
    set {_barSizeSetting = newValue}
  }
  /// Returns true if `barSizeSetting` has been explicitly set.
  public var hasBarSizeSetting: Bool {self._barSizeSetting != nil}
  /// Clears the value of `barSizeSetting`. Subsequent reads from it will return its default value.
  public mutating func clearBarSizeSetting() {self._barSizeSetting = nil}

  public var duration: String {
    get {_duration ?? String()}
    set {_duration = newValue}
  }
  /// Returns true if `duration` has been explicitly set.
  public var hasDuration: Bool {self._duration != nil}
  /// Clears the value of `duration`. Subsequent reads from it will return its default value.
  public mutating func clearDuration() {self._duration = nil}

  public var useRth: Bool {
    get {_useRth ?? false}
    set {_useRth = newValue}
  }
  /// Returns true if `useRth` has been explicitly set.
  public var hasUseRth: Bool {self._useRth != nil}
  /// Clears the value of `useRth`. Subsequent reads from it will return its default value.
  public mutating func clearUseRth() {self._useRth = nil}

  public var whatToShow: String {
    get {_whatToShow ?? String()}
    set {_whatToShow = newValue}
  }
  /// Returns true if `whatToShow` has been explicitly set.
  public var hasWhatToShow: Bool {self._whatToShow != nil}
  /// Clears the value of `whatToShow`. Subsequent reads from it will return its default value.
  public mutating func clearWhatToShow() {self._whatToShow = nil}

  public var formatDate: Int32 {
    get {_formatDate ?? 0}
    set {_formatDate = newValue}
  }
  /// Returns true if `formatDate` has been explicitly set.
  public var hasFormatDate: Bool {self._formatDate != nil}
  /// Clears the value of `formatDate`. Subsequent reads from it will return its default value.
  public mutating func clearFormatDate() {self._formatDate = nil}

  public var keepUpToDate: Bool {
    get {_keepUpToDate ?? false}
    set {_keepUpToDate = newValue}
  }
  /// Returns true if `keepUpToDate` has been explicitly set.
  public var hasKeepUpToDate: Bool {self._keepUpToDate != nil}
  /// Clears the value of `keepUpToDate`. Subsequent reads from it will return its default value.
  public mutating func clearKeepUpToDate() {self._keepUpToDate = nil}

  public var chartOptions: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _contract: IBPBContract? = nil
  fileprivate var _endDateTime: String? = nil
  fileprivate var _barSizeSetting: String? = nil
  fileprivate var _duration: String? = nil
  fileprivate var _useRth: Bool? = nil
  fileprivate var _whatToShow: String? = nil
  fileprivate var _formatDate: Int32? = nil
  fileprivate var _keepUpToDate: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBHistoricalDataRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HistoricalDataRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}contract\0\u{1}endDateTime\0\u{1}barSizeSetting\0\u{1}duration\0\u{1}useRTH\0\u{1}whatToShow\0\u{1}formatDate\0\u{1}keepUpToDate\0\u{1}chartOptions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._contract) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._endDateTime) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._barSizeSetting) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._duration) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._useRth) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._whatToShow) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._formatDate) }()
      case 9: try { try decoder.decodeSingularBoolField(value: &self._keepUpToDate) }()
      case 10: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.chartOptions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._contract {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._endDateTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._barSizeSetting {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._duration {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._useRth {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._whatToShow {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._formatDate {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._keepUpToDate {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 9)
    } }()
    if !self.chartOptions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.chartOptions, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBHistoricalDataRequest, rhs: IBPBHistoricalDataRequest) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._contract != rhs._contract {return false}
    if lhs._endDateTime != rhs._endDateTime {return false}
    if lhs._barSizeSetting != rhs._barSizeSetting {return false}
    if lhs._duration != rhs._duration {return false}
    if lhs._useRth != rhs._useRth {return false}
    if lhs._whatToShow != rhs._whatToShow {return false}
    if lhs._formatDate != rhs._formatDate {return false}
    if lhs._keepUpToDate != rhs._keepUpToDate {return false}
    if lhs.chartOptions != rhs.chartOptions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
