// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: HistoricalNewsRequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBHistoricalNewsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var conID: Int32 {
    get {_conID ?? 0}
    set {_conID = newValue}
  }
  /// Returns true if `conID` has been explicitly set.
  public var hasConID: Bool {self._conID != nil}
  /// Clears the value of `conID`. Subsequent reads from it will return its default value.
  public mutating func clearConID() {self._conID = nil}

  public var providerCodes: String {
    get {_providerCodes ?? String()}
    set {_providerCodes = newValue}
  }
  /// Returns true if `providerCodes` has been explicitly set.
  public var hasProviderCodes: Bool {self._providerCodes != nil}
  /// Clears the value of `providerCodes`. Subsequent reads from it will return its default value.
  public mutating func clearProviderCodes() {self._providerCodes = nil}

  public var startDateTime: String {
    get {_startDateTime ?? String()}
    set {_startDateTime = newValue}
  }
  /// Returns true if `startDateTime` has been explicitly set.
  public var hasStartDateTime: Bool {self._startDateTime != nil}
  /// Clears the value of `startDateTime`. Subsequent reads from it will return its default value.
  public mutating func clearStartDateTime() {self._startDateTime = nil}

  public var endDateTime: String {
    get {_endDateTime ?? String()}
    set {_endDateTime = newValue}
  }
  /// Returns true if `endDateTime` has been explicitly set.
  public var hasEndDateTime: Bool {self._endDateTime != nil}
  /// Clears the value of `endDateTime`. Subsequent reads from it will return its default value.
  public mutating func clearEndDateTime() {self._endDateTime = nil}

  public var totalResults: Int32 {
    get {_totalResults ?? 0}
    set {_totalResults = newValue}
  }
  /// Returns true if `totalResults` has been explicitly set.
  public var hasTotalResults: Bool {self._totalResults != nil}
  /// Clears the value of `totalResults`. Subsequent reads from it will return its default value.
  public mutating func clearTotalResults() {self._totalResults = nil}

  public var historicalNewsOptions: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _conID: Int32? = nil
  fileprivate var _providerCodes: String? = nil
  fileprivate var _startDateTime: String? = nil
  fileprivate var _endDateTime: String? = nil
  fileprivate var _totalResults: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBHistoricalNewsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HistoricalNewsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}conId\0\u{1}providerCodes\0\u{1}startDateTime\0\u{1}endDateTime\0\u{1}totalResults\0\u{1}historicalNewsOptions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._conID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._providerCodes) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._startDateTime) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._endDateTime) }()
      case 6: try { try decoder.decodeSingularInt32Field(value: &self._totalResults) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.historicalNewsOptions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._conID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._providerCodes {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._startDateTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._endDateTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._totalResults {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 6)
    } }()
    if !self.historicalNewsOptions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.historicalNewsOptions, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBHistoricalNewsRequest, rhs: IBPBHistoricalNewsRequest) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._conID != rhs._conID {return false}
    if lhs._providerCodes != rhs._providerCodes {return false}
    if lhs._startDateTime != rhs._startDateTime {return false}
    if lhs._endDateTime != rhs._endDateTime {return false}
    if lhs._totalResults != rhs._totalResults {return false}
    if lhs.historicalNewsOptions != rhs.historicalNewsOptions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
