// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: HistoricalSession.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBHistoricalSession: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var startDateTime: String {
    get {_startDateTime ?? String()}
    set {_startDateTime = newValue}
  }
  /// Returns true if `startDateTime` has been explicitly set.
  public var hasStartDateTime: Bool {self._startDateTime != nil}
  /// Clears the value of `startDateTime`. Subsequent reads from it will return its default value.
  public mutating func clearStartDateTime() {self._startDateTime = nil}

  public var endDateTime: String {
    get {_endDateTime ?? String()}
    set {_endDateTime = newValue}
  }
  /// Returns true if `endDateTime` has been explicitly set.
  public var hasEndDateTime: Bool {self._endDateTime != nil}
  /// Clears the value of `endDateTime`. Subsequent reads from it will return its default value.
  public mutating func clearEndDateTime() {self._endDateTime = nil}

  public var refDate: String {
    get {_refDate ?? String()}
    set {_refDate = newValue}
  }
  /// Returns true if `refDate` has been explicitly set.
  public var hasRefDate: Bool {self._refDate != nil}
  /// Clears the value of `refDate`. Subsequent reads from it will return its default value.
  public mutating func clearRefDate() {self._refDate = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _startDateTime: String? = nil
  fileprivate var _endDateTime: String? = nil
  fileprivate var _refDate: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBHistoricalSession: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".HistoricalSession"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}startDateTime\0\u{1}endDateTime\0\u{1}refDate\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._startDateTime) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._endDateTime) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._refDate) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._startDateTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._endDateTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._refDate {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBHistoricalSession, rhs: IBPBHistoricalSession) -> Bool {
    if lhs._startDateTime != rhs._startDateTime {return false}
    if lhs._endDateTime != rhs._endDateTime {return false}
    if lhs._refDate != rhs._refDate {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
