// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: MarketDepthData.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBMarketDepthData: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var position: Int32 {
    get {_position ?? 0}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  public var operation: Int32 {
    get {_operation ?? 0}
    set {_operation = newValue}
  }
  /// Returns true if `operation` has been explicitly set.
  public var hasOperation: Bool {self._operation != nil}
  /// Clears the value of `operation`. Subsequent reads from it will return its default value.
  public mutating func clearOperation() {self._operation = nil}

  public var side: Int32 {
    get {_side ?? 0}
    set {_side = newValue}
  }
  /// Returns true if `side` has been explicitly set.
  public var hasSide: Bool {self._side != nil}
  /// Clears the value of `side`. Subsequent reads from it will return its default value.
  public mutating func clearSide() {self._side = nil}

  public var price: Double {
    get {_price ?? 0}
    set {_price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {self._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {self._price = nil}

  public var size: String {
    get {_size ?? String()}
    set {_size = newValue}
  }
  /// Returns true if `size` has been explicitly set.
  public var hasSize: Bool {self._size != nil}
  /// Clears the value of `size`. Subsequent reads from it will return its default value.
  public mutating func clearSize() {self._size = nil}

  public var marketMaker: String {
    get {_marketMaker ?? String()}
    set {_marketMaker = newValue}
  }
  /// Returns true if `marketMaker` has been explicitly set.
  public var hasMarketMaker: Bool {self._marketMaker != nil}
  /// Clears the value of `marketMaker`. Subsequent reads from it will return its default value.
  public mutating func clearMarketMaker() {self._marketMaker = nil}

  public var isSmartDepth: Bool {
    get {_isSmartDepth ?? false}
    set {_isSmartDepth = newValue}
  }
  /// Returns true if `isSmartDepth` has been explicitly set.
  public var hasIsSmartDepth: Bool {self._isSmartDepth != nil}
  /// Clears the value of `isSmartDepth`. Subsequent reads from it will return its default value.
  public mutating func clearIsSmartDepth() {self._isSmartDepth = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _position: Int32? = nil
  fileprivate var _operation: Int32? = nil
  fileprivate var _side: Int32? = nil
  fileprivate var _price: Double? = nil
  fileprivate var _size: String? = nil
  fileprivate var _marketMaker: String? = nil
  fileprivate var _isSmartDepth: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBMarketDepthData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".MarketDepthData"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}position\0\u{1}operation\0\u{1}side\0\u{1}price\0\u{1}size\0\u{1}marketMaker\0\u{1}isSmartDepth\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._position) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._operation) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._side) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._price) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._size) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._marketMaker) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._isSmartDepth) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._position {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._operation {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._side {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._price {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._size {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._marketMaker {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._isSmartDepth {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBMarketDepthData, rhs: IBPBMarketDepthData) -> Bool {
    if lhs._position != rhs._position {return false}
    if lhs._operation != rhs._operation {return false}
    if lhs._side != rhs._side {return false}
    if lhs._price != rhs._price {return false}
    if lhs._size != rhs._size {return false}
    if lhs._marketMaker != rhs._marketMaker {return false}
    if lhs._isSmartDepth != rhs._isSmartDepth {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
