// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: NewsArticleRequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBNewsArticleRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var providerCode: String {
    get {_providerCode ?? String()}
    set {_providerCode = newValue}
  }
  /// Returns true if `providerCode` has been explicitly set.
  public var hasProviderCode: Bool {self._providerCode != nil}
  /// Clears the value of `providerCode`. Subsequent reads from it will return its default value.
  public mutating func clearProviderCode() {self._providerCode = nil}

  public var articleID: String {
    get {_articleID ?? String()}
    set {_articleID = newValue}
  }
  /// Returns true if `articleID` has been explicitly set.
  public var hasArticleID: Bool {self._articleID != nil}
  /// Clears the value of `articleID`. Subsequent reads from it will return its default value.
  public mutating func clearArticleID() {self._articleID = nil}

  public var newsArticleOptions: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _providerCode: String? = nil
  fileprivate var _articleID: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBNewsArticleRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NewsArticleRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}providerCode\0\u{1}articleId\0\u{1}newsArticleOptions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._providerCode) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._articleID) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.newsArticleOptions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._providerCode {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._articleID {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    if !self.newsArticleOptions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.newsArticleOptions, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBNewsArticleRequest, rhs: IBPBNewsArticleRequest) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._providerCode != rhs._providerCode {return false}
    if lhs._articleID != rhs._articleID {return false}
    if lhs.newsArticleOptions != rhs.newsArticleOptions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
