// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: NewsBulletin.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBNewsBulletin: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var newsMsgID: Int32 {
    get {_newsMsgID ?? 0}
    set {_newsMsgID = newValue}
  }
  /// Returns true if `newsMsgID` has been explicitly set.
  public var hasNewsMsgID: Bool {self._newsMsgID != nil}
  /// Clears the value of `newsMsgID`. Subsequent reads from it will return its default value.
  public mutating func clearNewsMsgID() {self._newsMsgID = nil}

  public var newsMsgType: Int32 {
    get {_newsMsgType ?? 0}
    set {_newsMsgType = newValue}
  }
  /// Returns true if `newsMsgType` has been explicitly set.
  public var hasNewsMsgType: Bool {self._newsMsgType != nil}
  /// Clears the value of `newsMsgType`. Subsequent reads from it will return its default value.
  public mutating func clearNewsMsgType() {self._newsMsgType = nil}

  public var newsMessage: String {
    get {_newsMessage ?? String()}
    set {_newsMessage = newValue}
  }
  /// Returns true if `newsMessage` has been explicitly set.
  public var hasNewsMessage: Bool {self._newsMessage != nil}
  /// Clears the value of `newsMessage`. Subsequent reads from it will return its default value.
  public mutating func clearNewsMessage() {self._newsMessage = nil}

  public var originatingExch: String {
    get {_originatingExch ?? String()}
    set {_originatingExch = newValue}
  }
  /// Returns true if `originatingExch` has been explicitly set.
  public var hasOriginatingExch: Bool {self._originatingExch != nil}
  /// Clears the value of `originatingExch`. Subsequent reads from it will return its default value.
  public mutating func clearOriginatingExch() {self._originatingExch = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _newsMsgID: Int32? = nil
  fileprivate var _newsMsgType: Int32? = nil
  fileprivate var _newsMessage: String? = nil
  fileprivate var _originatingExch: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBNewsBulletin: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".NewsBulletin"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}newsMsgId\0\u{1}newsMsgType\0\u{1}newsMessage\0\u{1}originatingExch\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._newsMsgID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._newsMsgType) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._newsMessage) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._originatingExch) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._newsMsgID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._newsMsgType {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._newsMessage {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._originatingExch {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBNewsBulletin, rhs: IBPBNewsBulletin) -> Bool {
    if lhs._newsMsgID != rhs._newsMsgID {return false}
    if lhs._newsMsgType != rhs._newsMsgType {return false}
    if lhs._newsMessage != rhs._newsMessage {return false}
    if lhs._originatingExch != rhs._originatingExch {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
