// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: OpenOrder.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBOpenOrder: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var orderID: Int32 {
    get {_orderID ?? 0}
    set {_orderID = newValue}
  }
  /// Returns true if `orderID` has been explicitly set.
  public var hasOrderID: Bool {self._orderID != nil}
  /// Clears the value of `orderID`. Subsequent reads from it will return its default value.
  public mutating func clearOrderID() {self._orderID = nil}

  public var contract: IBPBContract {
    get {_contract ?? IBPBContract()}
    set {_contract = newValue}
  }
  /// Returns true if `contract` has been explicitly set.
  public var hasContract: Bool {self._contract != nil}
  /// Clears the value of `contract`. Subsequent reads from it will return its default value.
  public mutating func clearContract() {self._contract = nil}

  public var order: IBPBOrder {
    get {_order ?? IBPBOrder()}
    set {_order = newValue}
  }
  /// Returns true if `order` has been explicitly set.
  public var hasOrder: Bool {self._order != nil}
  /// Clears the value of `order`. Subsequent reads from it will return its default value.
  public mutating func clearOrder() {self._order = nil}

  public var orderState: IBPBOrderState {
    get {_orderState ?? IBPBOrderState()}
    set {_orderState = newValue}
  }
  /// Returns true if `orderState` has been explicitly set.
  public var hasOrderState: Bool {self._orderState != nil}
  /// Clears the value of `orderState`. Subsequent reads from it will return its default value.
  public mutating func clearOrderState() {self._orderState = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _orderID: Int32? = nil
  fileprivate var _contract: IBPBContract? = nil
  fileprivate var _order: IBPBOrder? = nil
  fileprivate var _orderState: IBPBOrderState? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBOpenOrder: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OpenOrder"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}orderId\0\u{1}contract\0\u{1}order\0\u{1}orderState\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._orderID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._contract) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._order) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._orderState) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._orderID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._contract {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._order {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._orderState {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBOpenOrder, rhs: IBPBOpenOrder) -> Bool {
    if lhs._orderID != rhs._orderID {return false}
    if lhs._contract != rhs._contract {return false}
    if lhs._order != rhs._order {return false}
    if lhs._orderState != rhs._orderState {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
