// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: OrderAllocation.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBOrderAllocation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var account: String {
    get {_account ?? String()}
    set {_account = newValue}
  }
  /// Returns true if `account` has been explicitly set.
  public var hasAccount: Bool {self._account != nil}
  /// Clears the value of `account`. Subsequent reads from it will return its default value.
  public mutating func clearAccount() {self._account = nil}

  public var position: String {
    get {_position ?? String()}
    set {_position = newValue}
  }
  /// Returns true if `position` has been explicitly set.
  public var hasPosition: Bool {self._position != nil}
  /// Clears the value of `position`. Subsequent reads from it will return its default value.
  public mutating func clearPosition() {self._position = nil}

  public var positionDesired: String {
    get {_positionDesired ?? String()}
    set {_positionDesired = newValue}
  }
  /// Returns true if `positionDesired` has been explicitly set.
  public var hasPositionDesired: Bool {self._positionDesired != nil}
  /// Clears the value of `positionDesired`. Subsequent reads from it will return its default value.
  public mutating func clearPositionDesired() {self._positionDesired = nil}

  public var positionAfter: String {
    get {_positionAfter ?? String()}
    set {_positionAfter = newValue}
  }
  /// Returns true if `positionAfter` has been explicitly set.
  public var hasPositionAfter: Bool {self._positionAfter != nil}
  /// Clears the value of `positionAfter`. Subsequent reads from it will return its default value.
  public mutating func clearPositionAfter() {self._positionAfter = nil}

  public var desiredAllocQty: String {
    get {_desiredAllocQty ?? String()}
    set {_desiredAllocQty = newValue}
  }
  /// Returns true if `desiredAllocQty` has been explicitly set.
  public var hasDesiredAllocQty: Bool {self._desiredAllocQty != nil}
  /// Clears the value of `desiredAllocQty`. Subsequent reads from it will return its default value.
  public mutating func clearDesiredAllocQty() {self._desiredAllocQty = nil}

  public var allowedAllocQty: String {
    get {_allowedAllocQty ?? String()}
    set {_allowedAllocQty = newValue}
  }
  /// Returns true if `allowedAllocQty` has been explicitly set.
  public var hasAllowedAllocQty: Bool {self._allowedAllocQty != nil}
  /// Clears the value of `allowedAllocQty`. Subsequent reads from it will return its default value.
  public mutating func clearAllowedAllocQty() {self._allowedAllocQty = nil}

  public var isMonetary: Bool {
    get {_isMonetary ?? false}
    set {_isMonetary = newValue}
  }
  /// Returns true if `isMonetary` has been explicitly set.
  public var hasIsMonetary: Bool {self._isMonetary != nil}
  /// Clears the value of `isMonetary`. Subsequent reads from it will return its default value.
  public mutating func clearIsMonetary() {self._isMonetary = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _account: String? = nil
  fileprivate var _position: String? = nil
  fileprivate var _positionDesired: String? = nil
  fileprivate var _positionAfter: String? = nil
  fileprivate var _desiredAllocQty: String? = nil
  fileprivate var _allowedAllocQty: String? = nil
  fileprivate var _isMonetary: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBOrderAllocation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OrderAllocation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}account\0\u{1}position\0\u{1}positionDesired\0\u{1}positionAfter\0\u{1}desiredAllocQty\0\u{1}allowedAllocQty\0\u{1}isMonetary\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._account) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._position) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._positionDesired) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._positionAfter) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._desiredAllocQty) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._allowedAllocQty) }()
      case 7: try { try decoder.decodeSingularBoolField(value: &self._isMonetary) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._account {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._position {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._positionDesired {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._positionAfter {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._desiredAllocQty {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._allowedAllocQty {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._isMonetary {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBOrderAllocation, rhs: IBPBOrderAllocation) -> Bool {
    if lhs._account != rhs._account {return false}
    if lhs._position != rhs._position {return false}
    if lhs._positionDesired != rhs._positionDesired {return false}
    if lhs._positionAfter != rhs._positionAfter {return false}
    if lhs._desiredAllocQty != rhs._desiredAllocQty {return false}
    if lhs._allowedAllocQty != rhs._allowedAllocQty {return false}
    if lhs._isMonetary != rhs._isMonetary {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
