// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: OrderCancel.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBOrderCancel: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var manualOrderCancelTime: String {
    get {_manualOrderCancelTime ?? String()}
    set {_manualOrderCancelTime = newValue}
  }
  /// Returns true if `manualOrderCancelTime` has been explicitly set.
  public var hasManualOrderCancelTime: Bool {self._manualOrderCancelTime != nil}
  /// Clears the value of `manualOrderCancelTime`. Subsequent reads from it will return its default value.
  public mutating func clearManualOrderCancelTime() {self._manualOrderCancelTime = nil}

  public var extOperator: String {
    get {_extOperator ?? String()}
    set {_extOperator = newValue}
  }
  /// Returns true if `extOperator` has been explicitly set.
  public var hasExtOperator: Bool {self._extOperator != nil}
  /// Clears the value of `extOperator`. Subsequent reads from it will return its default value.
  public mutating func clearExtOperator() {self._extOperator = nil}

  public var manualOrderIndicator: Int32 {
    get {_manualOrderIndicator ?? 0}
    set {_manualOrderIndicator = newValue}
  }
  /// Returns true if `manualOrderIndicator` has been explicitly set.
  public var hasManualOrderIndicator: Bool {self._manualOrderIndicator != nil}
  /// Clears the value of `manualOrderIndicator`. Subsequent reads from it will return its default value.
  public mutating func clearManualOrderIndicator() {self._manualOrderIndicator = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _manualOrderCancelTime: String? = nil
  fileprivate var _extOperator: String? = nil
  fileprivate var _manualOrderIndicator: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBOrderCancel: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OrderCancel"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}manualOrderCancelTime\0\u{1}extOperator\0\u{1}manualOrderIndicator\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._manualOrderCancelTime) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._extOperator) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._manualOrderIndicator) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._manualOrderCancelTime {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._extOperator {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._manualOrderIndicator {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBOrderCancel, rhs: IBPBOrderCancel) -> Bool {
    if lhs._manualOrderCancelTime != rhs._manualOrderCancelTime {return false}
    if lhs._extOperator != rhs._extOperator {return false}
    if lhs._manualOrderIndicator != rhs._manualOrderIndicator {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
