// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: OrderCondition.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBOrderCondition: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var type: Int32 {
    get {_type ?? 0}
    set {_type = newValue}
  }
  /// Returns true if `type` has been explicitly set.
  public var hasType: Bool {self._type != nil}
  /// Clears the value of `type`. Subsequent reads from it will return its default value.
  public mutating func clearType() {self._type = nil}

  public var isConjunctionConnection: Bool {
    get {_isConjunctionConnection ?? false}
    set {_isConjunctionConnection = newValue}
  }
  /// Returns true if `isConjunctionConnection` has been explicitly set.
  public var hasIsConjunctionConnection: Bool {self._isConjunctionConnection != nil}
  /// Clears the value of `isConjunctionConnection`. Subsequent reads from it will return its default value.
  public mutating func clearIsConjunctionConnection() {self._isConjunctionConnection = nil}

  public var isMore: Bool {
    get {_isMore ?? false}
    set {_isMore = newValue}
  }
  /// Returns true if `isMore` has been explicitly set.
  public var hasIsMore: Bool {self._isMore != nil}
  /// Clears the value of `isMore`. Subsequent reads from it will return its default value.
  public mutating func clearIsMore() {self._isMore = nil}

  public var conID: Int32 {
    get {_conID ?? 0}
    set {_conID = newValue}
  }
  /// Returns true if `conID` has been explicitly set.
  public var hasConID: Bool {self._conID != nil}
  /// Clears the value of `conID`. Subsequent reads from it will return its default value.
  public mutating func clearConID() {self._conID = nil}

  public var exchange: String {
    get {_exchange ?? String()}
    set {_exchange = newValue}
  }
  /// Returns true if `exchange` has been explicitly set.
  public var hasExchange: Bool {self._exchange != nil}
  /// Clears the value of `exchange`. Subsequent reads from it will return its default value.
  public mutating func clearExchange() {self._exchange = nil}

  public var symbol: String {
    get {_symbol ?? String()}
    set {_symbol = newValue}
  }
  /// Returns true if `symbol` has been explicitly set.
  public var hasSymbol: Bool {self._symbol != nil}
  /// Clears the value of `symbol`. Subsequent reads from it will return its default value.
  public mutating func clearSymbol() {self._symbol = nil}

  public var secType: String {
    get {_secType ?? String()}
    set {_secType = newValue}
  }
  /// Returns true if `secType` has been explicitly set.
  public var hasSecType: Bool {self._secType != nil}
  /// Clears the value of `secType`. Subsequent reads from it will return its default value.
  public mutating func clearSecType() {self._secType = nil}

  public var percent: Int32 {
    get {_percent ?? 0}
    set {_percent = newValue}
  }
  /// Returns true if `percent` has been explicitly set.
  public var hasPercent: Bool {self._percent != nil}
  /// Clears the value of `percent`. Subsequent reads from it will return its default value.
  public mutating func clearPercent() {self._percent = nil}

  public var changePercent: Double {
    get {_changePercent ?? 0}
    set {_changePercent = newValue}
  }
  /// Returns true if `changePercent` has been explicitly set.
  public var hasChangePercent: Bool {self._changePercent != nil}
  /// Clears the value of `changePercent`. Subsequent reads from it will return its default value.
  public mutating func clearChangePercent() {self._changePercent = nil}

  public var price: Double {
    get {_price ?? 0}
    set {_price = newValue}
  }
  /// Returns true if `price` has been explicitly set.
  public var hasPrice: Bool {self._price != nil}
  /// Clears the value of `price`. Subsequent reads from it will return its default value.
  public mutating func clearPrice() {self._price = nil}

  public var triggerMethod: Int32 {
    get {_triggerMethod ?? 0}
    set {_triggerMethod = newValue}
  }
  /// Returns true if `triggerMethod` has been explicitly set.
  public var hasTriggerMethod: Bool {self._triggerMethod != nil}
  /// Clears the value of `triggerMethod`. Subsequent reads from it will return its default value.
  public mutating func clearTriggerMethod() {self._triggerMethod = nil}

  public var time: String {
    get {_time ?? String()}
    set {_time = newValue}
  }
  /// Returns true if `time` has been explicitly set.
  public var hasTime: Bool {self._time != nil}
  /// Clears the value of `time`. Subsequent reads from it will return its default value.
  public mutating func clearTime() {self._time = nil}

  public var volume: Int32 {
    get {_volume ?? 0}
    set {_volume = newValue}
  }
  /// Returns true if `volume` has been explicitly set.
  public var hasVolume: Bool {self._volume != nil}
  /// Clears the value of `volume`. Subsequent reads from it will return its default value.
  public mutating func clearVolume() {self._volume = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _type: Int32? = nil
  fileprivate var _isConjunctionConnection: Bool? = nil
  fileprivate var _isMore: Bool? = nil
  fileprivate var _conID: Int32? = nil
  fileprivate var _exchange: String? = nil
  fileprivate var _symbol: String? = nil
  fileprivate var _secType: String? = nil
  fileprivate var _percent: Int32? = nil
  fileprivate var _changePercent: Double? = nil
  fileprivate var _price: Double? = nil
  fileprivate var _triggerMethod: Int32? = nil
  fileprivate var _time: String? = nil
  fileprivate var _volume: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBOrderCondition: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".OrderCondition"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}type\0\u{1}isConjunctionConnection\0\u{1}isMore\0\u{1}conId\0\u{1}exchange\0\u{1}symbol\0\u{1}secType\0\u{1}percent\0\u{1}changePercent\0\u{1}price\0\u{1}triggerMethod\0\u{1}time\0\u{1}volume\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._type) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self._isConjunctionConnection) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._isMore) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._conID) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._exchange) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._symbol) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._secType) }()
      case 8: try { try decoder.decodeSingularInt32Field(value: &self._percent) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self._changePercent) }()
      case 10: try { try decoder.decodeSingularDoubleField(value: &self._price) }()
      case 11: try { try decoder.decodeSingularInt32Field(value: &self._triggerMethod) }()
      case 12: try { try decoder.decodeSingularStringField(value: &self._time) }()
      case 13: try { try decoder.decodeSingularInt32Field(value: &self._volume) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._type {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._isConjunctionConnection {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._isMore {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._conID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._exchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._symbol {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._secType {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._percent {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._changePercent {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._price {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._triggerMethod {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._time {
      try visitor.visitSingularStringField(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._volume {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 13)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBOrderCondition, rhs: IBPBOrderCondition) -> Bool {
    if lhs._type != rhs._type {return false}
    if lhs._isConjunctionConnection != rhs._isConjunctionConnection {return false}
    if lhs._isMore != rhs._isMore {return false}
    if lhs._conID != rhs._conID {return false}
    if lhs._exchange != rhs._exchange {return false}
    if lhs._symbol != rhs._symbol {return false}
    if lhs._secType != rhs._secType {return false}
    if lhs._percent != rhs._percent {return false}
    if lhs._changePercent != rhs._changePercent {return false}
    if lhs._price != rhs._price {return false}
    if lhs._triggerMethod != rhs._triggerMethod {return false}
    if lhs._time != rhs._time {return false}
    if lhs._volume != rhs._volume {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
