// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: PnL.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBPnL: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var dailyPnL: Double {
    get {_dailyPnL ?? 0}
    set {_dailyPnL = newValue}
  }
  /// Returns true if `dailyPnL` has been explicitly set.
  public var hasDailyPnL: Bool {self._dailyPnL != nil}
  /// Clears the value of `dailyPnL`. Subsequent reads from it will return its default value.
  public mutating func clearDailyPnL() {self._dailyPnL = nil}

  public var unrealizedPnL: Double {
    get {_unrealizedPnL ?? 0}
    set {_unrealizedPnL = newValue}
  }
  /// Returns true if `unrealizedPnL` has been explicitly set.
  public var hasUnrealizedPnL: Bool {self._unrealizedPnL != nil}
  /// Clears the value of `unrealizedPnL`. Subsequent reads from it will return its default value.
  public mutating func clearUnrealizedPnL() {self._unrealizedPnL = nil}

  public var realizedPnL: Double {
    get {_realizedPnL ?? 0}
    set {_realizedPnL = newValue}
  }
  /// Returns true if `realizedPnL` has been explicitly set.
  public var hasRealizedPnL: Bool {self._realizedPnL != nil}
  /// Clears the value of `realizedPnL`. Subsequent reads from it will return its default value.
  public mutating func clearRealizedPnL() {self._realizedPnL = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _dailyPnL: Double? = nil
  fileprivate var _unrealizedPnL: Double? = nil
  fileprivate var _realizedPnL: Double? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBPnL: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".PnL"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}dailyPnL\0\u{1}unrealizedPnL\0\u{1}realizedPnL\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularDoubleField(value: &self._dailyPnL) }()
      case 3: try { try decoder.decodeSingularDoubleField(value: &self._unrealizedPnL) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._realizedPnL) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._dailyPnL {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._unrealizedPnL {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._realizedPnL {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBPnL, rhs: IBPBPnL) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._dailyPnL != rhs._dailyPnL {return false}
    if lhs._unrealizedPnL != rhs._unrealizedPnL {return false}
    if lhs._realizedPnL != rhs._realizedPnL {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
