// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: RealTimeBarsRequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBRealTimeBarsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var contract: IBPBContract {
    get {_contract ?? IBPBContract()}
    set {_contract = newValue}
  }
  /// Returns true if `contract` has been explicitly set.
  public var hasContract: Bool {self._contract != nil}
  /// Clears the value of `contract`. Subsequent reads from it will return its default value.
  public mutating func clearContract() {self._contract = nil}

  public var barSize: Int32 {
    get {_barSize ?? 0}
    set {_barSize = newValue}
  }
  /// Returns true if `barSize` has been explicitly set.
  public var hasBarSize: Bool {self._barSize != nil}
  /// Clears the value of `barSize`. Subsequent reads from it will return its default value.
  public mutating func clearBarSize() {self._barSize = nil}

  public var whatToShow: String {
    get {_whatToShow ?? String()}
    set {_whatToShow = newValue}
  }
  /// Returns true if `whatToShow` has been explicitly set.
  public var hasWhatToShow: Bool {self._whatToShow != nil}
  /// Clears the value of `whatToShow`. Subsequent reads from it will return its default value.
  public mutating func clearWhatToShow() {self._whatToShow = nil}

  public var useRth: Bool {
    get {_useRth ?? false}
    set {_useRth = newValue}
  }
  /// Returns true if `useRth` has been explicitly set.
  public var hasUseRth: Bool {self._useRth != nil}
  /// Clears the value of `useRth`. Subsequent reads from it will return its default value.
  public mutating func clearUseRth() {self._useRth = nil}

  public var realTimeBarsOptions: Dictionary<String,String> = [:]

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _contract: IBPBContract? = nil
  fileprivate var _barSize: Int32? = nil
  fileprivate var _whatToShow: String? = nil
  fileprivate var _useRth: Bool? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBRealTimeBarsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".RealTimeBarsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}contract\0\u{1}barSize\0\u{1}whatToShow\0\u{1}useRTH\0\u{1}realTimeBarsOptions\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._contract) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._barSize) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._whatToShow) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._useRth) }()
      case 6: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.realTimeBarsOptions) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._contract {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._barSize {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._whatToShow {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._useRth {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    if !self.realTimeBarsOptions.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.realTimeBarsOptions, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBRealTimeBarsRequest, rhs: IBPBRealTimeBarsRequest) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._contract != rhs._contract {return false}
    if lhs._barSize != rhs._barSize {return false}
    if lhs._whatToShow != rhs._whatToShow {return false}
    if lhs._useRth != rhs._useRth {return false}
    if lhs.realTimeBarsOptions != rhs.realTimeBarsOptions {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
