// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: ScannerDataElement.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBScannerDataElement: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var rank: Int32 {
    get {_rank ?? 0}
    set {_rank = newValue}
  }
  /// Returns true if `rank` has been explicitly set.
  public var hasRank: Bool {self._rank != nil}
  /// Clears the value of `rank`. Subsequent reads from it will return its default value.
  public mutating func clearRank() {self._rank = nil}

  public var contract: IBPBContract {
    get {_contract ?? IBPBContract()}
    set {_contract = newValue}
  }
  /// Returns true if `contract` has been explicitly set.
  public var hasContract: Bool {self._contract != nil}
  /// Clears the value of `contract`. Subsequent reads from it will return its default value.
  public mutating func clearContract() {self._contract = nil}

  public var marketName: String {
    get {_marketName ?? String()}
    set {_marketName = newValue}
  }
  /// Returns true if `marketName` has been explicitly set.
  public var hasMarketName: Bool {self._marketName != nil}
  /// Clears the value of `marketName`. Subsequent reads from it will return its default value.
  public mutating func clearMarketName() {self._marketName = nil}

  public var distance: String {
    get {_distance ?? String()}
    set {_distance = newValue}
  }
  /// Returns true if `distance` has been explicitly set.
  public var hasDistance: Bool {self._distance != nil}
  /// Clears the value of `distance`. Subsequent reads from it will return its default value.
  public mutating func clearDistance() {self._distance = nil}

  public var benchmark: String {
    get {_benchmark ?? String()}
    set {_benchmark = newValue}
  }
  /// Returns true if `benchmark` has been explicitly set.
  public var hasBenchmark: Bool {self._benchmark != nil}
  /// Clears the value of `benchmark`. Subsequent reads from it will return its default value.
  public mutating func clearBenchmark() {self._benchmark = nil}

  public var projection: String {
    get {_projection ?? String()}
    set {_projection = newValue}
  }
  /// Returns true if `projection` has been explicitly set.
  public var hasProjection: Bool {self._projection != nil}
  /// Clears the value of `projection`. Subsequent reads from it will return its default value.
  public mutating func clearProjection() {self._projection = nil}

  public var comboKey: String {
    get {_comboKey ?? String()}
    set {_comboKey = newValue}
  }
  /// Returns true if `comboKey` has been explicitly set.
  public var hasComboKey: Bool {self._comboKey != nil}
  /// Clears the value of `comboKey`. Subsequent reads from it will return its default value.
  public mutating func clearComboKey() {self._comboKey = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _rank: Int32? = nil
  fileprivate var _contract: IBPBContract? = nil
  fileprivate var _marketName: String? = nil
  fileprivate var _distance: String? = nil
  fileprivate var _benchmark: String? = nil
  fileprivate var _projection: String? = nil
  fileprivate var _comboKey: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBScannerDataElement: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".ScannerDataElement"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}rank\0\u{1}contract\0\u{1}marketName\0\u{1}distance\0\u{1}benchmark\0\u{1}projection\0\u{1}comboKey\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._rank) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._contract) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._marketName) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._distance) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._benchmark) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._projection) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._comboKey) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._rank {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._contract {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._marketName {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._distance {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._benchmark {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._projection {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._comboKey {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBScannerDataElement, rhs: IBPBScannerDataElement) -> Bool {
    if lhs._rank != rhs._rank {return false}
    if lhs._contract != rhs._contract {return false}
    if lhs._marketName != rhs._marketName {return false}
    if lhs._distance != rhs._distance {return false}
    if lhs._benchmark != rhs._benchmark {return false}
    if lhs._projection != rhs._projection {return false}
    if lhs._comboKey != rhs._comboKey {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
