// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: SecDefOptParamsRequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBSecDefOptParamsRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var underlyingSymbol: String {
    get {_underlyingSymbol ?? String()}
    set {_underlyingSymbol = newValue}
  }
  /// Returns true if `underlyingSymbol` has been explicitly set.
  public var hasUnderlyingSymbol: Bool {self._underlyingSymbol != nil}
  /// Clears the value of `underlyingSymbol`. Subsequent reads from it will return its default value.
  public mutating func clearUnderlyingSymbol() {self._underlyingSymbol = nil}

  public var futFopExchange: String {
    get {_futFopExchange ?? String()}
    set {_futFopExchange = newValue}
  }
  /// Returns true if `futFopExchange` has been explicitly set.
  public var hasFutFopExchange: Bool {self._futFopExchange != nil}
  /// Clears the value of `futFopExchange`. Subsequent reads from it will return its default value.
  public mutating func clearFutFopExchange() {self._futFopExchange = nil}

  public var underlyingSecType: String {
    get {_underlyingSecType ?? String()}
    set {_underlyingSecType = newValue}
  }
  /// Returns true if `underlyingSecType` has been explicitly set.
  public var hasUnderlyingSecType: Bool {self._underlyingSecType != nil}
  /// Clears the value of `underlyingSecType`. Subsequent reads from it will return its default value.
  public mutating func clearUnderlyingSecType() {self._underlyingSecType = nil}

  public var underlyingConID: Int32 {
    get {_underlyingConID ?? 0}
    set {_underlyingConID = newValue}
  }
  /// Returns true if `underlyingConID` has been explicitly set.
  public var hasUnderlyingConID: Bool {self._underlyingConID != nil}
  /// Clears the value of `underlyingConID`. Subsequent reads from it will return its default value.
  public mutating func clearUnderlyingConID() {self._underlyingConID = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _underlyingSymbol: String? = nil
  fileprivate var _futFopExchange: String? = nil
  fileprivate var _underlyingSecType: String? = nil
  fileprivate var _underlyingConID: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBSecDefOptParamsRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".SecDefOptParamsRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}underlyingSymbol\0\u{1}futFopExchange\0\u{1}underlyingSecType\0\u{1}underlyingConId\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._underlyingSymbol) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._futFopExchange) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self._underlyingSecType) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self._underlyingConID) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._underlyingSymbol {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._futFopExchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._underlyingSecType {
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._underlyingConID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBSecDefOptParamsRequest, rhs: IBPBSecDefOptParamsRequest) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._underlyingSymbol != rhs._underlyingSymbol {return false}
    if lhs._futFopExchange != rhs._futFopExchange {return false}
    if lhs._underlyingSecType != rhs._underlyingSecType {return false}
    if lhs._underlyingConID != rhs._underlyingConID {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
