// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: TickReqParams.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBTickReqParams: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var minTick: String {
    get {_minTick ?? String()}
    set {_minTick = newValue}
  }
  /// Returns true if `minTick` has been explicitly set.
  public var hasMinTick: Bool {self._minTick != nil}
  /// Clears the value of `minTick`. Subsequent reads from it will return its default value.
  public mutating func clearMinTick() {self._minTick = nil}

  public var bboExchange: String {
    get {_bboExchange ?? String()}
    set {_bboExchange = newValue}
  }
  /// Returns true if `bboExchange` has been explicitly set.
  public var hasBboExchange: Bool {self._bboExchange != nil}
  /// Clears the value of `bboExchange`. Subsequent reads from it will return its default value.
  public mutating func clearBboExchange() {self._bboExchange = nil}

  public var snapshotPermissions: Int32 {
    get {_snapshotPermissions ?? 0}
    set {_snapshotPermissions = newValue}
  }
  /// Returns true if `snapshotPermissions` has been explicitly set.
  public var hasSnapshotPermissions: Bool {self._snapshotPermissions != nil}
  /// Clears the value of `snapshotPermissions`. Subsequent reads from it will return its default value.
  public mutating func clearSnapshotPermissions() {self._snapshotPermissions = nil}

  public var lastPricePrecision: String {
    get {_lastPricePrecision ?? String()}
    set {_lastPricePrecision = newValue}
  }
  /// Returns true if `lastPricePrecision` has been explicitly set.
  public var hasLastPricePrecision: Bool {self._lastPricePrecision != nil}
  /// Clears the value of `lastPricePrecision`. Subsequent reads from it will return its default value.
  public mutating func clearLastPricePrecision() {self._lastPricePrecision = nil}

  public var lastSizePrecision: String {
    get {_lastSizePrecision ?? String()}
    set {_lastSizePrecision = newValue}
  }
  /// Returns true if `lastSizePrecision` has been explicitly set.
  public var hasLastSizePrecision: Bool {self._lastSizePrecision != nil}
  /// Clears the value of `lastSizePrecision`. Subsequent reads from it will return its default value.
  public mutating func clearLastSizePrecision() {self._lastSizePrecision = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _minTick: String? = nil
  fileprivate var _bboExchange: String? = nil
  fileprivate var _snapshotPermissions: Int32? = nil
  fileprivate var _lastPricePrecision: String? = nil
  fileprivate var _lastSizePrecision: String? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBTickReqParams: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TickReqParams"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}minTick\0\u{1}bboExchange\0\u{1}snapshotPermissions\0\u{1}lastPricePrecision\0\u{1}lastSizePrecision\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._minTick) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._bboExchange) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._snapshotPermissions) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._lastPricePrecision) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self._lastSizePrecision) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._minTick {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._bboExchange {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._snapshotPermissions {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._lastPricePrecision {
      try visitor.visitSingularStringField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._lastSizePrecision {
      try visitor.visitSingularStringField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBTickReqParams, rhs: IBPBTickReqParams) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._minTick != rhs._minTick {return false}
    if lhs._bboExchange != rhs._bboExchange {return false}
    if lhs._snapshotPermissions != rhs._snapshotPermissions {return false}
    if lhs._lastPricePrecision != rhs._lastPricePrecision {return false}
    if lhs._lastSizePrecision != rhs._lastSizePrecision {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
