// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: TickOptionComputation.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBTickOptionComputation: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var tickType: Int32 {
    get {_tickType ?? 0}
    set {_tickType = newValue}
  }
  /// Returns true if `tickType` has been explicitly set.
  public var hasTickType: Bool {self._tickType != nil}
  /// Clears the value of `tickType`. Subsequent reads from it will return its default value.
  public mutating func clearTickType() {self._tickType = nil}

  public var tickAttrib: Int32 {
    get {_tickAttrib ?? 0}
    set {_tickAttrib = newValue}
  }
  /// Returns true if `tickAttrib` has been explicitly set.
  public var hasTickAttrib: Bool {self._tickAttrib != nil}
  /// Clears the value of `tickAttrib`. Subsequent reads from it will return its default value.
  public mutating func clearTickAttrib() {self._tickAttrib = nil}

  public var impliedVol: Double {
    get {_impliedVol ?? 0}
    set {_impliedVol = newValue}
  }
  /// Returns true if `impliedVol` has been explicitly set.
  public var hasImpliedVol: Bool {self._impliedVol != nil}
  /// Clears the value of `impliedVol`. Subsequent reads from it will return its default value.
  public mutating func clearImpliedVol() {self._impliedVol = nil}

  public var delta: Double {
    get {_delta ?? 0}
    set {_delta = newValue}
  }
  /// Returns true if `delta` has been explicitly set.
  public var hasDelta: Bool {self._delta != nil}
  /// Clears the value of `delta`. Subsequent reads from it will return its default value.
  public mutating func clearDelta() {self._delta = nil}

  public var optPrice: Double {
    get {_optPrice ?? 0}
    set {_optPrice = newValue}
  }
  /// Returns true if `optPrice` has been explicitly set.
  public var hasOptPrice: Bool {self._optPrice != nil}
  /// Clears the value of `optPrice`. Subsequent reads from it will return its default value.
  public mutating func clearOptPrice() {self._optPrice = nil}

  public var pvDividend: Double {
    get {_pvDividend ?? 0}
    set {_pvDividend = newValue}
  }
  /// Returns true if `pvDividend` has been explicitly set.
  public var hasPvDividend: Bool {self._pvDividend != nil}
  /// Clears the value of `pvDividend`. Subsequent reads from it will return its default value.
  public mutating func clearPvDividend() {self._pvDividend = nil}

  public var gamma: Double {
    get {_gamma ?? 0}
    set {_gamma = newValue}
  }
  /// Returns true if `gamma` has been explicitly set.
  public var hasGamma: Bool {self._gamma != nil}
  /// Clears the value of `gamma`. Subsequent reads from it will return its default value.
  public mutating func clearGamma() {self._gamma = nil}

  public var vega: Double {
    get {_vega ?? 0}
    set {_vega = newValue}
  }
  /// Returns true if `vega` has been explicitly set.
  public var hasVega: Bool {self._vega != nil}
  /// Clears the value of `vega`. Subsequent reads from it will return its default value.
  public mutating func clearVega() {self._vega = nil}

  public var theta: Double {
    get {_theta ?? 0}
    set {_theta = newValue}
  }
  /// Returns true if `theta` has been explicitly set.
  public var hasTheta: Bool {self._theta != nil}
  /// Clears the value of `theta`. Subsequent reads from it will return its default value.
  public mutating func clearTheta() {self._theta = nil}

  public var undPrice: Double {
    get {_undPrice ?? 0}
    set {_undPrice = newValue}
  }
  /// Returns true if `undPrice` has been explicitly set.
  public var hasUndPrice: Bool {self._undPrice != nil}
  /// Clears the value of `undPrice`. Subsequent reads from it will return its default value.
  public mutating func clearUndPrice() {self._undPrice = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _tickType: Int32? = nil
  fileprivate var _tickAttrib: Int32? = nil
  fileprivate var _impliedVol: Double? = nil
  fileprivate var _delta: Double? = nil
  fileprivate var _optPrice: Double? = nil
  fileprivate var _pvDividend: Double? = nil
  fileprivate var _gamma: Double? = nil
  fileprivate var _vega: Double? = nil
  fileprivate var _theta: Double? = nil
  fileprivate var _undPrice: Double? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBTickOptionComputation: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".TickOptionComputation"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}tickType\0\u{1}tickAttrib\0\u{1}impliedVol\0\u{1}delta\0\u{1}optPrice\0\u{1}pvDividend\0\u{1}gamma\0\u{1}vega\0\u{1}theta\0\u{1}undPrice\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._tickType) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._tickAttrib) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._impliedVol) }()
      case 5: try { try decoder.decodeSingularDoubleField(value: &self._delta) }()
      case 6: try { try decoder.decodeSingularDoubleField(value: &self._optPrice) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self._pvDividend) }()
      case 8: try { try decoder.decodeSingularDoubleField(value: &self._gamma) }()
      case 9: try { try decoder.decodeSingularDoubleField(value: &self._vega) }()
      case 10: try { try decoder.decodeSingularDoubleField(value: &self._theta) }()
      case 11: try { try decoder.decodeSingularDoubleField(value: &self._undPrice) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._tickType {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._tickAttrib {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._impliedVol {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._delta {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._optPrice {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._pvDividend {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._gamma {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._vega {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._theta {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._undPrice {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 11)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBTickOptionComputation, rhs: IBPBTickOptionComputation) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._tickType != rhs._tickType {return false}
    if lhs._tickAttrib != rhs._tickAttrib {return false}
    if lhs._impliedVol != rhs._impliedVol {return false}
    if lhs._delta != rhs._delta {return false}
    if lhs._optPrice != rhs._optPrice {return false}
    if lhs._pvDividend != rhs._pvDividend {return false}
    if lhs._gamma != rhs._gamma {return false}
    if lhs._vega != rhs._vega {return false}
    if lhs._theta != rhs._theta {return false}
    if lhs._undPrice != rhs._undPrice {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
