// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: UpdateConfigRequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBUpdateConfigRequest: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_storage._reqID ?? 0}
    set {_uniqueStorage()._reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {_storage._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {_uniqueStorage()._reqID = nil}

  public var lockAndExit: IBPBLockAndExitConfig {
    get {_storage._lockAndExit ?? IBPBLockAndExitConfig()}
    set {_uniqueStorage()._lockAndExit = newValue}
  }
  /// Returns true if `lockAndExit` has been explicitly set.
  public var hasLockAndExit: Bool {_storage._lockAndExit != nil}
  /// Clears the value of `lockAndExit`. Subsequent reads from it will return its default value.
  public mutating func clearLockAndExit() {_uniqueStorage()._lockAndExit = nil}

  public var messages: [IBPBMessageConfig] {
    get {_storage._messages}
    set {_uniqueStorage()._messages = newValue}
  }

  public var api: IBPBApiConfig {
    get {_storage._api ?? IBPBApiConfig()}
    set {_uniqueStorage()._api = newValue}
  }
  /// Returns true if `api` has been explicitly set.
  public var hasApi: Bool {_storage._api != nil}
  /// Clears the value of `api`. Subsequent reads from it will return its default value.
  public mutating func clearApi() {_uniqueStorage()._api = nil}

  public var orders: IBPBOrdersConfig {
    get {_storage._orders ?? IBPBOrdersConfig()}
    set {_uniqueStorage()._orders = newValue}
  }
  /// Returns true if `orders` has been explicitly set.
  public var hasOrders: Bool {_storage._orders != nil}
  /// Clears the value of `orders`. Subsequent reads from it will return its default value.
  public mutating func clearOrders() {_uniqueStorage()._orders = nil}

  public var acceptedWarnings: [IBPBUpdateConfigWarning] {
    get {_storage._acceptedWarnings}
    set {_uniqueStorage()._acceptedWarnings = newValue}
  }

  public var resetApiorderSequence: Bool {
    get {_storage._resetApiorderSequence ?? false}
    set {_uniqueStorage()._resetApiorderSequence = newValue}
  }
  /// Returns true if `resetApiorderSequence` has been explicitly set.
  public var hasResetApiorderSequence: Bool {_storage._resetApiorderSequence != nil}
  /// Clears the value of `resetApiorderSequence`. Subsequent reads from it will return its default value.
  public mutating func clearResetApiorderSequence() {_uniqueStorage()._resetApiorderSequence = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBUpdateConfigRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".UpdateConfigRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}lockAndExit\0\u{1}messages\0\u{1}api\0\u{1}orders\0\u{1}acceptedWarnings\0\u{1}resetAPIOrderSequence\0")

  fileprivate class _StorageClass {
    var _reqID: Int32? = nil
    var _lockAndExit: IBPBLockAndExitConfig? = nil
    var _messages: [IBPBMessageConfig] = []
    var _api: IBPBApiConfig? = nil
    var _orders: IBPBOrdersConfig? = nil
    var _acceptedWarnings: [IBPBUpdateConfigWarning] = []
    var _resetApiorderSequence: Bool? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _reqID = source._reqID
      _lockAndExit = source._lockAndExit
      _messages = source._messages
      _api = source._api
      _orders = source._orders
      _acceptedWarnings = source._acceptedWarnings
      _resetApiorderSequence = source._resetApiorderSequence
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._reqID) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._lockAndExit) }()
        case 3: try { try decoder.decodeRepeatedMessageField(value: &_storage._messages) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._api) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._orders) }()
        case 6: try { try decoder.decodeRepeatedMessageField(value: &_storage._acceptedWarnings) }()
        case 7: try { try decoder.decodeSingularBoolField(value: &_storage._resetApiorderSequence) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._reqID {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._lockAndExit {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._messages.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._messages, fieldNumber: 3)
      }
      try { if let v = _storage._api {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._orders {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._acceptedWarnings.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._acceptedWarnings, fieldNumber: 6)
      }
      try { if let v = _storage._resetApiorderSequence {
        try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBUpdateConfigRequest, rhs: IBPBUpdateConfigRequest) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._reqID != rhs_storage._reqID {return false}
        if _storage._lockAndExit != rhs_storage._lockAndExit {return false}
        if _storage._messages != rhs_storage._messages {return false}
        if _storage._api != rhs_storage._api {return false}
        if _storage._orders != rhs_storage._orders {return false}
        if _storage._acceptedWarnings != rhs_storage._acceptedWarnings {return false}
        if _storage._resetApiorderSequence != rhs_storage._resetApiorderSequence {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
