// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: WshEventDataRequest.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

//
// Protobuf TWS API
//
// Copyright (C) 2013-2026  Interactive Brokers LLC
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate nonisolated struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public nonisolated struct IBPBWshEventDataRequest: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var reqID: Int32 {
    get {_reqID ?? 0}
    set {_reqID = newValue}
  }
  /// Returns true if `reqID` has been explicitly set.
  public var hasReqID: Bool {self._reqID != nil}
  /// Clears the value of `reqID`. Subsequent reads from it will return its default value.
  public mutating func clearReqID() {self._reqID = nil}

  public var conID: Int32 {
    get {_conID ?? 0}
    set {_conID = newValue}
  }
  /// Returns true if `conID` has been explicitly set.
  public var hasConID: Bool {self._conID != nil}
  /// Clears the value of `conID`. Subsequent reads from it will return its default value.
  public mutating func clearConID() {self._conID = nil}

  public var filter: String {
    get {_filter ?? String()}
    set {_filter = newValue}
  }
  /// Returns true if `filter` has been explicitly set.
  public var hasFilter: Bool {self._filter != nil}
  /// Clears the value of `filter`. Subsequent reads from it will return its default value.
  public mutating func clearFilter() {self._filter = nil}

  public var fillWatchlist: Bool {
    get {_fillWatchlist ?? false}
    set {_fillWatchlist = newValue}
  }
  /// Returns true if `fillWatchlist` has been explicitly set.
  public var hasFillWatchlist: Bool {self._fillWatchlist != nil}
  /// Clears the value of `fillWatchlist`. Subsequent reads from it will return its default value.
  public mutating func clearFillWatchlist() {self._fillWatchlist = nil}

  public var fillPortfolio: Bool {
    get {_fillPortfolio ?? false}
    set {_fillPortfolio = newValue}
  }
  /// Returns true if `fillPortfolio` has been explicitly set.
  public var hasFillPortfolio: Bool {self._fillPortfolio != nil}
  /// Clears the value of `fillPortfolio`. Subsequent reads from it will return its default value.
  public mutating func clearFillPortfolio() {self._fillPortfolio = nil}

  public var fillCompetitors: Bool {
    get {_fillCompetitors ?? false}
    set {_fillCompetitors = newValue}
  }
  /// Returns true if `fillCompetitors` has been explicitly set.
  public var hasFillCompetitors: Bool {self._fillCompetitors != nil}
  /// Clears the value of `fillCompetitors`. Subsequent reads from it will return its default value.
  public mutating func clearFillCompetitors() {self._fillCompetitors = nil}

  public var startDate: String {
    get {_startDate ?? String()}
    set {_startDate = newValue}
  }
  /// Returns true if `startDate` has been explicitly set.
  public var hasStartDate: Bool {self._startDate != nil}
  /// Clears the value of `startDate`. Subsequent reads from it will return its default value.
  public mutating func clearStartDate() {self._startDate = nil}

  public var endDate: String {
    get {_endDate ?? String()}
    set {_endDate = newValue}
  }
  /// Returns true if `endDate` has been explicitly set.
  public var hasEndDate: Bool {self._endDate != nil}
  /// Clears the value of `endDate`. Subsequent reads from it will return its default value.
  public mutating func clearEndDate() {self._endDate = nil}

  public var totalLimit: Int32 {
    get {_totalLimit ?? 0}
    set {_totalLimit = newValue}
  }
  /// Returns true if `totalLimit` has been explicitly set.
  public var hasTotalLimit: Bool {self._totalLimit != nil}
  /// Clears the value of `totalLimit`. Subsequent reads from it will return its default value.
  public mutating func clearTotalLimit() {self._totalLimit = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _reqID: Int32? = nil
  fileprivate var _conID: Int32? = nil
  fileprivate var _filter: String? = nil
  fileprivate var _fillWatchlist: Bool? = nil
  fileprivate var _fillPortfolio: Bool? = nil
  fileprivate var _fillCompetitors: Bool? = nil
  fileprivate var _startDate: String? = nil
  fileprivate var _endDate: String? = nil
  fileprivate var _totalLimit: Int32? = nil
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate nonisolated let _protobuf_package = "protobuf"

nonisolated extension IBPBWshEventDataRequest: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".WshEventDataRequest"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}reqId\0\u{1}conId\0\u{1}filter\0\u{1}fillWatchlist\0\u{1}fillPortfolio\0\u{1}fillCompetitors\0\u{1}startDate\0\u{1}endDate\0\u{1}totalLimit\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._reqID) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._conID) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._filter) }()
      case 4: try { try decoder.decodeSingularBoolField(value: &self._fillWatchlist) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._fillPortfolio) }()
      case 6: try { try decoder.decodeSingularBoolField(value: &self._fillCompetitors) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self._startDate) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self._endDate) }()
      case 9: try { try decoder.decodeSingularInt32Field(value: &self._totalLimit) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._reqID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._conID {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._filter {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._fillWatchlist {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._fillPortfolio {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._fillCompetitors {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._startDate {
      try visitor.visitSingularStringField(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._endDate {
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._totalLimit {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 9)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: IBPBWshEventDataRequest, rhs: IBPBWshEventDataRequest) -> Bool {
    if lhs._reqID != rhs._reqID {return false}
    if lhs._conID != rhs._conID {return false}
    if lhs._filter != rhs._filter {return false}
    if lhs._fillWatchlist != rhs._fillWatchlist {return false}
    if lhs._fillPortfolio != rhs._fillPortfolio {return false}
    if lhs._fillCompetitors != rhs._fillCompetitors {return false}
    if lhs._startDate != rhs._startDate {return false}
    if lhs._endDate != rhs._endDate {return false}
    if lhs._totalLimit != rhs._totalLimit {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
